/**
 * Toko suvenir, oleh-oleh & kerajinan Jakarta yang terdaftar di TripAdvisor.
 *
 * Sumber: crawl TripAdvisor geo g294229 (Jakarta), kategori Shopping (c26),
 * subkategori Gift & Specialty Shops + Antique Stores + Flea & Street Markets.
 * Alamat, koordinat, telepon, rating & jumlah ulasan diambil dari JSON-LD
 * halaman detail TripAdvisor; `relevance`, `product`, kota/kecamatan, status
 * dan validasi koordinat diverifikasi lewat penelusuran sumber terbuka
 * (Google Maps, situs/IG toko, artikel berita).
 *
 * CATATAN PENTING: TripAdvisor memasukkan banyak usaha yang BUKAN toko suvenir
 * ke kategori "Gift & Specialty Shops" (money changer, service HP, toko
 * elektronik, toko sepeda). Field `relevance` memisahkannya — pakai
 * `souvenirShops()` untuk hanya mengambil yang relevan.
 *
 * Dibangun otomatis oleh scripts/build-souvenir.ts dari
 * data-souvenir-GCI-jakarta.tsv — jangan diedit manual.
 */

export type SouvenirShop = {
  id: string;
  name: string;
  /** Subkategori Shopping TripAdvisor. */
  category: string;
  /** Ya = toko suvenir sungguhan; Sebagian = sebagian menjual suvenir; Tidak = bukan. */
  relevance: string;
  product?: string;
  address?: string;
  city?: string;
  district?: string;
  lat?: number;
  lng?: number;
  coordSource?: string;
  phone?: string;
  rating?: number;
  reviews?: number;
  status?: string;
  note?: string;
  url?: string;
};

export const SOUVENIR_SHOPS: SouvenirShop[] = [
  {
    "id": "flea-market-at-jalan-surabaya",
    "name": "Flea Market at Jalan Surabaya",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Ya",
    "product": "Barang antik & peta kuno",
    "address": "Surabaya St No.20-21 , Jakarta, 10310",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.197372,
    "lng": 106.839195,
    "coordSource": "TripAdvisor",
    "rating": 3.8,
    "reviews": 410,
    "status": "Aktif",
    "note": "Pasar antik/suvenir legendaris sejak 1980 di Jl. Surabaya, Menteng; jual wayang, batik, perhiasan, barang antik. Sumber: Tripadvisor, forevervacation.com, ajourneybespoke.com",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d2587868"
  },
  {
    "id": "batik-keris",
    "name": "Batik Keris",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Batik",
    "address": "Jakarta",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.1931,
    "lng": 106.8217,
    "coordSource": "Koreksi riset",
    "rating": 4.2,
    "reviews": 64,
    "status": "Aktif",
    "note": "Alamat sebenarnya Plaza Indonesia Lt.3 No.116C, Jl MH Thamrin, Gondangdia, Menteng, Jakarta Pusat (dari teks ulasan TripAdvisor); koordinat input meleset ~15km ke arah Cengkareng/perbatasan Tangerang, dikoreksi ke Plaza Indonesia. Sumber: tripadvisor.com, batikkeris.co.id.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d379331"
  },
  {
    "id": "pasar-seni-ancol",
    "name": "Pasar Seni Ancol",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Kerajinan tangan & lukisan (pasar seni)",
    "address": "Jl. Gerbang Ancol no. 93, Pademangan, Jakarta, 14430",
    "city": "Jakarta Utara",
    "district": "Pademangan",
    "lat": -6.126677,
    "lng": 106.83876,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 64713218",
    "rating": 3.4,
    "reviews": 35,
    "status": "Aktif",
    "note": "Pasar seni/kerajinan sejak 1977 di kompleks Ancol, ~240 lapak seniman; kecamatan Pademangan dari sumber flokq/ancol.com, koordinat sesuai area Ancol",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d9563968"
  },
  {
    "id": "rawa-bening-market",
    "name": "Rawa Bening Market",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Perhiasan/emas (batu akik, permata, kerajinan perak)",
    "address": "Jln. Stasiun, Jakarta, 12240",
    "city": "Jakarta Timur",
    "district": "Jatinegara",
    "lat": -6.215,
    "lng": 106.8703,
    "coordSource": "Koreksi riset",
    "phone": "+62 21 8197064",
    "rating": 3.6,
    "reviews": 11,
    "status": "Aktif",
    "note": "Jakarta Gems Center, tepat di depan Stasiun Jatinegara, Kec. Jatinegara — populer di kalangan wisatawan asing utk batu akik/perhiasan sbg suvenir. Koordinat input meleset ~10km (mengarah ke area Kebayoran/Blok M), dikoreksi ke sekitar Stasiun Jatinegara. Sebagian toko tutup namun pasar tetap beroperasi. Sumber: beritajakarta.id, detik.com, traveloka.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d6598978"
  },
  {
    "id": "bartele-gallery",
    "name": "Bartele Gallery",
    "category": "Toko Barang Antik",
    "relevance": "Ya",
    "product": "Barang antik & peta kuno",
    "address": "Jl. M.H. Thamrin Mandarin Oriental Hotel - 2nd floor, Jakarta, 10310",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.19604,
    "lng": 106.82356,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 29938997",
    "rating": 4.8,
    "reviews": 5,
    "status": "Aktif",
    "note": "Galeri peta & cetakan antik Asia sejak 2009, di Mandarin Oriental Hotel Jl MH Thamrin Menteng; sumber nowjakarta.co.id, bartelegallery.com. Ada info belum terverifikasi soal kemungkinan pindah ke Hotel Kempinski",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d12423972"
  },
  {
    "id": "khas-jakarta",
    "name": "Khas Jakarta",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Oleh-oleh makanan & suvenir Betawi",
    "address": "Jl. Thamrin Boulevard blok H5 no. 6 Thamrin City Lantai 1, Jakarta, 11110",
    "city": "Jakarta Pusat",
    "district": "Tanah Abang",
    "lat": -6.194593,
    "lng": 106.81542,
    "coordSource": "TripAdvisor",
    "phone": "+62 856-8593-383",
    "rating": 3.6,
    "reviews": 5,
    "status": "Aktif",
    "note": "Pusat oleh-oleh resmi (dodol Betawi, batik, ondel-ondel dll) di Thamrin City lt.1; kecamatan dari GoFood/near-place (Kb. Melati, Tanah Abang, kodepos 10230 - beda dgn kodepos 11110 di data asal, kemungkinan salah input); koordinat sesuai lokasi Thamrin City",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d7076588"
  },
  {
    "id": "rajanya-promosi",
    "name": "Rajanya Promosi",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Suvenir custom/merchandise (tumbler, gift set, dll)",
    "address": "Jl. Hankam No. 13, RT.6/RW.9 Jl. Siyarridin I, Jakarta, 12550",
    "city": "Jakarta Selatan",
    "district": "Pasar Minggu",
    "lat": -6.286373,
    "lng": 106.82381,
    "coordSource": "TripAdvisor",
    "phone": "+62 812-9907-6453",
    "rating": 5,
    "reviews": 4,
    "status": "Aktif",
    "note": "Vendor merchandise/suvenir custom (tumbler, flashdisk, gift set) area Ragunan/Jl. Hankam, Pasar Minggu (sumber: rajanyapromosi.com, facebook.com/RajanyaSouvenir). Koordinat cukup plausibel untuk area Ragunan meski tidak presisi ke titik jalan.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d28897061"
  },
  {
    "id": "batik-obate",
    "name": "Batik Obate",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Batik",
    "address": "Jl. Teuku Nyak Arief no. 10 Simprug Gallery Unit Blok S, Jakarta, 12220",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Lama",
    "lat": -6.23496,
    "lng": 106.78532,
    "coordSource": "TripAdvisor",
    "phone": "+62 811-9303-789",
    "rating": 5,
    "reviews": 3,
    "status": "Aktif",
    "note": "Toko batik (Yogya/Solo/Pekalongan) di Ruko Simprug Gallery; sumber Tripadvisor & near-place.com, tercatat aktif.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d12976615"
  },
  {
    "id": "lucy-s-batik-jakarta",
    "name": "Lucy's Batik - Jakarta",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Batik & kerajinan tangan",
    "address": "Jl. Kemang Raya No.30 Mitra Hadiprana 1st Floor, Jakarta, 12730",
    "city": "Jakarta Selatan",
    "district": "Mampang Prapatan",
    "lat": -6.260612,
    "lng": 106.815186,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 7182767",
    "rating": 4.7,
    "reviews": 3,
    "status": "Aktif",
    "note": "Butik batik & kerajinan Nusantara di Mitra Hadiprana Kemang; sumber lucysbatik.com & mitrahadiprana.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d16162508"
  },
  {
    "id": "paisley-things",
    "name": "Paisley Things",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Kerajinan tangan artisan lokal (dekorasi rumah)",
    "address": "Jln. Bumi no. 31a, Jakarta, 12120",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.24063,
    "lng": 106.78974,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 27510156",
    "rating": 4.3,
    "reviews": 3,
    "status": "Aktif",
    "note": "Toko kerajinan artisan lokal yg mendukung Darius Tobing Foundation, est. 2011, alamat Jl. Bumi No.31A Kebayoran Baru (indonesiaexpat.id, ajourneybespoke.com); ada akun IG @paisleythingsjakarta aktif",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d10161748"
  },
  {
    "id": "indies-gallery-antique-maps-prints-of-in",
    "name": "Indies Gallery - Antique Maps & Prints of Indonesia",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Barang antik & peta kuno",
    "address": "Jl. Kemang Raya No. 8B Aksara Bookstore, Jakarta, 12730",
    "city": "Jakarta Selatan",
    "district": "Mampang Prapatan",
    "lat": -6.256469,
    "lng": 106.81471,
    "coordSource": "TripAdvisor",
    "phone": "+62 813-1900-4269",
    "rating": 3,
    "reviews": 2,
    "status": "Tidak diketahui",
    "note": "\"Beralamat \"\"di dalam Aksara Bookstore Kemang\"\", namun Aksara Bookstore Kemang dilaporkan tutup permanen Des 2020; kemungkinan alamat sudah tidak berlaku. Sumber Jakarta Post/Detik.\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d18966670"
  },
  {
    "id": "mariami",
    "name": "Mariami",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "?",
    "address": "Jl. Petogogan II No.32 Blok A, Jakarta, 12140",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.25085,
    "lng": 106.79397,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 29126264",
    "rating": 3,
    "reviews": 2,
    "status": "Tidak diketahui",
    "note": "Terdaftar di Tripadvisor kategori Gift & Specialty Shops namun produk spesifik tidak ditemukan (ulasan sangat sedikit); tidak bisa diverifikasi lebih lanjut.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d15618584"
  },
  {
    "id": "souvennir-tumbler-murah",
    "name": "Souvennir Tumbler Murah",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Suvenir custom/merchandise (tumbler custom)",
    "address": "Komplek MPR, Jl. Flamboyan No.B11, Jakarta, 12430",
    "city": "Jakarta Selatan",
    "district": "Cilandak",
    "lat": -6.282774,
    "lng": 106.805466,
    "coordSource": "TripAdvisor",
    "phone": "+62 821-2339-7985",
    "rating": 5,
    "reviews": 2,
    "status": "Aktif",
    "note": "Produsen/toko suvenir tumbler custom murah, alamat Komplek MPR Jl. Flamboyan (Pondok Labu, Cilandak) sesuai postcode 12430 (sumber: souvenirtumblermurah.com). Koordinat plausibel untuk area Cilandak.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d32684407"
  },
  {
    "id": "indonesia-senyum",
    "name": "Indonesia Senyum",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Suvenir custom/merchandise (kaos, aksesoris, poster bertema Jakarta)",
    "address": "Jl. Panglima Polim No.37, RT.1/RW.1, Melawai Tenant Inside M Bloc Market, Jakarta, 12160",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.241794,
    "lng": 106.79899,
    "coordSource": "TripAdvisor",
    "rating": 5,
    "reviews": 1,
    "status": "Tidak diketahui",
    "note": "Tenant kecil di M Bloc Market Melawai menjual aksesoris, kaos, dan poster bertema Jakarta versi kartun — disebut sebagai tempat suvenir otentik Jakarta (sumber: ulasan TripAdvisor Des 2024). Koordinat cocok dengan lokasi M Bloc Market. Status operasional tidak dapat dipastikan lebih lanjut.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d32709906"
  },
  {
    "id": "oleholehku-id",
    "name": "Oleholehku.id",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Oleh-oleh UMKM (makanan & kerajinan)",
    "address": "Jalan Plot DKI, Block D9 Duren Palm Sub-district, Jakarta, 13440",
    "city": "Jakarta Timur",
    "district": "Duren Sawit",
    "lat": -6.230917,
    "lng": 106.914639,
    "coordSource": "Koreksi riset",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "\"Toko oleh-oleh UMKM binaan Dinas PPKUKM DKI, alamat asli Duren Sawit (bukan \"\"Duren Palm\"\" spt di data), sesuai artikel disppkukm.jakarta.go.id; koordinat sumber (-6.130224,106.706795) berada di wilayah Jakarta Barat, jauh dari Duren Sawit (~-6.23,106.91) — koreksi adalah titik kelurahan Duren Sawit (perkiraan, bukan alamat toko persis)\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d25159960"
  },
  {
    "id": "poster-house-77",
    "name": "Poster House 77",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Poster vintage & suvenir custom",
    "address": "Jalan Kemang Timur Raya No 77, Jakarta, 12730",
    "city": "Jakarta Selatan",
    "district": "Mampang Prapatan",
    "lat": -6.259977,
    "lng": 106.82344,
    "coordSource": "TripAdvisor",
    "phone": "+62 877-2347-6577",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Toko poster vintage/suvenir di Kemang Timur, kel. Bangka; terverifikasi via TripAdvisor & kodepos.id, koordinat sesuai area Bangka-Mampang Prapatan",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d23027735"
  },
  {
    "id": "souvenir-tumbler-murah",
    "name": "Souvenir Tumbler Murah",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Suvenir custom/merchandise",
    "address": "Jl. Flamboyan No.B11, Cilandak Bar., Kec. Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12430, Jakarta, 12430",
    "city": "Jakarta Selatan",
    "district": "Cilandak",
    "lat": -6.283486,
    "lng": 106.80547,
    "coordSource": "TripAdvisor",
    "phone": "+62 812-9907-6453",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Vendor suvenir custom (tumbler, mug, boneka) grosir min. 500pcs, alamat sesuai situs souvenirtumblermurah.com; kecamatan dari alamat/kodepos",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d34036099"
  },
  {
    "id": "batik-koenokoeni",
    "name": "Batik KoenoKoeni",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Batik",
    "address": "Jl. Cipete Raya no. 8A, Jakarta, 12410",
    "city": "Jakarta Selatan",
    "district": "Cilandak",
    "lat": -6.27773,
    "lng": 106.80483,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 22705821",
    "status": "Tidak diketahui",
    "note": "Toko pakaian batik (kemeja/blus) di Jl. Cipete Raya No.8A; kecamatan Cilandak dari kodepos 12410/near-place.com; IG @batikkoenokoeni ada tapi aktivitas terbaru tidak terverifikasi",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d12778506"
  },
  {
    "id": "khas-jakarta-kota-tua",
    "name": "Khas Jakarta Kota Tua",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Oleh-oleh makanan & suvenir khas Jakarta",
    "address": "Jl. Taman Fatahillah No.3 Kota Tua Post Office, Jakarta, 11110",
    "city": "Jakarta Barat",
    "district": "Taman Sari",
    "lat": -6.134133,
    "lng": 106.81322,
    "coordSource": "TripAdvisor",
    "phone": "+62 896-7880-8034",
    "status": "Aktif",
    "note": "Toko oleh-oleh (dodol Betawi, bir pletok, kaos, gantungan kunci, batik) di kawasan Taman Fatahillah; sumber Okezone & Tripadvisor.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d17713976"
  },
  {
    "id": "maison-amare-studio",
    "name": "Maison Amare Studio",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Suvenir custom/merchandise (parfum custom)",
    "address": "Jl. Letjen S.Parman No.Kav 21 Mal Taman Anggrek, Lt. G, Jakarta, 11470",
    "city": "Jakarta Barat",
    "district": "Grogol Petamburan",
    "lat": -6.178342,
    "lng": 106.792595,
    "coordSource": "TripAdvisor",
    "phone": "+62 823-1334-9096",
    "status": "Aktif",
    "note": "Studio parfum custom Korea (KPIA) di Mal Taman Anggrek — pengunjung meracik dan membawa pulang parfum sendiri sebagai suvenir/gift (sumber: maisonamare.com, corner.inc). Koordinat sangat cocok dengan lokasi Mal Taman Anggrek.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d33053752"
  },
  {
    "id": "neng-mae",
    "name": "Neng Mae",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Oleh-oleh makanan (jajanan Betawi)",
    "address": "Jl. Rorotan IV No.51, RT.10/RW.06, Rorotan, Kec. Cilincing, Jkt Utara, Daerah Khusus Ibukota Jakarta 14140, Jakarta, 14140",
    "city": "Jakarta Utara",
    "district": "Cilincing",
    "lat": -6.151821,
    "lng": 106.95545,
    "coordSource": "TripAdvisor",
    "phone": "+62 813-1211-6030",
    "status": "Aktif",
    "note": "\"Toko oleh-oleh Jakarta \"\"Neng Mae\"\" (IG @nengmae.id, PIRT & Halal MUI, toko offline di Rorotan); juga terdaftar di GoFood/GrabFood sbg Jajanan Betawi Neng Mae\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d34469473"
  },
  {
    "id": "royalkueid",
    "name": "Royalkueid",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Oleh-oleh makanan (bakpao gandum halal)",
    "address": "Pantai Indah Kapuk St. Fresh Market PIK, TP 22, Jakarta, 14470",
    "city": "Jakarta Utara",
    "district": "Penjaringan",
    "lat": -6.104652,
    "lng": 106.74207,
    "coordSource": "TripAdvisor",
    "phone": "+62 813-8265-9808",
    "status": "Aktif",
    "note": "Usaha bakpao gandum halal (aneka rasa) di Fresh Market PIK, Kamal Muara, Penjaringan (sumber: instagram.com/royalkueid, youtube Royal Kue ID). Koordinat cocok dengan lokasi Fresh Market PIK.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d32867928"
  },
  {
    "id": "sidikalang-jaya-coffee-store",
    "name": "Sidikalang Jaya Coffee Store",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Ya",
    "product": "Oleh-oleh makanan (kopi)",
    "address": "Jl. Seni Budaya Raya No.7A, Jakarta, 11460",
    "city": "Jakarta Barat",
    "district": "Grogol Petamburan",
    "coordSource": "Koordinat TripAdvisor salah, belum ada koreksi",
    "phone": "+62 816-1717-8119",
    "status": "Aktif",
    "note": "Toko kopi grosir/eceran sejak 1984; alamat terverifikasi di Jelambar Baru (dekat Jl. Jelambar Utara) tapi koordinat yang diberikan (-6.1878,106.79098) meleset ~4km dari pusat Jelambar Baru (~-6.150,106.783); tidak ditemukan koordinat pengganti presisi dari sumber tepercaya. Sumber infokopi.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d20110209"
  },
  {
    "id": "cikini-gold-center",
    "name": "Cikini Gold Center",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Perhiasan/emas",
    "address": "Jln. Pegangsaan Barat/Timur, Jakarta, 10320",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.198286,
    "lng": 106.84164,
    "coordSource": "TripAdvisor",
    "phone": "+62 131 9090 88",
    "rating": 4,
    "reviews": 322,
    "status": "Aktif",
    "note": "Pusat pertokoan emas/perhiasan 7 lantai (60+ toko), bukan suvenir turis tapi jadi daya tarik belanja; alamat & kec. dari Waze/KF Map (Jl. Pegangsaan Timur No.9, Menteng), koordinat cocok area Menteng",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d6725477"
  },
  {
    "id": "tanah-abang-market",
    "name": "Tanah Abang Market",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Sebagian",
    "product": "Tekstil/batik grosir",
    "address": "Jl. Fachrudin 5 Stasiun Pasarsenen, Jakarta, 10250",
    "city": "Jakarta Pusat",
    "district": "Tanah Abang",
    "lat": -6.187184,
    "lng": 106.8153,
    "coordSource": "TripAdvisor",
    "rating": 3.8,
    "reviews": 307,
    "status": "Aktif",
    "note": "Pasar grosir pakaian & batik terbesar Jakarta; suvenir bukan fokus utama, lebih ke tekstil/fashion grosir. Sumber: Tripadvisor, Waze (Pasar Tanah Abang Blok A, Jl. K.H. Fachrudin)",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d3640861"
  },
  {
    "id": "pasaraya-the-pride-of-indonesia",
    "name": "Pasaraya, the Pride of Indonesia",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Pasar campuran (department store dgn batik/kerajinan)",
    "address": "Blok M Jln. Iskandarsyah II 2 Kebayoran Baru, Jakarta, 12160",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.241865,
    "lng": 106.800766,
    "coordSource": "TripAdvisor",
    "phone": "+62 622 18312674",
    "rating": 3.9,
    "reviews": 74,
    "status": "Aktif",
    "note": "Department store lama (sejak 1958) di Jl Iskandarsyah II No.2, Kebayoran Baru; masih beroperasi (situs resmi pasaraya.id aktif) meski okupansi menurun. Sumber: pasaraya.id, kumparan.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d3264840"
  },
  {
    "id": "pasar-asemka",
    "name": "Pasar Asemka",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Suvenir custom/merchandise & aksesori grosir",
    "address": "Jl. Raya Pantura, Jakarta, 11110",
    "city": "Jakarta Barat",
    "district": "Taman Sari",
    "lat": -6.138857,
    "lng": 106.81249,
    "coordSource": "TripAdvisor",
    "rating": 3.9,
    "reviews": 43,
    "status": "Aktif",
    "note": "Pusat grosir aksesori & suvenir di Jl Asemka No.33, Pinangsia, Kec. Taman Sari; pengunjung menurun tapi masih beroperasi. Sumber: flokq.com, investortrust.id.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d3845753"
  },
  {
    "id": "mangga-dua-morning-market",
    "name": "Mangga Dua Morning Market",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Sebagian",
    "product": "Pasar campuran (fashion, kerajinan manik-manik, alat tulis)",
    "address": "Jl. Mangga Dua Raya, Jakarta, 14430",
    "city": "Jakarta Utara",
    "district": "Pademangan",
    "lat": -6.13629,
    "lng": 106.821884,
    "coordSource": "TripAdvisor",
    "phone": "+021 600 4840",
    "rating": 3.8,
    "reviews": 33,
    "status": "Aktif",
    "note": "Pasar grosir pakaian 5 lantai (Pasar Pagi Mangga Dua), kelurahan Ancol, kec. Pademangan, kodepos 14430; ada toko kerajinan manik-manik tapi mayoritas fashion grosir. Sumber: kumparan.com, idalamat.com",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d8330603"
  },
  {
    "id": "pasar-ular",
    "name": "Pasar Ular",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Pasar campuran (pakaian/sepatu branded KW, aksesori)",
    "address": "Jln. Plumpang B, Jakarta, 14230",
    "city": "Jakarta Utara",
    "district": "Koja",
    "lat": -6.12357,
    "lng": 106.90005,
    "coordSource": "TripAdvisor",
    "rating": 3.6,
    "reviews": 10,
    "status": "Aktif",
    "note": "Pasar di Jl Plumpang Semper/Inspeksi Kali Sunter, Rawa Badak Selatan, Kec. Koja; makin sepi pembeli namun masih buka per 2024-2025. Sumber: kompas.com, detik.com, beritajakarta.id.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d3844811"
  },
  {
    "id": "pasar-tebet-barat",
    "name": "Pasar Tebet Barat",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Sebagian",
    "product": "Pasar campuran (kebutuhan sehari-hari, ada penjual suvenir kecil)",
    "address": "Jl. Tebet Barat Dalam Raya, Jakarta, 12810",
    "city": "Jakarta Selatan",
    "district": "Tebet",
    "lat": -6.23449,
    "lng": 106.84656,
    "coordSource": "TripAdvisor",
    "rating": 4,
    "reviews": 3,
    "status": "Aktif",
    "note": "\"Pasar tradisional harian; disebutkan ada \"\"souvenir vendors\"\" tapi mayoritas sembako/kuliner, bukan tujuan wisata suvenir. Alamat resmi: Jl. Tebet Barat Dalam Raya No.11, Kec. Tebet, Jakarta Selatan 12810 (pasarjaya.co.id). Sumber: flokq.com, saungmaman.com\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d12459860"
  },
  {
    "id": "by-the-sea-mall",
    "name": "By The Sea Mall",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Distrik belanja lokal (fashion, kecantikan, F&B)",
    "address": "Pantai Maju Golf Island Pik Pik 2, Jakarta",
    "city": "Jakarta Utara",
    "district": "Penjaringan",
    "rating": 4.5,
    "reviews": 2,
    "status": "Aktif",
    "note": "Kawasan belanja semi-outdoor di Golf Island/Pantai Maju, PIK2, kel. Kamal Muara; lat/lng tidak tersedia di data sumber sehingga tak bisa divalidasi; sumber: CNN Indonesia, Tempo, situs resmi Golf Island",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d25090320"
  },
  {
    "id": "cocona-care",
    "name": "Cocona Care",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Produk perawatan tubuh minyak kelapa (bisa jadi oleh-oleh)",
    "address": "Jl RS Fatmawati no. 39, Jakarta, 12430",
    "city": "Jakarta Selatan",
    "district": "Cilandak",
    "lat": -6.28647,
    "lng": 106.79553,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 75906515",
    "rating": 4.5,
    "reviews": 2,
    "status": "Aktif",
    "note": "Toko produk body care berbahan virgin coconut oil, juga ada cabang Bali; alamat Jl. RS Fatmawati No.39 Cilandak (littlestepsasia.com, facebook.com/CoconaCareID)",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d11864940"
  },
  {
    "id": "gema-collection",
    "name": "Gema Collection",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Kain/tekstil (pasar campuran Mayestik)",
    "address": "Jl. Tebah III No.107 Mayestik Market, Jakarta, 12120",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "rating": 2,
    "reviews": 1,
    "status": "Tidak diketahui",
    "note": "Tenant di dalam Pasar Mayestik (pasar kain/tekstil), bukan toko suvenir spesifik; rating rendah (2.0, 1 ulasan) di TripAdvisor, tidak ditemukan situs/sosmed resmi untuk verifikasi lebih lanjut. Tidak ada lat/lng di data asal sehingga validitas koordinat tidak dapat dinilai.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d28564979"
  },
  {
    "id": "hublife-mall",
    "name": "Hublife Mall",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Pusat perbelanjaan campuran (F&B, ritel, ice-skating)",
    "address": "Jl. Tanjung Duren Timur No.2, Rt.12/rw.5, Tj. Duren Selatan, Jakarta, 11470",
    "city": "Jakarta Barat",
    "district": "Grogol Petamburan",
    "rating": 4,
    "reviews": 1,
    "status": "Aktif",
    "note": "Mal di Tj. Duren Timur (Taman Anggrek Residences), kel. Tanjung Duren Selatan; lat/lng tidak tersedia di data sumber sehingga tak bisa divalidasi; sumber: hublife.co.id, TripAdvisor",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d25066794"
  },
  {
    "id": "kirana-livin-at-alun-alun-indonesia",
    "name": "KIRANA LIVIN at Alun Alun Indonesia",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Sebagian",
    "product": "Pasar campuran (kerajinan, batik, kuliner khas)",
    "address": "Grand Indonesia, West Mall, 3rd Floor, Jl. MH Thamrin No.1, RT.1/RW.5 Menteng, Jakarta, 10310",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.196113,
    "lng": 106.822945,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 23580890",
    "status": "Aktif",
    "note": "Merupakan bagian dari Alun Alun Indonesia, department store budaya Indonesia (fashion, perhiasan, kerajinan, kuliner) di lt.3 West Mall Grand Indonesia; sumber: grand-indonesia.com & tripadvisor",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d34473610"
  },
  {
    "id": "cosma-studio-id",
    "name": "Cosma Studio.id",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "?",
    "product": "?",
    "address": "Jl Mandala Utara IV No 26 Rt 6 Rw 6 Tomang, Jakarta, 11440",
    "city": "Jakarta Barat",
    "district": "Grogol Petamburan",
    "lat": -6.172637,
    "lng": 106.79731,
    "coordSource": "TripAdvisor",
    "phone": "+62 811-1800-518",
    "status": "Tidak diketahui",
    "note": "\"Tidak ditemukan info spesifik ttg \"\"Cosma Studio.id\"\" di Mandala Utara IV Tomang; tidak bisa diverifikasi jenis usahanya. Kecamatan dari alamat (Tomang) & kodepos 11440\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d34469706"
  },
  {
    "id": "gong-ye",
    "name": "Gong-Ye",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "?",
    "product": "?",
    "address": "Jl. Daan Mogot KM.1 No.45, Jakarta, 11470",
    "city": "Jakarta Barat",
    "district": "Grogol Petamburan",
    "lat": -6.16576,
    "lng": 106.783295,
    "coordSource": "TripAdvisor",
    "phone": "+62 821-9601-5530",
    "status": "Tidak diketahui",
    "note": "Tidak ditemukan info memadai selain listing TripAdvisor (dikategorikan sbg museum di TripAdvisor ID, No.58/73 museum Jakarta); kecamatan dari kodepos 11470 (Grogol Petamburan)",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d34311250"
  },
  {
    "id": "aneka-foto",
    "name": "Aneka Foto",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Samanhudi No.19-20 Blok AKS Metro Atom Plaza, RT.20/RW.3, Ps. Baru, Jakarta, 10710",
    "city": "Jakarta Pusat",
    "district": "Sawah Besar",
    "lat": -6.1656,
    "lng": 106.8306,
    "coordSource": "Koreksi riset",
    "phone": "+62 21 3457933",
    "rating": 5,
    "reviews": 18,
    "status": "Aktif",
    "note": "Toko kamera & fotografi sejak 1991 di Metro Atom Plaza Pasar Baru, bukan toko suvenir (sumber: anekafoto.com, tripadvisor). Koordinat asli (-6.2838,106.7804) jauh dari Pasar Baru/Sawah Besar (sekitar 15km); koreksi ke titik Metro Atom Plaza Pasar Baru (perkiraan umum, belum diverifikasi presisi GPS).",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d28114445"
  },
  {
    "id": "fish-market-pasar-ikan",
    "name": "Fish Market (Pasar Ikan)",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Tidak",
    "address": "Jln. Sunda Kelapa, Jakarta, 14440",
    "city": "Jakarta Utara",
    "district": "Penjaringan",
    "lat": -6.12347,
    "lng": 106.81047,
    "coordSource": "TripAdvisor",
    "rating": 3.7,
    "reviews": 17,
    "status": "Aktif",
    "note": "\"Nama jalan/kawasan historis \"\"Jalan Pasar Ikan\"\" dekat Museum Bahari & Pelabuhan Sunda Kelapa, Kota Tua; bukan toko suvenir. Kecamatan dari kodepos 14440 (Penjaringan)\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d379326"
  },
  {
    "id": "rawa-belong-flower-market",
    "name": "Rawa Belong Flower Market",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jalan Sulaiman Raya No.50, Jakarta, 11540",
    "city": "Jakarta Barat",
    "district": "Kebon Jeruk",
    "lat": -6.205949,
    "lng": 106.77842,
    "coordSource": "TripAdvisor",
    "rating": 3.8,
    "reviews": 12,
    "status": "Aktif",
    "note": "Pasar bunga terbesar se-Asia Tenggara di Jl Sulaiman No.50/56, Sukabumi Utara, Kec. Kebon Jeruk; bukan toko suvenir. Koordinat input cocok dengan titik Google Maps. Sumber: google maps, wanderlog.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d6598992"
  },
  {
    "id": "galeries-lafayette",
    "name": "Galeries Lafayette",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Pacific Place Mall, SCBD Jl. Jend. Sudirman, Jakarta",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.22798,
    "lng": 106.80896,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 57973343",
    "rating": 4.2,
    "reviews": 10,
    "status": "Aktif",
    "note": "Department store fashion mewah di Pacific Place, SCBD, Kel. Senayan, Kec. Kebayoran Baru; bukan toko suvenir/oleh-oleh, masih terdaftar aktif di direktori pacificplace.co.id. Sumber: pacificplace.co.id, map.co.id.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d4424695"
  },
  {
    "id": "electronic-city",
    "name": "Electronic City",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Jenderal Sudirman Kav. 52-53 Sudirman Central Business District, Jakarta, 12190",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.2261,
    "lng": 106.8114,
    "coordSource": "Koreksi riset",
    "phone": "+62 21 1500032",
    "rating": 3.1,
    "reviews": 8,
    "status": "Aktif",
    "note": "Toko elektronik, bukan suvenir. Koordinat asal (-6.34,106.85) meleset jauh ke selatan (area Jagakarsa), lokasi asli SCBD Senayan/Kby Baru sekitar -6.226,106.811 (Google Maps via Wanderlog); reopening store dikonfirmasi Nov 2024",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d8403837"
  },
  {
    "id": "gembrong-market",
    "name": "Gembrong Market",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jakarta, 13320",
    "city": "Jakarta Timur",
    "district": "Jatinegara",
    "rating": 3.3,
    "reviews": 6,
    "status": "Aktif",
    "note": "Pasar mainan anak grosir/eceran di Jl Jend Basuki Rachmat, Prumpung/Cipinang Besar Utara, Kec. Jatinegara; bukan kategori suvenir wisata. Tidak ada koordinat pada data sumber sehingga tidak bisa divalidasi. Sumber: tribunjakarta.com, jejakpiknik.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d6536286"
  },
  {
    "id": "muara-baru-modern-fish-market",
    "name": "Muara Baru Modern Fish Market",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Tidak",
    "address": "Jl. Muara Baru Raya North Jakarta City, Jakarta, 14440",
    "city": "Jakarta Utara",
    "district": "Penjaringan",
    "lat": -6.12129,
    "lng": 106.80384,
    "coordSource": "TripAdvisor",
    "rating": 3.8,
    "reviews": 5,
    "status": "Aktif",
    "note": "Pasar ikan modern (PIM), diresmikan 2019, bukan toko suvenir. Sumber: setkab.go.id, galontrip.wordpress.com",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d17531744"
  },
  {
    "id": "pusat-promosi-ikan-hias-sumenep",
    "name": "Pusat Promosi Ikan Hias Sumenep",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jln. Sumenep, Jakarta, 10310",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.19974,
    "lng": 106.82537,
    "coordSource": "TripAdvisor",
    "rating": 3.6,
    "reviews": 5,
    "status": "Aktif",
    "note": "Sentra ikan hias di Jl Sumenep No.4, Kec. Menteng; bukan toko suvenir. Sumber: beritajakarta.id, tribunnews.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d6579516"
  },
  {
    "id": "chandraprima-money-changer",
    "name": "Chandraprima Money Changer",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Wahid Hasyim street number 185. Tanah abang Afindo cargo room number 222, Jakarta, 10250",
    "city": "Jakarta Pusat",
    "district": "Tanah Abang",
    "lat": -6.187398,
    "lng": 106.81649,
    "coordSource": "TripAdvisor",
    "phone": "+62 851-0368-7688",
    "rating": 4,
    "reviews": 4,
    "status": "Aktif",
    "note": "Penukaran uang asing (money changer) di Gedung Afindo, Jl. K.H. Wahid Hasyim, kel. Kebon Kacang; punya situs resmi chandraprima.com dengan jam operasional; koordinat sesuai area Tanah Abang",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d25408428"
  },
  {
    "id": "dayana-tobacco",
    "name": "Dayana TOBACCO",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Iskandarsyah Raya no. 65 Hotel Grandhika Iskandarsyah - M Level, Jakarta, 12160",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.244306,
    "lng": 106.80375,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 73910443",
    "rating": 5,
    "reviews": 4,
    "status": "Aktif",
    "note": "Toko cerutu/tembakau premium est.1997 di Hotel GranDhika Iskandarsyah, Melawai; website dayanatobacco.com masih ada; kecamatan Kebayoran Baru dari kodepos 12160/lokasi hotel",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d12017934"
  },
  {
    "id": "hype-festival",
    "name": "Hype Festival",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Tidak",
    "address": "Jln. Pantai Indah, Jakarta, 14420",
    "city": "Jakarta Utara",
    "district": "Penjaringan",
    "lat": -6.12155,
    "lng": 106.83383,
    "coordSource": "TripAdvisor",
    "phone": "+62 852-1888-8810",
    "rating": 3.8,
    "reviews": 4,
    "status": "Aktif",
    "note": "Bazaar/pop-up market bulanan (weekend) di kawasan Pantai Indah Kapuk berisi F&B dan fashion, bukan toko suvenir/kerajinan tetap. Sumber: Tripadvisor, kompas.com",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d8728059"
  },
  {
    "id": "arafah-collection",
    "name": "Arafah Collection",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Thamrin City Block C35 Nomor 18-21  Jln. Jakarta, Jakarta, 10730",
    "city": "Jakarta Pusat",
    "district": "Tanah Abang",
    "lat": -6.1913,
    "lng": 106.8172,
    "coordSource": "Koreksi riset",
    "phone": "+62 21 31990936",
    "rating": 4,
    "reviews": 1,
    "status": "Aktif",
    "note": "Toko busana muslim (gamis/abaya/kaftan gaya Timur Tengah) di Thamrin City Blok C35, Waduk Melati, Kec. Tanah Abang — bukan toko suvenir. Koordinat input meleset jauh (area Kembangan/Jakarta Barat), dikoreksi ke perkiraan lokasi Thamrin City (perkiraan, belum diverifikasi presisi). Sumber: trip.com, thamrincity.co.id.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d5966692"
  },
  {
    "id": "biasa-jakarta",
    "name": "BIASA Jakarta",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Kemang Raya No.20, Jakarta, 12730",
    "city": "Jakarta Selatan",
    "district": "Mampang Prapatan",
    "lat": -6.259716,
    "lng": 106.815125,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 7182322",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Butik fashion resort-wear asal Bali (bukan toko oleh-oleh/suvenir); sumber biasagroup.com.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d19453565"
  },
  {
    "id": "bike-station",
    "name": "Bike Station",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jalan Asia Afrika No 32 Stc LG 34, Jakarta, 10270",
    "city": "Jakarta Pusat",
    "district": "Tanah Abang",
    "lat": -6.22728,
    "lng": 106.79836,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 57931891",
    "rating": 4,
    "reviews": 1,
    "status": "Tidak diketahui",
    "note": "\"Toko sepeda di STC Senayan; berita 2025 menyebut mayoritas toko sepeda \"\"high-end\"\" di STC sudah tutup, status spesifik Bike Station tidak terkonfirmasi. Sumber Kompas/Detik Ags 2025.\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d18841189"
  },
  {
    "id": "florist-sedapmalam-mas-agung",
    "name": "Florist Sedapmalam Mas Agung",
    "category": "Toko Barang Antik",
    "relevance": "Tidak",
    "address": "Jl. Sulaiman No.56 Blok B Lapak Sedapmalam, Rw.3, Sukabumi Utara, Kec. Kb. Jeruk, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11540, Jakarta, 11540",
    "city": "Jakarta Barat",
    "district": "Kebon Jeruk",
    "lat": -6.206067,
    "lng": 106.77821,
    "coordSource": "TripAdvisor",
    "phone": "+62 852-1046-4090",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Penjual bunga sedap malam (florist), bukan suvenir; alamat & nama sesuai listing TripAdvisor & referensi toko bunga Kebon Jeruk",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d32814483"
  },
  {
    "id": "immanuel-bookstore",
    "name": "Immanuel Bookstore",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jalan Proklamasi 76, Jakarta, 10320",
    "city": "Jakarta Pusat",
    "district": "Menteng",
    "lat": -6.20287,
    "lng": 106.84893,
    "coordSource": "TripAdvisor",
    "phone": "+62 21 3900790",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Toko buku rohani Kristen, bukan suvenir wisata; sumber immanuelbookstore.co.id (masih beroperasi, cabang Proklamasi sejak 1992).",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d13817991"
  },
  {
    "id": "nonna-store-pik",
    "name": "Nonna Store PIK",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Outer Ring Road Pantai Indah Kapuk, Food Plaza building Block A No 35-37, Jakarta, 14470",
    "city": "Jakarta Utara",
    "district": "Penjaringan",
    "lat": -6.103562,
    "lng": 106.74109,
    "coordSource": "TripAdvisor",
    "phone": "+62 857-1549-0196",
    "rating": 5,
    "reviews": 1,
    "status": "Tidak diketahui",
    "note": "Toko kosmetik/aksesoris (Nonna Cosmetic, produk Taiwan), bukan suvenir khas; kecamatan Penjaringan dari lokasi PIK/kodepos 14470, koordinat sesuai area PIK; tidak ada info status terkini yang bisa diverifikasi",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d9727715"
  },
  {
    "id": "pecenongan-night-market",
    "name": "Pecenongan Night Market",
    "category": "Pasar Loak & Pasar Jalanan",
    "relevance": "Tidak",
    "address": "Jl. Pecenongan, Jakarta, 10120",
    "city": "Jakarta Pusat",
    "district": "Gambir",
    "lat": -6.16222,
    "lng": 106.82695,
    "coordSource": "TripAdvisor",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Kawasan wisata kuliner malam (jajanan/makanan), bukan toko suvenir. Sumber: travel.detik.com, Tripadvisor",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d19090223"
  },
  {
    "id": "pojahome-indonesia",
    "name": "Pojahome Indonesia",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. H. Daud I 35c, Rt.2/rw.3, Sukabumi Sel., Kec. Kb. Jeruk Kota Jakarta Barat, Daerah Khusus Ibukota , Jakarta, 11560",
    "city": "Jakarta Barat",
    "district": "Kebon Jeruk",
    "lat": -6.20643,
    "lng": 106.7747,
    "coordSource": "TripAdvisor",
    "phone": "+62 851-3312-5638",
    "rating": 5,
    "reviews": 1,
    "status": "Aktif",
    "note": "Jasa desain interior & custom furniture (bukan toko suvenir), workshop di Kebon Jeruk sesuai alamat (sumber: pojahome.co.id). Koordinat plausibel untuk area Kebon Jeruk/Sukabumi Selatan.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d32764882"
  },
  {
    "id": "big-boy-looks-good",
    "name": "Big Boy Looks Good",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl Prof Dr. Satrio Kav 18, Jakarta, 12940",
    "city": "Jakarta Selatan",
    "district": "Setiabudi",
    "lat": -6.216613,
    "lng": 106.81918,
    "coordSource": "TripAdvisor",
    "phone": "+62 857-7993-3198",
    "status": "Aktif",
    "note": "Merek/toko pakaian pria plus-size Indonesia (didirikan 2009), bukan toko suvenir; Jl. Prof. Dr. Satrio kel. Karet Kuningan masuk kec. Setiabudi; koordinat sesuai area Kuningan",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d26585518"
  },
  {
    "id": "home-decor-indonesia",
    "name": "Home Decor Indonesia",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jalan Rs Fatmawati No. 5a,c,d 1, Rt.1/rw.6, Gandaria Utara, Kec. Kebayoran. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12140, Jakarta, 12140",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.259873,
    "lng": 106.79643,
    "coordSource": "TripAdvisor",
    "phone": "+62 818-0604-0506",
    "status": "Aktif",
    "note": "Toko interior/furnitur (gorden, sofa, wallpaper) sejak 1992, bukan suvenir; alamat & jam buka dikonfirmasi di homedecorindonesia.com dan mylifegb.com",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d33404716"
  },
  {
    "id": "jakartanotebook-benhil",
    "name": "Jakartanotebook Benhil",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Bendungan Hilir Raya Blok G1 No. 10 Jakarta Pusat Seberang Geprek Bensu Benhil, Jakarta, 10210",
    "city": "Jakarta Pusat",
    "district": "Tanah Abang",
    "lat": -6.211045,
    "lng": 106.812355,
    "coordSource": "TripAdvisor",
    "phone": "+62 896-1352-2200",
    "status": "Aktif",
    "note": "Cabang toko elektronik/notebook (bukan suvenir), Bendungan Hilir masuk kec. Tanah Abang; buka sejak 2022, aktif di Instagram/TikTok; koordinat sesuai area Benhil",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d26270726"
  },
  {
    "id": "kuponhosting",
    "name": "Kuponhosting",
    "category": "Toko Barang Antik",
    "relevance": "Tidak",
    "address": "Jakarta Pusat, Jakarta",
    "city": "Jakarta Pusat",
    "district": "?",
    "lat": -6.180511,
    "lng": 106.828384,
    "coordSource": "TripAdvisor",
    "phone": "+62 881-0235-15545",
    "status": "Tidak diketahui",
    "note": "\"Nama & kategori (Antique Stores) tidak konsisten dgn \"\"Kuponhosting\"\" yg berasosiasi dgn situs kupon hosting (kuponhosting.com, domain dijual di Flippa); diduga listing spam/tidak valid, tidak dapat diverifikasi sbg toko nyata. Kecamatan tidak dapat ditentukan (alamat hanya \"\"Jakarta Pusat\"\")\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d23760495"
  },
  {
    "id": "nagarey",
    "name": "Nagarey",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Jalur 20 No.9, RT.4/RW.10 Meruya Utara, Jakarta, 11650",
    "city": "Jakarta Barat",
    "district": "Kembangan",
    "lat": -6.197569,
    "lng": 106.72874,
    "coordSource": "TripAdvisor",
    "phone": "+62 822-1076-9566",
    "status": "Aktif",
    "note": "Toko furnitur & dekorasi rumah custom (rustic), bukan toko suvenir untuk wisatawan, di Meruya Utara, Kembangan (sumber: nagarey.com, topgoogle.com). Koordinat plausibel untuk area Meruya Utara.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d32986329"
  },
  {
    "id": "number-76-jakarta",
    "name": "Number 76 Jakarta",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "18 Parc Place Tower D, Ground Floor, Suite 2, Scbd, Jl. Jendral Sudirman Kav. 52-53, Rt.5/rw.3, Senayan, Kebayoran Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12190, Indonesia, Jakarta, 12190",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.2251,
    "lng": 106.809,
    "coordSource": "Koreksi riset",
    "phone": "+62 21 51401776",
    "status": "Aktif",
    "note": "Salon rambut Jepang (Number76), bukan suvenir; alamat Parc Place SCBD, Senayan masuk kec. Kebayoran Baru; grand reopening Okt 2025 jadi masih aktif. Koordinat sumber (-6.21462,106.84513) bergeser ~4km ke timur dari lokasi SCBD/Senayan sebenarnya (sekitar -6.225,106.809); koreksi adalah perkiraan area SCBD, bukan titik persis gedung",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d27720986"
  },
  {
    "id": "pelangi-bunga",
    "name": "Pelangi Bunga",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Budi Raya No.4C Kemanggisan, Jakarta, 11480",
    "city": "Jakarta Barat",
    "district": "Palmerah",
    "lat": -6.19302,
    "lng": 106.78226,
    "coordSource": "TripAdvisor",
    "phone": "+62 813-1759-8383",
    "status": "Aktif",
    "note": "Toko bunga (florist), bukan suvenir; sumber Facebook pelangibungaid.",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d20254097"
  },
  {
    "id": "samsung-mhi-itc-fatmawati",
    "name": "Samsung Mhi Itc Fatmawati",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Itc Fatmawati Lt. 1 No 49-51, RT.3/RW.5, Cipete Utara, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota , Jakarta, 12150",
    "city": "Jakarta Selatan",
    "district": "Kebayoran Baru",
    "lat": -6.2825,
    "lng": 106.7995,
    "coordSource": "Koreksi riset",
    "phone": "+62 811-8818-124",
    "status": "Aktif",
    "note": "Samsung Service Center (pusat servis HP/elektronik), bukan toko suvenir, di ITC Fatmawati Lt.1, Cipete Utara, Kebayoran Baru (sumber: servicesamsung.id, idalamat.com). Koordinat asli (lng 106.621) meleset jauh ke barat (~20km) dari ITC Fatmawati; koreksi ke perkiraan lokasi ITC Fatmawati (belum diverifikasi presisi GPS).",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d33225533"
  },
  {
    "id": "shishaholic",
    "name": "Shishaholic",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Raya Condet No.5, RT.1/RW.16, Cililitan, KEC, Jakarta, 13640",
    "city": "Jakarta Timur",
    "district": "Kramat Jati",
    "lat": -6.26571,
    "lng": 106.86111,
    "coordSource": "TripAdvisor",
    "phone": "+62 812-9587-0909",
    "status": "Tidak diketahui",
    "note": "\"Lounge/toko shisha (bukan suvenir); alamat Jl. Raya Condet, kel. Cililitan masuk kec. Kramat Jati (kodepos 13640), koordinat sesuai area tsb; sebuah blog lain menyebut \"\"Shishaholic\"\" berlokasi di selatan kota — kemungkinan beda tempat/tidak konsisten, status operasional tidak bisa dipastikan dari sumber yang ada\"",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d27508964"
  },
  {
    "id": "toko-board-game",
    "name": "Toko Board Game",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Kerajinan I no. 35, Jakarta, 11130",
    "city": "Jakarta Barat",
    "district": "Tamansari",
    "lat": -6.152825,
    "lng": 106.81452,
    "coordSource": "TripAdvisor",
    "phone": "+62 878-8732-8782",
    "status": "Aktif",
    "note": "Toko board game (TBG), bukan suvenir; alamat Jl. Kerajinan I No.35 Keagungan, Kec. Tamansari (bkppkutim.com); masih berjualan aktif di Tokopedia (tokopedia.com/tokoboardgame)",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d12918278"
  },
  {
    "id": "toko-buku-pak-pay",
    "name": "Toko Buku Pak Pay",
    "category": "Toko Suvenir & Spesialisasi",
    "relevance": "Tidak",
    "address": "Jl. Kramat Raya No.2 Rt.2/rw.7, Jakarta, 10420",
    "city": "Jakarta Pusat",
    "district": "Senen",
    "coordSource": "Koordinat TripAdvisor salah, belum ada koreksi",
    "phone": "+62 878-8385-8604",
    "status": "Tidak diketahui",
    "note": "Toko buku (bukan suvenir); alamat Jl. Kramat Raya No.2 masuk kel. Kwitang, kec. Senen (dari kodepos 10420); tidak ditemukan hasil pencarian spesifik untuk memverifikasi keberadaan usaha ini. Koordinat sumber (-6.2959,106.81137) meleset ~13km dari lokasi Kramat Raya yang sebenarnya (sekitar -6.182,106.843); koreksi persis tidak dapat dipastikan sehingga dikosongkan",
    "url": "https://www.tripadvisor.com/Attraction_Review-g294229-d26806658"
  }
];

/** Hanya toko yang benar-benar menjual suvenir/oleh-oleh (Ya + Sebagian). */
export function souvenirShops(): SouvenirShop[] {
  return SOUVENIR_SHOPS.filter(
    (s) => s.relevance === "Ya" || s.relevance === "Sebagian"
  );
}

export function souvenirMapsUrl(s: SouvenirShop): string {
  if (s.lat != null && s.lng != null) {
    return `https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lng}`;
  }
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    `${s.name} ${s.address ?? "Jakarta"}`
  )}`;
}

/** Embed peta untuk slot "gambar produk" di kartu (pola sama lib/restaurants). */
export function souvenirEmbedUrl(s: SouvenirShop): string {
  if (s.lat != null && s.lng != null) {
    return `https://www.google.com/maps?q=${s.lat},${s.lng}&hl=id&z=17&output=embed`;
  }
  const q = [s.name, s.address, "Jakarta"].filter(Boolean).join(", ");
  return `https://www.google.com/maps?q=${encodeURIComponent(q)}&hl=id&z=16&output=embed`;
}

/** Daftar produk unik (untuk filter), urut alfabetis. "?" = belum terverifikasi,
 *  dibuang dari opsi filter karena bukan kategori produk yang bermakna. */
export function souvenirProducts(): string[] {
  const set = new Set(
    SOUVENIR_SHOPS.map((s) => s.product).filter(
      (p): p is string => !!p && p !== "?"
    )
  );
  return [...set].sort((a, b) => a.localeCompare(b, "id"));
}
