/**
 * GCI — Pertunjukan Musik & Acara Budaya Besar Jakarta 2025
 * =========================================================
 * Dataset untuk Global City Index (GCI), indikator: "Jumlah pertunjukan musik
 * internasional dan acara budaya besar lainnya di Jakarta dalam setahun".
 * Cakupan: DKI Jakarta, tahun 2025.
 *
 * Format kolom seragam:
 *  - date     : satu hari "YYYY-MM-DD", atau rentang "YYYY-MM-DD s/d YYYY-MM-DD"
 *               (beberapa hanya diketahui bulannya, mis. "Mei 2025").
 *  - visitors : ANGKA saja ("" bila tak ada sumber). Konteksnya di `note`.
 *  - note     : keterangan tambahan (kapasitas/perkiraan/target/total/2 hari/dst).
 *
 * "Jumlah Pengunjung" tidak pernah dikarang. Daftar = dasar, perlu spot-check tim.
 */

export type EventCategory =
  | "Konser Musik"
  | "Festival Musik"
  | "Seni Tari"
  | "Teater / Musikal"
  | "Orkestra / Klasik"
  | "Seni Tradisional"
  | "Seni Rupa"
  | "Film"
  | "Budaya"
  | "Budaya Pop"
  | "Fashion"
  | "Fan Meeting";

export const EVENT_CATEGORIES: EventCategory[] = [
  "Konser Musik",
  "Festival Musik",
  "Seni Tari",
  "Teater / Musikal",
  "Orkestra / Klasik",
  "Seni Tradisional",
  "Seni Rupa",
  "Film",
  "Budaya",
  "Budaya Pop",
  "Fashion",
  "Fan Meeting",
];

export type GciEvent = {
  id: string;
  /** Nama Penyelenggara / Organizer */
  organizer: string;
  /** Nama Pertunjukan / Name of Performance */
  name: string;
  /** Tanggal Pertunjukan — satu hari atau rentang (A s/d B) */
  date: string;
  /** Tempat Pertunjukan / Place of Performance — selalu DKI Jakarta */
  venue: string;
  /** Jenis Pertunjukan / Type of Performance */
  type: string;
  /** Jumlah Pengunjung — ANGKA saja ("" bila tak ada) */
  visitors: string;
  /** Keterangan — konteks angka/tanggal (kapasitas, perkiraan, total, dst) */
  note: string;
  /** Kategori kasar untuk filter web (bukan kolom deliverable) */
  category: EventCategory;
  /** Sumber — URL bukti verifikasi */
  source: string;
};

const SEED: GciEvent[] = [
  // ── Konser Musik ──
  { id: "k01", organizer: "Front Row Asia", name: "Boney M. 50th Anniversary Tour Live in Jakarta", date: "2025-01-10", venue: "Grand Ballroom Pullman Jakarta Central Park", type: "Konser Musik Internasional (Disco/Pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.tempo.co/teroka/boney-m-akan-gelar-konser-50-tahun-berkarya-di-jakarta-10-januari-2025-1167900" },
  { id: "k02", organizer: "Live Nation, TEM Presents, PK Entertainment", name: "Cigarettes After Sex - X's World Tour 2025 Live in Jakarta", date: "2025-01-17", venue: "Beach City International Stadium (BCIS) Ancol", type: "Konser Musik Internasional (Dream Pop/Indie)", visitors: "", note: "", category: "Konser Musik", source: "https://www.pk-ent.com/concert/cigaretter-after-sex" },
  { id: "k03", organizer: "", name: "INFINITE 15th Anniversary Concert: Limited Edition in Jakarta", date: "2025-01-18", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (K-pop)", visitors: "~5.000", note: "kapasitas", category: "Konser Musik", source: "https://www.socialexpat.net/list-of-k-pop-concerts-and-fan-meetings-in-indonesia-for-2025/" },
  { id: "k04", organizer: "", name: "TAEYANG 2025 TOUR [THE LIGHT YEAR] in Jakarta", date: "2025-01-25", venue: "Beach City International Stadium (BCIS) Ancol", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://urbanvibes.id/index.php/2024/12/06/taeyang-konser-di-jakarta-bertemakan-the-light-year-pada-25-januari-2025/" },
  { id: "k05", organizer: "PK Entertainment", name: "Maroon 5 Asia 2025 - Jakarta", date: "2025-02-01", venue: "Jakarta International Stadium (JIS)", type: "Konser Musik Internasional (Pop/Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://www.tempo.co/teroka/maroon-5-konser-di-jakarta-1-februari-2025-ketiga-kali-berkunjung-ke-indonesia-1201096" },
  { id: "k06", organizer: "", name: "KYUHYUN COLORS Asia Tour in Jakarta", date: "2025-02-08", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.suara.com/entertainment/2025/12/29/182500/tak-ada-bulan-sepi-ini-deretan-konser-k-pop-yang-siap-guncang-jakarta-sepanjang-2025" },
  { id: "k07", organizer: "", name: "SEVENTEEN [RIGHT HERE] World Tour in Jakarta", date: "2025-02-08", venue: "Jakarta International Stadium (JIS)", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.kompas.com/hype/read/2025/02/08/122100566/rundown-konser-seventeen-right-here-in-jakarta-di-jis" },
  { id: "k08", organizer: "Ravel Entertainment", name: "The Corrs - From Jakarta with Love", date: "2025-02-08", venue: "Beach City International Stadium (BCIS) Ancol", type: "Konser Musik Internasional (Pop/Celtic Rock)", visitors: "10.000+", note: "", category: "Konser Musik", source: "https://kumparan.com/seputar-jakarta/rundown-konser-the-corrs-di-jakarta-2025-di-beach-city-international-stadium-24SDbhmySXn" },
  { id: "k09", organizer: "CK Star Entertainment", name: "wave to earth 0.03 World Tour in Jakarta", date: "2025-02-13", venue: "Istora Senayan", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.kompas.com/hype/read/2025/02/13/185717066/wave-to-earth-gelar-konser-malam-ini-di-istora-senayan" },
  { id: "k10", organizer: "Aloka", name: "NIKI: Buzz World Tour Jakarta (Hari 1)", date: "2025-02-14", venue: "Beach City International Stadium (BCIS) Ancol", type: "Konser Musik Internasional (Pop)", visitors: "~10.000", note: "kapasitas", category: "Konser Musik", source: "https://www.setlist.fm/setlist/niki/2025/beach-city-international-stadium-kota-administrasi-jakarta-utara-indonesia-7b5ee6dc.html" },
  { id: "k11", organizer: "", name: "NCT 127 4th Tour 'NEO CITY – THE MOMENTUM' in Jakarta", date: "2025-02-15", venue: "Indonesia Arena", type: "Konser Musik Internasional (K-pop)", visitors: "~16.500", note: "kapasitas", category: "Konser Musik", source: "https://www.socialexpat.net/list-of-k-pop-concerts-and-fan-meetings-in-indonesia-for-2025/" },
  { id: "k12", organizer: "Ravel Entertainment", name: "Green Day Live in Jakarta 2025", date: "2025-02-15", venue: "Pantai Karnaval Ancol", type: "Konser Musik Internasional (Punk Rock)", visitors: "40.000", note: "target promotor", category: "Konser Musik", source: "https://www.jawapos.com/nasional/014981335/promotor-targetkan-40-ribu-penonton-pada-konser-green-day-di-pantai-carnaval-ancol" },
  { id: "k13", organizer: "Aloka", name: "NIKI: Buzz World Tour Jakarta (Hari 2)", date: "2025-02-16", venue: "Beach City International Stadium (BCIS) Ancol", type: "Konser Musik Internasional (Pop)", visitors: "~10.000", note: "kapasitas", category: "Konser Musik", source: "https://www.setlist.fm/setlist/niki/2025/beach-city-international-stadium-jakarta-indonesia-735ee6d1.html" },
  { id: "k14", organizer: "Live Nation, TEM Presents, PK Entertainment", name: "Linkin Park - From Zero World Tour 2025 Live in Jakarta", date: "2025-02-16", venue: "Stadion Madya Gelora Bung Karno (GBK)", type: "Konser Musik Internasional (Rock/Nu-Metal)", visitors: "", note: "", category: "Konser Musik", source: "https://www.tempo.co/teroka/linkin-park-akan-konser-di-stadion-madya-gbk-16-februari-2025-tiket-dijual-pekan-depan-1173455" },
  { id: "k15", organizer: "Alesana", name: "Alesana - The Southeast Asia Tour 2025 Live in Jakarta", date: "2025-02-21", venue: "Ballroom Kuningan City, Jakarta Selatan", type: "Konser Musik Internasional (Post-Hardcore/Metalcore)", visitors: "", note: "", category: "Konser Musik", source: "https://www.setlist.fm/setlist/alesana/2025/kuningan-city-ballroom-kota-administrasi-jakarta-selatan-indonesia-2b5dac62.html" },
  { id: "k16", organizer: "", name: "YOASOBI ASIA TOUR 2024-2025 in Jakarta", date: "2025-02-26", venue: "Istora Senayan", type: "Konser Musik Internasional (J-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.cnnindonesia.com/hiburan/20240827122803-227-1137983/yoasobi-akan-gelar-konser-2-hari-di-jakarta-pada-februari-2025" },
  { id: "k17", organizer: "", name: "2025 JAY B CONCERT [TAPE:RE LOAD] in Asia - Jakarta", date: "2025-04-05", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.socialexpat.net/list-of-k-pop-concerts-and-fan-meetings-in-indonesia-for-2025/" },
  { id: "k18", organizer: "", name: "TAEYEON CONCERT - The TENSE in Jakarta", date: "2025-04-12", venue: "Indonesia Arena", type: "Konser Musik Internasional (K-pop)", visitors: "~16.500", note: "kapasitas", category: "Konser Musik", source: "https://www.socialexpat.net/list-of-k-pop-concerts-and-fan-meetings-in-indonesia-for-2025/" },
  { id: "k19", organizer: "", name: "BOYNEXTDOOR [KNOCK ON] Vol.1 Tour in Jakarta", date: "2025-04-12", venue: "Istora Senayan", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.kompas.com/hype/read/2025/01/06/115818566/daftar-jadwal-konser-kpop-di-indonesia-sepanjang-2025" },
  { id: "k20", organizer: "Akselerasi Entertainment", name: "M2M - The Better Endings Tour 2025 Live in Jakarta", date: "2025-04-26", venue: "Ecovention Hall, Ancol, Jakarta Utara", type: "Konser Musik Internasional (Pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.setlist.fm/setlist/m2m/2025/hall-ecovention-kota-administrasi-jakarta-utara-indonesia-6b510e02.html" },
  { id: "k21", organizer: "Color Asia Live", name: "Boyce Avenue Live in Jakarta 2025", date: "2025-04-27", venue: "Pullman Jakarta Central Park, Jakarta Barat", type: "Konser Musik Internasional (Acoustic/Pop Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://www.bandsintown.com/e/106643654-boyce-avenue-at-pullman-jakarta-central-park" },
  { id: "k22", organizer: "", name: "DAY6 3rd World Tour 'The DECADE' in Jakarta", date: "2025-05-03", venue: "Jakarta International Stadium (JIS)", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.kompas.com/hype/read/2025/01/06/115818566/daftar-jadwal-konser-kpop-di-indonesia-sepanjang-2025" },
  { id: "k23", organizer: "", name: "2025 j-hope Tour 'HOPE ON THE STAGE' in Jakarta", date: "2025-05-03", venue: "Indonesia Arena", type: "Konser Musik Internasional (K-pop)", visitors: "~16.500", note: "kapasitas", category: "Konser Musik", source: "https://www.setlist.fm/setlist/jhope/2025/indonesia-arena-jakarta-indonesia-b5d9566.html" },
  { id: "k24", organizer: "Rajawali Indonesia Communication", name: "Boyz II Men Live in Jakarta 2025", date: "2025-05-21", venue: "Istora Senayan", type: "Konser Musik Internasional (R&B)", visitors: "~7.000", note: "kapasitas", category: "Konser Musik", source: "https://event.tempo.co/read/2009388/boyz-ii-men-gandeng-kahitna-di-jakarta" },
  { id: "k25", organizer: "", name: "NCT WISH Asia Tour 'Into the WISH' in Jakarta", date: "2025-05-31", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (K-pop)", visitors: "~5.000", note: "kapasitas", category: "Konser Musik", source: "https://www.socialexpat.net/list-of-k-pop-concerts-and-fan-meetings-in-indonesia-for-2025/" },
  { id: "k26", organizer: "Color Asia Live & Otello Asia", name: "Heart & Soul Live in Jakarta 2025 (All-4-One & Brian McKnight)", date: "2025-06-11", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (R&B)", visitors: "~5.000", note: "kapasitas", category: "Konser Musik", source: "https://urbanvibes.id/2025/06/12/heart-soul-jakarta-2025-all-4-one-brian-mcknight-raisa-pukau-ribuan-penonton/" },
  { id: "k27", organizer: "", name: "2025 STAYC TOUR [STAY TUNED] in Jakarta", date: "2025-06-28", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.goersapp.com/blog/konser-kpop-jakarta-2025/" },
  { id: "k28", organizer: "", name: "Ailee: Ascend, Live in Jakarta", date: "2025-07-05", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.liputan6.com/showbiz/read/6052051/bocoran-konser-ailee-ascend-live-in-jakarta-bakal-nyanyi-3-lagu-yang-belum-pernah-dibawakan-secara-live" },
  { id: "k29", organizer: "AEG Presents / TME Live / CK Star Entertainment", name: "G-DRAGON 2025 WORLD TOUR [Übermensch] in Jakarta", date: "2025-07-25", venue: "Indonesia Arena", type: "Konser Musik Internasional (K-pop)", visitors: "22.000", note: "2 hari", category: "Konser Musik", source: "https://www.cnnindonesia.com/hiburan/20250319111856-227-1210576/g-dragon-akan-konser-ubermensch-di-indonesia-arena-26-juli-2025" },
  { id: "k30", organizer: "Bozz Event (Soul 5.0)", name: "Soul 5.0 with HONNE - The Ouch Tour", date: "2025-08-02", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (Pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.songkick.com/concerts/42650421-honne-at-kasablanka" },
  { id: "k31", organizer: "CK Star Entertainment", name: "D.O. (EXO) ASIA TOUR 'DO it!' in Jakarta", date: "2025-08-09", venue: "Indonesia Arena", type: "Konser Musik Internasional (K-pop)", visitors: "~16.500", note: "kapasitas", category: "Konser Musik", source: "https://www.kompas.com/hype/read/2025/08/09/192339566/do-exo-buka-konsernya-di-indonesia-arena-jakarta-annyeong-haseyo" },
  { id: "k32", organizer: "", name: "2025 B.I TOUR IN ASIA: The Last Parade Tour in Jakarta", date: "2025-09-13", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://todaystage.com/articles/events/b-i-lights-up-jakarta-with-the-last-parade-tour-concert-at-kasablanka-hall/" },
  { id: "k33", organizer: "Ravel Entertainment", name: "Muse: Live in Jakarta 2025", date: "2025-09-19", venue: "Pantai Carnaval Ancol", type: "Konser Musik Internasional (Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://www.muse.mu/tour-date/carnaval-ancol-jakarta-indonesia" },
  { id: "k34", organizer: "Rajawali Indonesia", name: "Air Supply - Klakustik Live in Jakarta 2025 (Stage of Love)", date: "2025-09-26", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (Soft Rock/Pop)", visitors: "~5.200", note: "kapasitas", category: "Konser Musik", source: "https://www.kompas.id/artikel/en-udara-penuh-cinta-di-konser-air-supply" },
  { id: "k35", organizer: "", name: "NCT DREAM THE DREAM SHOW 4: Dream The Future in Jakarta", date: "2025-09-27", venue: "Jakarta International Stadium (JIS)", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://mediaaku.com/konser-nct-dream-the-dream-show-4-siap-guncang-jakarta-27-28-september-2025/" },
  { id: "k36", organizer: "Kiryu Entertainment", name: "Jeff Satur 'Red Giant' Concert in Jakarta 2025", date: "2025-09-27", venue: "Jakarta Concert Hall, Kebon Sirih, Jakarta Pusat", type: "Konser Musik Internasional (T-pop/Thailand)", visitors: "", note: "", category: "Konser Musik", source: "https://www.netralnews.com/jeff-satur-siap-guncang-jakarta-dengan-red-giant-concert-september-2025/TDY5QWNRVW9SU0ROVEZ6cFpkSTE3dz09" },
  { id: "k37", organizer: "Ravel Entertainment", name: "Foo Fighters: Live in Jakarta 2025", date: "2025-10-02", venue: "Pantai Carnaval Ancol", type: "Konser Musik Internasional (Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://foojkt.com/" },
  { id: "k38", organizer: "CK Star Entertainment", name: "The Smashing Pumpkins: Rock Invasion 2025 Tour in Jakarta", date: "2025-10-03", venue: "JIExpo Kemayoran (Hall A2-A3)", type: "Konser Musik Internasional (Alternative Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://thesmashingpumpkinsjkt.com/" },
  { id: "k39", organizer: "Otello Asia", name: "With Love From BRI Presents Babyface - Live in Jakarta 2025", date: "2025-10-25", venue: "Beach City International Stadium (BCIS) Ancol", type: "Konser Musik Internasional (Pop/R&B)", visitors: "", note: "", category: "Konser Musik", source: "https://mediaaku.com/konser-babyface-live-in-jakarta-siap-menyemarakan-beach-city-international-stadium-ancol-25-oktober-2025/" },
  { id: "k40", organizer: "iMe Indonesia", name: "BLACKPINK WORLD TOUR [DEADLINE] in Jakarta", date: "2025-11-01", venue: "Gelora Bung Karno (GBK)", type: "Konser Musik Internasional (K-pop)", visitors: "~110.000-120.000", note: "2 hari, estimasi", category: "Konser Musik", source: "https://www.thejakartapost.com/culture/2025/11/03/blackpink-turns-gbk-into-pink-dome-for-two-day-deadline-gig" },
  { id: "k41", organizer: "Sound Rhythm & Mataloka", name: "HYDE [INSIDE] LIVE 2025 WORLD TOUR in Jakarta", date: "2025-11-01", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (J-Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://koranindopos.com/jakarta-bersiap-menyambut-hyde-tennis-indoor-senayan-sabtu-1-november-2025/" },
  { id: "k42", organizer: "MEG Entertainment", name: "The Paper Kites Live in Jakarta 2025", date: "2025-11-26", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (Indie/Folk Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://artatix.co.id/event/the_paper_kites_jakarta" },
  { id: "k43", organizer: "MMEG Entertainment", name: "BLUE Live in Jakarta 2025 (25th Anniversary Tour)", date: "2025-11-27", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (Pop)", visitors: "", note: "", category: "Konser Musik", source: "https://artatix.co.id/event/blue-live-jakarta" },
  { id: "k44", organizer: "MEG Entertainment", name: "Secondhand Serenade - Awake 20 Year Anniversary", date: "2025-12-06", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (Pop/Rock)", visitors: "", note: "", category: "Konser Musik", source: "https://artatix.co.id/event/secondhand_serenade_awake_20_year_anniversary_jakarta" },

  { id: "k45", organizer: "PK Entertainment / TEM Presents / Live Nation", name: "keshi 'REQUIEM TOUR' in Jakarta 2025", date: "2025-02-23", venue: "Istora Senayan", type: "Konser Musik Internasional (Indie/Alternatif)", visitors: "", note: "Opening act BOYLIFE", category: "Konser Musik", source: "https://www.pk-ent.com/concert/keshi-requiem-world-tour" },
  { id: "k46", organizer: "FriedRice Entertainment", name: "2025 BTOB FAN-CON '3,2,1 GO! MELympic' in Jakarta", date: "2025-06-07", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (Fan-Con K-pop)", visitors: "", note: "", category: "Konser Musik", source: "https://hypeabis.id/read/49285/6-konser-k-pop-fan-meeting-juni-2025-ada-babymonster-hingga-lee-do-hyun" },
  { id: "k47", organizer: "", name: "2025 KAI (EXO) SOLO CONCERT TOUR <KAION> in Jakarta", date: "2025-06-14", venue: "Tennis Indoor Senayan", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "Konser solo perdana KAI di Jakarta", category: "Konser Musik", source: "https://hypeabis.id/read/49285/6-konser-k-pop-fan-meeting-juni-2025-ada-babymonster-hingga-lee-do-hyun" },
  { id: "k48", organizer: "Dyandra Global Edutainment", name: "2025 Jay Park World Tour [Serenades & Body Rolls] in Jakarta", date: "2025-07-12", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop/Hip-Hop)", visitors: "", note: "Tamu Ziva Magnolya & Ramengvrl", category: "Konser Musik", source: "https://amp.kompas.com/hype/read/2025/07/12/193620166/jay-park-buka-konser-serenades-body-rolls-jakarta-dengan-ohx3" },
  { id: "k49", organizer: "FriedRice Entertainment", name: "2025 EVNNE Concert 'SET N GO' in Jakarta", date: "2025-07-26", venue: "The Kasablanka Hall", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "Penutup tur Asia", category: "Konser Musik", source: "https://www.ntvnews.id/hiburan/0157179/pecah-evnne-sukses-gelar-konser-set-n-go-2025-di-jakarta-sebagai-penutup-tur-asia" },
  { id: "k50", organizer: "54 Entertainment", name: "La La Land in Concert", date: "2025-07-26", venue: "JIExpo Kemayoran, Jakarta", type: "Konser Musik Internasional (Film-Concert/Orkestra)", visitors: "", note: "Iringan orkestra langsung (Twilite Orchestra); 2 pertunjukan", category: "Konser Musik", source: "https://www.suara.com/entertainment/2025/08/17/093620/la-la-land-in-concert-sukses-pukau-ribuan-penonton-di-jiexpo-kemayoran-jakarta" },
  { id: "k51", organizer: "Color Asia Live", name: "2025 PLAVE Asia Tour [DASH: Quantum Leap] in Jakarta", date: "2025-10-18", venue: "Beach City International Stadium (BCIS) Ancol, Jakarta Utara", type: "Konser Musik Internasional (K-pop virtual)", visitors: "", note: "Konser virtual group pertama di Indonesia", category: "Konser Musik", source: "https://www.tempo.co/teroka/plave-akan-konser-di-jakarta-pada-18-oktober-2025-2062660" },
  { id: "k52", organizer: "Color Asia Live", name: "Nancy Ajram Live in Jakarta 2025", date: "2025-11-05", venue: "Istora Senayan", type: "Konser Musik Internasional (Arab Pop)", visitors: "", note: "Diva Lebanon; kolaborasi Ayu Ting Ting", category: "Konser Musik", source: "https://www.tempo.co/teroka/nancy-ajram-siap-hibur-penggemar-di-istora-senayan-malam-ini-2086702" },
  { id: "k53", organizer: "", name: "Maher Zain & Harris J Indonesia Tour", date: "2025-11-09", venue: "Istora Senayan", type: "Konser Musik Internasional (Islamic Pop)", visitors: "", note: "Pembuka tur Indonesia", category: "Konser Musik", source: "https://www.detik.com/pop/music/d-8201140/maher-zain-dan-ikatan-kuat-dengan-industri-musik-indonesia" },
  { id: "k54", organizer: "", name: "the 1/9 tour by eaJ in Jakarta", date: "2025-11-21", venue: "Basket Hall GBK, Senayan", type: "Konser Musik Internasional (K-pop)", visitors: "", note: "eaJ (Jae, eks DAY6)", category: "Konser Musik", source: "https://www.kapanlagi.com/korea/eaj-rilis-single-put-it-on-me-siap-gelar-konser-di-basket-hall-gbk-bulan-november-d6b095.html" },

  // ── Konser Musik Nasional (musisi Indonesia, konser tunggal/headline) ──
  { id: "n01", organizer: "Bank Mandiri", name: "Konser Super Diva", date: "2025-01-17", venue: "Indonesia Arena, GBK Senayan, Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "", note: "Kolaborasi Krisdayanti, Ruth Sahanaya, Titi DJ, Lyodra, Tiara Andini, Ziva Magnolya", category: "Konser Musik", source: "https://m.jpnn.com/news/bank-mandiri-hadirkan-konser-super-diva-di-indonesia-arena-gbk" },
  { id: "n02", organizer: "Expoindo", name: "Pasar Malam Empat Satoe Slank (HUT ke-41)", date: "2025-01-04", venue: "JIExpo Kemayoran, Jakarta", type: "Konser Musik Nasional (Rock/Pop)", visitors: "", note: "Konser tunggal HUT ke-41 Slank", category: "Konser Musik", source: "https://exhibition.jiexpo.com/slank-siap-rayakan-konser-empat-satoe-bersama-slankers/" },
  { id: "n03", organizer: "Nonton Lagu by Kantara Creative", name: "Konser Bingah Yura Yunita", date: "2025-02-02", venue: "Istora Senayan, Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "6.500", note: "sold out; kapasitas", category: "Konser Musik", source: "https://www.liputan6.com/showbiz/read/5903075/tiket-konser-yura-yunita-sold-out-6500-penonton-siap-padati-istora-senayan-jakarta" },
  { id: "n04", organizer: "", name: "Rossa - Here I Am Concert", date: "2025-05-23", venue: "Indonesia Arena, GBK Senayan, Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "12.000", note: "sold out", category: "Konser Musik", source: "https://www.tempo.co/teroka/rossa-manjakan-12-ribu-penonton-dalam-konser-here-i-am-1528206" },
  { id: "n05", organizer: "Antara Suara", name: ".Feast - Pertunjukan Membangun & Menghancurkan", date: "2025-05-31", venue: "Jakarta International Velodrome, Rawamangun, Jakarta Timur", type: "Konser Musik Nasional (Rock)", visitors: "", note: "sold out; 30.000 pendaftar pra-registrasi", category: "Konser Musik", source: "https://www.detik.com/pop/music/d-7943378/feast-rayakan-kebangkitan-di-pertunjukan-membangun-menghancurkan" },
  { id: "n06", organizer: "Sepuluh Dua Empat (1024) x Seraya Live", name: "Hindia - '25 On Blank Canvas", date: "2025-06-07", venue: "Tennis Indoor Senayan, Jakarta", type: "Konser Musik Nasional (Pop/Indie)", visitors: "", note: "Showcase peluncuran mixtape", category: "Konser Musik", source: "https://mediaaku.com/hindia-siap-memukau-jakarta-dengan-konser-intim-25-on-blank-canvas-pada-7-juni-2025/" },
  { id: "n07", organizer: "Gaung Merah (Gudang Garam)", name: "Konser Iwan Fals \"Gaung Merah SeGALAnya\"", date: "2025-06-14", venue: "Eks Hanggar Teras Pancoran, Jakarta Selatan", type: "Konser Musik Nasional (Balada/Pop)", visitors: "", note: "Konser gratis; ribuan penonton", category: "Konser Musik", source: "https://okjakarta.com/2025/06/konser-iwan-fals-dan-band-tkoos-jadi-epilog-spektakuler-di-ex-hanggar-teras-pancoran/" },
  { id: "n08", organizer: "JUNI Concert", name: "Konser Tunggal Bernadya \"Babak Penutup: Untungnya, Untungnya\"", date: "2025-06-20", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM), Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "", note: "Konser tunggal perdana", category: "Konser Musik", source: "https://www.idntimes.com/hype/entertainment/harga-tiket-konser-bernadya-untungnya-untungnya-00-6x7yf-dv6lys" },
  { id: "n09", organizer: "New Live Entertainment", name: "3553 Concert (Yuni Shara)", date: "2025-08-30", venue: "Istora Senayan, Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "", note: "Konser tunggal perdana", category: "Konser Musik", source: "https://www.liputan6.com/showbiz/read/6148000/yuni-shara-sukses-gelar-konser-3553-di-istora-senayan-jakarta-diramaikan-nassar-hingga-ariel-noah" },
  { id: "n10", organizer: "PT Mega Bintang Investama", name: "Konser Dewa 19 Featuring All Stars 2.0", date: "2025-09-06", venue: "Stadion Utama Gelora Bung Karno (GBK), Senayan, Jakarta", type: "Konser Musik Nasional (Rock/Pop)", visitors: "60.000", note: "perkiraan", category: "Konser Musik", source: "https://soundcorners.com/sekitar-60-ribu-penonton-padati-konser-dewa-19-featuring-all-stars-2-0/" },
  { id: "n11", organizer: "", name: "Romansa ke Masa Depan (Konser Hologram Tribute Glenn Fredly)", date: "2025-09-30", venue: "Puri Agung Convention Hall, Grand Sahid Jaya, Jakarta", type: "Konser Musik Nasional (Pop/Tribute)", visitors: "", note: "Konser hologram tribute Glenn Fredly", category: "Konser Musik", source: "https://urbanvibes.id/index.php/2025/08/19/9092-20-agustus-2025-entertainment-romansa-ke-masa-depan-konser-hologram-glenn-fredly-di-grand-sahid-jaya-jakarta/" },
  { id: "n12", organizer: "", name: "Konser Untuk Korban Sakit Hati Banget - Jakarta (Juicy Luicy & Adrian Khalif)", date: "2025-10-11", venue: "Jakarta International Velodrome, Rawamangun, Jakarta Timur", type: "Konser Musik Nasional (Pop)", visitors: "", note: "Co-headline; tamu Maliq & D'Essentials", category: "Konser Musik", source: "https://event.detik.com/898/konser-untuk-korban-sakit-hati-banget---jakarta" },
  { id: "n13", organizer: "", name: "Konser 10 Tahun Sinestesia - Efek Rumah Kaca (IMUST 2025)", date: "2025-11-19", venue: "Teater Wahyu Sihombing, Taman Ismail Marzuki (TIM), Jakarta", type: "Konser Musik Nasional (Indie/Alternatif)", visitors: "", note: "sold out; 10 tahun album Sinestesia", category: "Konser Musik", source: "https://milenianews.com/hiburan/musik/efek-rumah-kaca-buka-imust-2025-dengan-konser-10-tahun-sinestesia/" },
  { id: "n14", organizer: "", name: "Tiara Andini - Edelweiss Showcase 2025", date: "2025-11-21", venue: "Balai Sarbini, Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "", note: "Showcase album 'Edelweiss'; presale sold out", category: "Konser Musik", source: "https://seremonia.id/event/tiara-andini-siap-gelar-edelweiss-showcase-2025-di-balai-sarbini-jakarta/" },
  { id: "n15", organizer: "RedLine", name: "Konser Suarasmara (Andien)", date: "2025-11-15", venue: "Istora Senayan, Jakarta", type: "Konser Musik Nasional (Pop/Jazz)", visitors: "5.000", note: "kapasitas; perayaan 25 tahun karier", category: "Konser Musik", source: "https://www.kompas.com/hype/read/2025/11/15/102054266/andien-gelar-konser-tunggal-suarasmara-hari-ini-di-istora" },
  { id: "n16", organizer: "ALOKA", name: "Rich Brian - WHERE IS MY HEAD? (Asia Tour, Jakarta)", date: "2025-11-29", venue: "Beach City International Stadium (BCIS) Ancol, Jakarta Utara", type: "Konser Musik Nasional (Hip-Hop/Rap)", visitors: "", note: "Musisi diaspora (88rising); kota pembuka tur Asia", category: "Konser Musik", source: "https://www.loket.com/event/rich-brian-where-is-my-head-asian-tour-2025_kTD4" },
  { id: "n17", organizer: "86 Production", name: "Tipe-X \"Tiga Dekade Berdanska\" (30th Anniversary)", date: "2025-11-29", venue: "Gambir Expo, JIExpo Kemayoran, Jakarta", type: "Konser Musik Nasional (Ska)", visitors: "", note: "30 tahun Tipe-X; peluncuran album ke-8", category: "Konser Musik", source: "https://www.liputan6.com/showbiz/read/6216882/tipe-x-gelar-konser-tiga-dekade-berdanska-rayakan-30-tahun-berkarier-dan-jadi-raksasa-musik-ska" },
  { id: "n18", organizer: "Signature Time", name: "Barasuara - Tur Album Showcase Jalaran Sadrah (Penutup Jakarta)", date: "2025-12-20", venue: "Bali United Studio, Kuningan, Jakarta Selatan", type: "Konser Musik Nasional (Rock/Alternatif)", visitors: "", note: "Penutup tur album Jalaran Sadrah", category: "Konser Musik", source: "https://dapurletter.id/2025/12/22/barasuara-tutup-tur-album-showcase-jalaran-sadrah-dengan-konser-meriah-di-jakarta/" },

  // ── Festival Musik ──
  { id: "f01", organizer: "Java Festival Production", name: "BNI Java Jazz Festival 2025", date: "2025-05-30 s/d 2025-06-01", venue: "JIExpo Kemayoran, Jakarta Pusat", type: "Festival Musik (Jazz)", visitors: "", note: "", category: "Festival Musik", source: "https://jakarta.akurat.co/lifestyle/1315791621/bni-java-jazz-festival-2025-kembali-hadir-di-jiexpo-kemayoran-pada-30-mei-hingga-1-juni-berikut-daftar-lineup-fase-pertama" },
  { id: "f02", organizer: "Allo Bank / CT Corp", name: "Allo Bank Festival 2025 (Jakarta)", date: "2025-06-21 s/d 2025-06-22", venue: "Istora Senayan, Jakarta Pusat", type: "Festival Musik (Multi-genre/Pop & K-Pop)", visitors: "", note: "", category: "Festival Musik", source: "https://tirto.id/rundown-allo-bank-festival-2025-open-gate-cara-ke-venue-hdf6" },
  { id: "f03", organizer: "TServe / The Sounds Project", name: "The Sounds Project 2025 (Vol. 8)", date: "2025-08-08 s/d 2025-08-10", venue: "Ecovention & Ecopark Ancol, Jakarta Utara", type: "Festival Musik (Multi-genre)", visitors: "", note: "", category: "Festival Musik", source: "https://www.metrotvnews.com/read/b7WCgB7A-lebih-dari-110-musisi-meriahkan-the-sounds-project-2025" },
  { id: "f04", organizer: "Dyandra / LaLaLa Fest", name: "LaLaLa Festival 2025", date: "2025-08-22 s/d 2025-08-24", venue: "JIExpo Kemayoran, Jakarta Pusat", type: "Festival Musik (Multi-genre, Internasional)", visitors: "", note: "", category: "Festival Musik", source: "https://eventfest.id/events/lalala-festival-2025/" },
  { id: "f05", organizer: "Boss Creator", name: "Pestapora 2025", date: "2025-09-05 s/d 2025-09-07", venue: "Gambir Expo & Hall D2, JIExpo Kemayoran, Jakarta", type: "Festival Musik (Multi-genre)", visitors: "~90.000-100.000", note: "tiket terjual", category: "Festival Musik", source: "https://hypeabis.id/read/41430/lebih-dari-90000-tiket-pestapora-selama-3-hari-sukses-terjual" },
  { id: "f06", organizer: "Demajors (Synchronize Festival)", name: "Synchronize Fest 2025", date: "2025-10-03 s/d 2025-10-05", venue: "Gambir Expo Kemayoran, Jakarta", type: "Festival Musik (Multi-genre)", visitors: "", note: "", category: "Festival Musik", source: "https://www.kompas.com/hype/read/2025/10/03/083123166/synchronize-fest-2025-dimulai-hari-ini-ratusan-musisi-meriahkan-gambir-expo" },
  { id: "f07", organizer: "Plainsong Live (Joyland Festival)", name: "Joyland Sessions Jakarta 2025", date: "2025-11-29 s/d 2025-11-30", venue: "GBK City Park (Senayan), Jakarta Pusat", type: "Festival Musik (Indie/Multi-genre)", visitors: "", note: "", category: "Festival Musik", source: "https://indonesiaexpat.id/events/joyland-sessions-2025/" },
  { id: "f08", organizer: "Detik Network / Soundrenaline", name: "Soundrenaline 2025 (Sana Sini Jakarta)", date: "2025-12-18 s/d 2025-12-21", venue: "Multi-distrik DKI Jakarta (Istora SCBD, Taman Peruri, Blok M)", type: "Festival Musik (Multi-genre)", visitors: "", note: "", category: "Festival Musik", source: "https://www.detik.com/pop/music/d-8254584/jadwal-lengkap-soundrenaline-2025-3-hari-di-3-tempat-dan-line-up-nya" },
  { id: "f09", organizer: "Berlian Entertainment / Erajaya", name: "SoundsFest 2025", date: "2025-05-23 s/d 2025-05-25", venue: "Gambir Expo Kemayoran, JIExpo, Jakarta", type: "Festival Musik (Multi-genre)", visitors: "", note: "Edisi perdana Jakarta; 68 musisi; tema 'Magical Festival'", category: "Festival Musik", source: "https://jakarta.akurat.co/lifestyle/110676/soundsfest-2025-resmi-hadir-di-jakarta-untuk-pertama-kalinya-pada-23-25-mei-nanti-simak-lineup-nya-berikut-ini" },
  { id: "f10", organizer: "JBL / PT Inti Megah Swara", name: "JBL Festival 2025", date: "2025-09-13", venue: "Istora Senayan, Jakarta", type: "Festival Musik (Multi-genre)", visitors: "", note: "Slank, Ari Lasso, Kotak, Tiara Andini", category: "Festival Musik", source: "https://www.liputan6.com/showbiz/read/6154089/jbl-festival-2025-menyapa-istora-senayan-jakarta-13-september-ada-slank-hingga-ari-lasso" },
  { id: "f11", organizer: "Prambors / Men's Biore", name: "Awesome Skool Fest 2025", date: "2025-09-20", venue: "Beach City International Stadium (BCIS) Ancol, Jakarta Utara", type: "Festival Musik (Pop/Indie)", visitors: "", note: "Hindia, .Feast, For Revenge, The Panturas", category: "Festival Musik", source: "https://www.idntimes.com/hype/entertainment/harga-tiket-dan-line-up-awesome-skool-fest-2025-00-6x7yf-p8l2r8" },
  { id: "f12", organizer: "Kementerian UMKM & Kementerian BUMN", name: "KOPLING 2025 (Koplo Keliling) Jakarta", date: "2025-11-08 s/d 2025-11-09", venue: "Gambir Expo Kemayoran, JIExpo, Jakarta", type: "Festival Musik (Dangdut/Koplo)", visitors: "", note: "Edisi perdana Jakarta; 30+ penampil; 192 tenant UMKM", category: "Festival Musik", source: "https://exhibition.jiexpo.com/events/kopling-2025-koplo-keliling/" },
  { id: "f13", organizer: "JakJazz (Jakarta International Jazz Festival)", name: "JakJazz 2025 (edisi ke-15)", date: "2025-12-20", venue: "Senayan Park (SPARK), Jakarta", type: "Festival Musik (Jazz)", visitors: "4.500", note: "kapasitas; kembali setelah vakum 6 tahun", category: "Festival Musik", source: "https://en.antaranews.com/amp/news/382152/jakjazz-festival-returns-dec-20-after-six-year-hiatus" },
  { id: "f14", organizer: "EXPOINDO", name: "Big Bang Festival 2025", date: "2025-12-24 s/d 2026-01-04", venue: "JIExpo Kemayoran, Jakarta", type: "Festival Musik & Bazar (Multi-genre)", visitors: "", note: "Edisi ke-8; konser multi-artis + bazar", category: "Festival Musik", source: "https://www.antaranews.com/berita/5323861/big-bang-festival-2025-kembali-digelar-di-jiexpo-kemayoran" },

  // ── Seni Tari ──
  { id: "p05", organizer: "TMII (InJourney Destination Management)", name: "Pesta Rakyat Nusantara 50 Tahun TMII — 500 anak menari Tarian Nusantara", date: "2025-04-20", venue: "Plaza Keong Mas, Taman Mini Indonesia Indah (TMII), Jakarta Timur", type: "Seni Tari", visitors: "~50.000", note: "perkiraan, 20 April 2025", category: "Seni Tari", source: "https://injourneydestination.id/en/2025/04/20/kemeriahan-hut-ke-50-tmii-dengan-penampilan-500-anak-menarikan-tarian-nusantara/" },
  { id: "p06", organizer: "Indonesia World Dance Festival (IWDF) / Pemprov DKI Jakarta", name: "Indonesia World Dance Festival 2025", date: "2025-05-11", venue: "Gelanggang Remaja Bulungan, Kebayoran Baru, Jakarta Selatan", type: "Seni Tari", visitors: "~800", note: "peserta; 68 sanggar", category: "Seni Tari", source: "https://era.id/nasional/177407/iwdf-2025-digelar-di-jakarta-68-sanggar-tari-jadi-peserta" },
  { id: "p09", organizer: "Yayasan Indonesia Ballet / ballet.id", name: "The Indonesian Ballet Gala 2025", date: "2025-07-06", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM)", type: "Seni Tari", visitors: "", note: "", category: "Seni Tari", source: "https://mediaindonesia.com/hiburan/788859/the-indonesian-ballet-gala-2025-tampilkan-bintang-balet-dunia" },
  { id: "p25", organizer: "Galeri Indonesia Kaya / Bakti Budaya Djarum Foundation", name: "Indonesia Menari 2025 (#MenariDiMall)", date: "2025-10-12", venue: "Grand Indonesia (West Mall), Thamrin, Jakarta Pusat", type: "Seni Tari", visitors: "8.000+", note: "peserta menari", category: "Seni Tari", source: "https://www.tempo.co/foto/arsip/indonesia-menari-2025-di-grand-indonesia-2078882" },
  { id: "p28", organizer: "Étoile Dance Center & Ballet Manila", name: "Balet Cinderella", date: "2025-11-15", venue: "Ciputra Artpreneur, Jakarta", type: "Seni Tari", visitors: "", note: "", category: "Seni Tari", source: "https://urbanvibes.id/index.php/2025/11/15/balet-cinderella-etoile-x-ballet-manila-siap-memukau-jakarta-di-ciputra-artpreneur/" },

  // ── Teater / Musikal ──
  { id: "p01", organizer: "BPI (Yanti Airlangga), sutradara Hanung Bramantyo", name: "Musikal Sinematik \"City of Love\"", date: "2025-02-14", venue: "Plenary Hall, Jakarta Convention Center (JCC) Senayan", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.tvonenews.com/berita/300817-intip-pagelaran-musikal-sinematik-city-of-love-di-jcc" },
  { id: "p03", organizer: "ArtSwara", name: "Drama Musikal \"MAR\"", date: "2025-02-26", venue: "Ciputra Artpreneur, Jakarta", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.ciputraartpreneur.com/events/detail/drama-musikal-mar" },
  { id: "p07", organizer: "New Art Collective (NAC)", name: "Next to Normal (The Musical)", date: "2025-05-07", venue: "Teater Wahyu Sihombing, Taman Ismail Marzuki (TIM)", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.lspr.ac.id/next-to-normal-teater-musikal-yang-mengangkat-tema-tentang-keluarga-dan-kesehatan-mental/" },
  { id: "p08", organizer: "Ciputra Artpreneur", name: "Re-run Musikal Lutung Kasarung", date: "2025-05-22", venue: "Ciputra Artpreneur, Jakarta", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.ciputraartpreneur.com/events/past-tag/musical-theater" },
  { id: "p15", organizer: "Visinema Studios & Indonesia Kaya", name: "Musikal Keluarga Cemara 2025", date: "2025-06-20 s/d 2025-07-13", venue: "Ciputra Artpreneur, Jakarta", type: "Teater / Drama Musikal", visitors: "~30.000", note: "perkiraan, 30 pertunjukan; 30 pertunjukan", category: "Teater / Musikal", source: "https://www.ciputraartpreneur.com/events/detail/musikal-keluarga-cemara-2025" },
  { id: "p14", organizer: "Jakarta Movin & Indonesia Kaya (Bakti Budaya Djarum Foundation)", name: "Musikal Petualangan Sherina", date: "2025-07-11", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM)", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.djarumfoundation.org/aktivitas/musikal-petualangan-sherina-2025-kembali-hadir-merayakan-25-tahun-kisah-ikonik-di-panggung-pertunjukan-indonesia?lang=id" },
  { id: "p16", organizer: "Ciputra Artpreneur & Hi Jakarta Production", name: "School of Rock: The Musical 2025", date: "2025-07-26", venue: "Ciputra Artpreneur, Jakarta", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.ciputraartpreneur.com/events/detail/school-of-rock-the-musical-2025" },
  { id: "p18", organizer: "Teater Koma (sutradara Rangga Riantiarno)", name: "Lakon \"Mencari Semar\" (produksi ke-235, HUT ke-48 Teater Koma)", date: "2025-08-13", venue: "Ciputra Artpreneur, Jakarta", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.detik.com/pop/culture/d-8057708/teater-koma-siap-gelar-lakon-mencari-semar-13-17-agustus" },
  { id: "p20", organizer: "Titimangsa & Bakti Budaya Djarum Foundation", name: "Bunga Penutup Abad", date: "2025-08-29", venue: "Ciputra Artpreneur, Jakarta", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.kompas.id/artikel/en-bunga-penutup-abad-kobarkan-perlawanan" },
  { id: "p21", organizer: "EKI Dance Company", name: "Perempuan Punya Cerita (Musikal)", date: "2025-09-04", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM)", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.beritajakarta.id/potret-jakarta/album/18405/pertunjukan-musikal-perempuan-punya-cerita-di-graha-bhakti-budaya-tim" },
  { id: "p27", organizer: "EKI Foundation & Indonesia Kaya", name: "Festival Musikal Indonesia (FMI) 2025 — 12 komunitas musikal", date: "2025-11-14", venue: "Teater Jakarta, Taman Ismail Marzuki (TIM)", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://adv.kompas.id/baca/festival-musikal-indonesia-2025-kembali-hadirkan-ruang-inklusif-untuk-karya-kolaborasi-dan-kebudayaan/" },
  { id: "p31", organizer: "Titimangsa & PENASTRI", name: "Festival Teater Indonesia 2025 \"Sirkulasi Ilusi\"", date: "2025-12-14", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM)", type: "Teater / Drama Musikal", visitors: "", note: "", category: "Teater / Musikal", source: "https://www.detik.com/pop/culture/d-8260710/festival-teater-indonesia-2025-berlabuh-ke-jakarta" },

  // ── Orkestra / Klasik ──
  { id: "p02", organizer: "Twilite Orchestra (Addie MS) x TipTip & East Ventures", name: "Video Game Concert Volume II", date: "2025-02-22", venue: "Tennis Indoor Senayan, Jakarta", type: "Orkestra / Musik Klasik", visitors: "3.000", note: "perkiraan", category: "Orkestra / Klasik", source: "https://www.detik.com/pop/music/d-7730678/addie-ms-twilite-orchestra-gelar-konser-video-game-concert-volume-ii" },
  { id: "n19", organizer: "Enjoy Live Experience & ImaginAction", name: "Miliaran Cinta: Yovie Widianto - Andi Rianto Berkonser (Magenta Orchestra)", date: "2025-09-21", venue: "Plenary Hall, Jakarta Convention Center (JCC) Senayan, Jakarta", type: "Konser Orkestra Nasional", visitors: "", note: "Tamu Kahitna, Isyana, Monita, dll", category: "Orkestra / Klasik", source: "https://www.tempo.co/teroka/yovie-widianto-dan-andi-rianto-gelar-konser-21-september-2025-2063510" },
  { id: "n20", organizer: "Smartfren / XLSMART", name: "Malam 100 Cinta 2025 (Erwin Gutawa Orchestra)", date: "2025-10-25", venue: "JIExpo Convention Centre & Theatre, Kemayoran, Jakarta", type: "Konser Orkestra Nasional", visitors: "2.400", note: "perkiraan; Erwin Gutawa Orchestra ft. Tulus, Yura Yunita, Lyodra, dll", category: "Orkestra / Klasik", source: "https://selular.id/2025/10/smartfren-sukses-gelar-malam-100-cinta-2025-di-jiexpo-kemayoran/" },
  { id: "p04", organizer: "Jakarta Simfonia Orchestra (Dr. Stephen Tong)", name: "Beethoven Symphony No. 4 & 6", date: "2025-03-22", venue: "Aula Simfonia Jakarta, Kemayoran", type: "Orkestra / Musik Klasik", visitors: "", note: "", category: "Orkestra / Klasik", source: "https://aulasimfoniajakarta.com/id/events/beethoven-symphony-no-4-&-6" },
  { id: "p11", organizer: "Embassy of Italy & Italian Cultural Institute Jakarta", name: "Bel Canto & Beyond: A Night at the Opera", date: "2025-06-22", venue: "Gedung Kesenian Jakarta", type: "Opera / Musik Klasik", visitors: "~500+", note: "perkiraan", category: "Orkestra / Klasik", source: "https://winnicode.com/explore/berita/Budaya/warga-jakarta-haus-hiburan-berkualitas-a-night-at-the-opera-membludak-di-gedung-kesenian" },
  { id: "p17", organizer: "Jakarta Concert Orchestra & The Resonanz (Avip Priatna)", name: "Konser Simfoni untuk Bangsa 2025: 8 Dekade Musik Indonesia", date: "2025-08-02", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM)", type: "Orkestra / Musik Klasik", visitors: "", note: "", category: "Orkestra / Klasik", source: "https://www.kompas.com/hype/read/2025/08/02/183806766/konser-simfoni-untuk-bangsa-2025-hadirkan-perjalanan-musik-dalam-8-dekade" },
  { id: "p23", organizer: "Erwin Gutawa Orchestra", name: "Symphonesia: Bangga Indonesia", date: "2025-09-27 s/d 2025-09-28", venue: "Ciputra Artpreneur, Jakarta", type: "Orkestra / Musik Klasik", visitors: "", note: "2 hari, 4 show; Once Mekel, Putri Ariani, dll", category: "Orkestra / Klasik", source: "https://www.ciputraartpreneur.com/events/detail/erwin-gutawa-orchestra-symphonesia-bangga-indonesia" },
  { id: "p24", organizer: "Ciputra Artpreneur (Disney Concerts; Bandung Philharmonic)", name: "Disney's Beauty and the Beast in Concert", date: "2025-09-27", venue: "Ciputra Artpreneur, Jakarta", type: "Orkestra / Musik Klasik", visitors: "", note: "", category: "Orkestra / Klasik", source: "https://hypeabis.id/read/52557/hari-terakhir-disneys-beauty-and-the-beast-in-concert-hadir-di-ciputra-artpreneur" },
  { id: "p26", organizer: "Twilite Orchestra / Twilite Chorus (Addie MS)", name: "Twilite Chorus 30th Anniversary Concert", date: "2025-11-08", venue: "Aula Simfonia Jakarta, Kemayoran", type: "Orkestra / Musik Klasik", visitors: "", note: "", category: "Orkestra / Klasik", source: "https://www.aulasimfoniajakarta.com/en/events/twilite-chorus-30th-anniversary-concert" },
  { id: "p29", organizer: "Jakarta Concert Orchestra, Batavia Madrigal Singers (Avip Priatna)", name: "Opera Carmen (Bizet)", date: "2025-11-15", venue: "Ciputra Artpreneur, Jakarta", type: "Opera", visitors: "", note: "", category: "Orkestra / Klasik", source: "https://www.nowjakarta.co.id/upcoming-events/bizets-carmen-comes-jakarta/" },
  { id: "p30", organizer: "Erwin Gutawa Orchestra", name: "Symphonesia: Viral 100% Musik Indonesia", date: "2025-12-09", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM)", type: "Orkestra / Musik Klasik", visitors: "", note: "", category: "Orkestra / Klasik", source: "https://eventfest.id/berita/symphonesia-2025-hadirkan-konser-viral-bersama-erwin-gutawa-orchestra/" },

  // ── Seni Tradisional ──
  { id: "p10", organizer: "Pemerintah Provinsi DKI Jakarta", name: "Upacara & Pertunjukan Kolosal HUT ke-498 Jakarta (defile, tari kolosal Betawi)", date: "2025-06-22", venue: "Kawasan Monumen Nasional (Monas), Jakarta Pusat", type: "Seni Tradisional", visitors: "", note: "", category: "Seni Tradisional", source: "https://megapolitan.kompas.com/read/2025/06/22/08360191/upacara-hut-jakarta-di-monas-dimeriahkan-defile-dan-tarian-kolosal" },
  { id: "p22", organizer: "Galeri Indonesia Kaya & Paguyuban Wayang Orang Bharata", name: "Pandawa Nawasena (pagelaran Wayang Orang Bharata lintas generasi)", date: "2025-09-27", venue: "Galeri Indonesia Kaya, Grand Indonesia, Jakarta Pusat", type: "Seni Tradisional", visitors: "", note: "", category: "Seni Tradisional", source: "https://www.biem.co/read/2025/09/28/110413/paguyuban-wayang-orang-bharata-sukses-pentaskan-lakon-pandawa-nawasena-sebuah-karya-seni-tradisi-lintas-generasi/" },
  { id: "p12", organizer: "Dinas Kebudayaan DKI Jakarta", name: "Festival Teater Tradisional Jakarta 2025", date: "Juni 2025", venue: "Gedung Kesenian Jakarta, Jakarta Pusat", type: "Seni Tradisional", visitors: "", note: "", category: "Seni Tradisional", source: "https://seremonia.id/event/festival-teater-tradisional-2025-angkat-cerita-rakyat-jakarta-di-gedung-kesenian/" },

  // ── Seni Rupa ──
  { id: "b05", organizer: "Galeri Nasional Indonesia (Kementerian Kebudayaan)", name: "Pameran NYALA: 200 Tahun Perang Diponegoro", date: "s/d 2025-10-15", venue: "Galeri Nasional Indonesia, Jakarta Pusat", type: "Seni Rupa / Pameran", visitors: "", note: "Berlangsung sepanjang 2025, diperpanjang hingga 15 Okt 2025", category: "Seni Rupa", source: "https://girlsbeyond.com/2025/10/02/lifestyle/5-pameran-seni-oktober-2025-di-jakarta-salah-satunya-ada-art-jakarta" },
  { id: "b02", organizer: "Art Moments Jakarta", name: "Art Moments Jakarta 2025 (tema 'Restoration')", date: "2025-08-07 s/d 2025-08-10", venue: "AGORA Exhibition Hall, Thamrin Nine, Jakarta Pusat", type: "Seni Rupa / Art Fair", visitors: "", note: "", category: "Seni Rupa", source: "https://www.luxuo.com/culture/art/artmoments-jakarta-2025-returns-with-a-new-venue-and-renewed-focus.html" },
  { id: "b01", organizer: "Mandala Media / Art Jakarta", name: "Art Jakarta 2025", date: "2025-10-03 s/d 2025-10-05", venue: "JIExpo Kemayoran (Hall C1, C3, B3)", type: "Seni Rupa / Art Fair", visitors: "~35.000-40.000", note: "target penyelenggara", category: "Seni Rupa", source: "https://eventguide.id/2025/09/12/art-jakarta-2025-di-jiexpo-persembahkan-karya-seni-koleksi-75-galeri-dari-16-negara-catat-tanggalnya/" },
  { id: "b04", organizer: "Museum MACAN", name: "Olafur Eliasson: 'Your curious journey'", date: "2025-11-29 s/d 2026-04-12", venue: "Museum MACAN, Jakarta Barat", type: "Seni Rupa / Pameran", visitors: "", note: "", category: "Seni Rupa", source: "https://www.museummacan.org/exhibition/your-curious-journey" },
  { id: "b03", organizer: "Museum MACAN", name: "Kei Imazu: 'The Sea is Barely Wrinkled'", date: "Mei 2025", venue: "Museum MACAN, Jakarta Barat", type: "Seni Rupa / Pameran", visitors: "", note: "", category: "Seni Rupa", source: "https://www.detik.com/pop/culture/d-7801479/museum-macan-umumkan-3-pameran-seni-terbesar-sepanjang-2025" },

  // ── Film ──
  { id: "b09", organizer: "Delegasi Uni Eropa untuk Indonesia & lembaga kebudayaan Eropa", name: "Europe on Screen 2025 (edisi ke-25)", date: "2025-06-13 s/d 2025-06-22", venue: "Berbagai venue di Jakarta (kota utama, ~80% program)", type: "Festival Film", visitors: "", note: "", category: "Film", source: "https://www.eeas.europa.eu/delegations/indonesia/europe-screen-2025-celebrating-25-years-cinematic-exchange_en" },
  { id: "b07", organizer: "Dinas Kebudayaan & Dinas Pariwisata DKI Jakarta", name: "Jakarta Film Week 2025 (tema 'REIGNITE')", date: "2025-10-22 s/d 2025-10-26", venue: "CGV Grand Indonesia, CGV FX Sudirman, TIM, dll (Jakarta)", type: "Festival Film", visitors: "", note: "", category: "Film", source: "https://en.wikipedia.org/wiki/2025_Jakarta_Film_Week" },
  { id: "b08", organizer: "Komite FFI / Badan Perfilman Indonesia", name: "Malam Anugerah Festival Film Indonesia (FFI) 2025 — Piala Citra", date: "2025-11-20", venue: "Teater Jakarta, Taman Ismail Marzuki (TIM), Jakarta Pusat", type: "Festival Film / Penghargaan", visitors: "", note: "", category: "Film", source: "https://en.wikipedia.org/wiki/2025_Indonesian_Film_Festival" },

  // ── Budaya ──
  { id: "b12", organizer: "Pemkot Jakarta Barat / komunitas Pancoran Chinatown Glodok", name: "Festival Cap Go Meh 2025 Glodok", date: "2025-02-12", venue: "Pancoran Chinatown Point, Glodok, Jakarta Barat", type: "Acara Budaya / Festival", visitors: "", note: "", category: "Budaya", source: "https://barat.jakarta.go.id/berita/perayaan-cap-go-meh-2025-di-pancoran-chinatown-glodok-meriah" },
  { id: "b10", organizer: "PT Jakarta International Expo (JIExpo) / Pemprov DKI Jakarta", name: "Jakarta Fair Kemayoran 2025 (PRJ)", date: "2025-06-19 s/d 2025-07-13", venue: "JIExpo Kemayoran, Jakarta Pusat", type: "Acara Budaya / Pameran & Festival (rangkaian konser)", visitors: "5.900.000", note: "total pengunjung, sumber penyelenggara", category: "Budaya", source: "https://www.jakartafair.co.id/post/jakarta-fair-kemayoran-2025-resmi-dibuka" },
  { id: "p13", organizer: "Pemerintah Provinsi DKI Jakarta", name: "Jakarta dalam Warna (pagelaran tari kolosal Betawi & silat)", date: "2025-07-06", venue: "Bundaran Hotel Indonesia (HI), Jakarta Pusat", type: "Pertunjukan Budaya", visitors: "7.000+", note: "pengisi; 5.000 pesilat + 2.000 penari", category: "Budaya", source: "https://www.jakarta.go.id/siaran-pers/5682-SP-HMS-07-2025" },
  { id: "p19", organizer: "Yayasan Sabang Merauke; musik oleh Jakarta Concert Orchestra (Avip Priatna)", name: "Pagelaran Sabang Merauke 2025: The Indonesian Broadway — Hikayat Nusantara", date: "2025-08-23", venue: "Indonesia Arena, GBK Senayan, Jakarta", type: "Pertunjukan Budaya", visitors: "~28.000", note: "perkiraan; tiket ~92% terjual", category: "Budaya", source: "https://lifestyle.bisnis.com/read/20250824/254/1905054/pagelaran-sabang-merauke-tampilkan-pertunjukan-kolosal-nan-megah" },
  { id: "b06", organizer: "Museum Nasional Indonesia (Kementerian Kebudayaan)", name: "Pembukaan Kembali & Pameran 'Sejarah Awal' (repatriasi fosil Java Man)", date: "2025-09-04 s/d 2025-12-18", venue: "Museum Nasional Indonesia, Jakarta Pusat", type: "Acara Budaya / Pameran Museum", visitors: "", note: "Buka kembali 4 Sep; pameran 'Sejarah Awal' mulai 18 Des 2025", category: "Budaya", source: "https://www.museumnasional.or.id/5375/" },

  // ── Fashion ──
  { id: "b11", organizer: "Jakarta Fashion Week (Femina Group / APPMI)", name: "Jakarta Fashion Week (edisi ke-18, 'The Legacy of Style')", date: "2025-10-27 s/d 2025-11-02", venue: "Pondok Indah Mall 3, Jakarta Selatan", type: "Fashion", visitors: "", note: "", category: "Fashion", source: "https://jtdapperfashionweek.com/2025/10/30/jakarta-fashion-week-2026-entitled-the-legacy-of-style/" },
  { id: "fs01", organizer: "Indonesian Fashion Chamber & Dyandra Promosindo", name: "MUFFEST+ 2025 (Muslim Fashion Festival)", date: "2025-02-20 s/d 2025-02-23", venue: "Hall A, Jakarta Convention Center (JCC) Senayan, Jakarta", type: "Fashion / Peragaan Busana (Modest)", visitors: "", note: "Edisi ke-10; ~130 brand & desainer", category: "Fashion", source: "https://www.farah.id/read/2025/02/20/18211/muffest+-2025-resmi-dibuka" },
  { id: "fs02", organizer: "APPMI (Poppy Dharsono)", name: "Indonesia Fashion Week (IFW) 2025", date: "2025-05-28 s/d 2025-06-01", venue: "Jakarta Convention Center (JCC) Senayan, Jakarta", type: "Fashion / Peragaan Busana", visitors: "", note: "Tema 'Ronakultura Jakarta'; 200+ desainer", category: "Fashion", source: "https://www.tempo.co/gaya-hidup/indonesia-fashion-week-2025-gandeng-200-desainer-1583496" },
  { id: "fs03", organizer: "JF3 / Summarecon", name: "JF3 Fashion Festival 2025", date: "2025-07-24 s/d 2025-07-27", venue: "Summarecon Mall Kelapa Gading, Jakarta Utara", type: "Fashion / Peragaan Busana", visitors: "", note: "45+ desainer lokal & internasional; tema 'Recrafted'", category: "Fashion", source: "https://www.indonesianjournal.id/jf3-fashion-festival-kembali-digelar-di-summarecon-mall-kelapa-gading-24-27-juli-2025/" },
  { id: "fs04", organizer: "Plaza Indonesia", name: "Plaza Indonesia Fashion Week (PIFW) 2025", date: "2025-09-06 s/d 2025-09-14", venue: "The Warehouse, Plaza Indonesia, Jakarta Pusat", type: "Fashion / Peragaan Busana", visitors: "", note: "35 tahun PI; 35 fashion show + 3 kids + 1 special", category: "Fashion", source: "https://daman.co.id/plaza-indonesia-fashion-week-2025-schedule" },
  { id: "fs05", organizer: "Senayan City", name: "Senayan City Fashion Nation XIX 2025", date: "2025-09-19 s/d 2025-09-27", venue: "Main Atrium, Senayan City, Jakarta Selatan", type: "Fashion / Peragaan Busana", visitors: "", note: "Edisi ke-19; 3 maestro mode (Agus Lim, Rinaldy Yunardi, Tex Saverio)", category: "Fashion", source: "https://lifestyle.kompas.com/read/2025/09/20/113500120/senayan-city-fashion-nation-ke-19-digelar-gandeng-3-maestro-fesyen" },
  { id: "fs06", organizer: "Bank Indonesia & Indonesian Fashion Chamber", name: "IN2MOTIONFEST 2025 / ISEF (Indonesia Int'l Modest Fashion Festival)", date: "2025-10-08 s/d 2025-10-12", venue: "JIExpo Convention Centre & Theatre, Kemayoran, Jakarta", type: "Fashion / Peragaan Busana (Modest)", visitors: "", note: "241 desainer lokal + 11 internasional; 1.175 karya", category: "Fashion", source: "https://lifestyle.kompas.com/read/2025/10/08/203500320/in2motionfest-2025-pamerkan-karya-ratusan-desainer-lokal-dan-internasional" },
  { id: "fs07", organizer: "Kementerian Perdagangan RI & Indonesian Fashion Chamber", name: "Jakarta Muslim Fashion Week (JMFW) — digelar Nov 2025", date: "2025-11-06 s/d 2025-11-09", venue: "Kartika Expo, Balai Kartini, Jakarta Selatan", type: "Fashion / Peragaan Busana (Modest)", visitors: "8.000", note: "target; branded 'JMFW 2026' tapi fisik Nov 2025; 200+ brand, 100+ desainer", category: "Fashion", source: "https://getimedia.id/2025/11/06/jakarta-muslim-fashion-week-2026-siap-digelar-hadirkan-ratusan-jenama-modest-fashion/" },

  // ── Budaya Pop (convention/expo budaya pop & hobi skala besar) ──
  { id: "bp01", organizer: "Sozo / AFA", name: "Anime Festival Asia (AFA) Indonesia 2025", date: "2025-06-06 s/d 2025-06-08", venue: "Jakarta Convention Center (JCC), Hall A, Senayan, Jakarta Pusat", type: "Budaya Pop Jepang / Convention (ACG)", visitors: "", note: "Edisi ke-9; ACG terbesar Asia Tenggara", category: "Budaya Pop", source: "https://animefestival.asia/afaid25/" },
  { id: "bp02", organizer: "Panorama Media / MNC", name: "myBCA Indonesia Comic Con x INACON 2025", date: "2025-10-25 s/d 2025-10-26", venue: "Jakarta International Convention Center (JICC), Senayan, Jakarta Pusat", type: "Budaya Pop / Convention (comic, anime, game)", visitors: "", note: "Edisi ke-10; target 30.000-35.000 pengunjung", category: "Budaya Pop", source: "https://www.inilah.com/festival-pop-culture-terbesar-mybca-icc-x-inacon-2025-siap-digelar-akhir-pekan-ini" },
  { id: "bp03", organizer: "Cosplay Expo", name: "Cosplay Expo 2025: Invasion of GBK", date: "2025-10-18 s/d 2025-10-19", venue: "Stadion Utama Gelora Bung Karno (GBK), Senayan, Jakarta Pusat", type: "Budaya Pop / Cosplay (anime, manga, game, J-Pop)", visitors: "", note: "Pertama kali di Stadion Utama GBK", category: "Budaya Pop", source: "https://holopis.com/2025/10/19/ribuan-karakter-fantasi-penuhi-gbk-di-cosplay-expo-2025/" },
  { id: "bp04", organizer: "Windah Basudara x WCG / Motion IME", name: "WCG x Motion IME Festival 2025", date: "2025-12-12 s/d 2025-12-14", venue: "Gambir Expo & Hall D2, JIExpo Kemayoran, Jakarta Pusat", type: "Budaya Pop / Gaming & Creator Festival", visitors: "90.000", note: "gaming, K-Pop, cosplay; 3 hari", category: "Budaya Pop", source: "https://eventguide.id/2025/12/14/wcg-x-motion-ime-2025-leburkan-berbagai-elemen-budaya-pop-secara-asyik/" },
  { id: "bp05", organizer: "Provaliant Group", name: "The Jakarta 20th Toys & Comics Fair 2025", date: "2025-02-08 s/d 2025-02-09", venue: "Kartika Expo Center, Balai Kartini, Jakarta Selatan", type: "Pameran Mainan & Komik / Toys & Hobby Fair", visitors: "", note: "Edisi ke-20; 200+ booth vendor", category: "Budaya Pop", source: "https://www.jakartatoysfair.id/" },

  // ── Fan Meeting (Hallyu — aktor Korea) ──
  { id: "fm01", organizer: "Mecima Pro / Color Asia Live", name: "Hwang In Youp Fanmeeting Tour [IN LOVE] in Jakarta", date: "2025-02-15", venue: "The Kasablanka Hall, Jakarta Selatan", type: "Fan Meeting Hallyu (Aktor Korea)", visitors: "", note: "", category: "Fan Meeting", source: "https://www.tempo.co/hiburan/hwang-in-youp-buat-penggemar-jatuh-cinta-di-fan-meeting-jakarta-1207760" },
  { id: "fm02", organizer: "", name: "Lee Do Hyun Fanmeeting [Re DO HYUN] in Jakarta", date: "2025-06-28", venue: "The Kasablanka Hall, Jakarta", type: "Fan Meeting Hallyu (Aktor Korea)", visitors: "", note: "Fan meeting perdana di Jakarta", category: "Fan Meeting", source: "https://www.tempo.co/hiburan/lee-do-hyun-gelar-fan-meeting-pertama-di-jakarta-28-juni-2025-1825294" },
  { id: "fm03", organizer: "", name: "Ahn Hyo Seop Fanmeeting 'I Want to Say (Love, Jakarta)'", date: "2025-08-23", venue: "Hall D2, JIExpo Kemayoran, Jakarta", type: "Fan Meeting Hallyu (Aktor Korea)", visitors: "", note: "", category: "Fan Meeting", source: "https://exhibition.jiexpo.com/events/2025-ahn-hyo-seop-fanmeeting-i-want-to-say-love-jakarta/" },
  { id: "fm04", organizer: "Mecimapro", name: "Han So Hee Fan Meeting 'Xohee Loved Ones' in Jakarta", date: "2025-10-18", venue: "The Kasablanka Hall, Jakarta", type: "Fan Meeting Hallyu (Aktor Korea)", visitors: "", note: "Fan meeting perdana di Indonesia", category: "Fan Meeting", source: "https://www.suara.com/entertainment/2025/10/19/101252/fan-meeting-perdana-di-jakarta-disambut-antusias-han-so-hee-menangis-haru-hingga-janji-coba-seblak" },
  { id: "fm05", organizer: "", name: "Lee Chae Min Fan Meeting Tour 'Chaem-into YOU' in Jakarta", date: "2025-11-15", venue: "Balai Sarbini, Jakarta", type: "Fan Meeting Hallyu (Aktor Korea)", visitors: "", note: "Fan meeting perdana di luar Korea Selatan", category: "Fan Meeting", source: "https://www.idntimes.com/korea/kdrama/fanmeet-lee-chae-min-digelar-di-balai-sarbini-jakarta-pada-november-00-hwff8-cwxfqx" },
  { id: "fm06", organizer: "FriedRice Entertainment", name: "2025 Yoo Yeon Seok Fanmeeting [The Secret Code: Y] in Jakarta", date: "2025-04-05", venue: "JIExpo Theatre, Kemayoran, Jakarta Pusat", type: "Fan Meeting Hallyu (Aktor Korea)", visitors: "", note: "Stop terakhir tur Asia", category: "Fan Meeting", source: "https://yysjakarta.com/" },
  { id: "fm07", organizer: "Luppyverse Production", name: "2025 Hyeri Fanmeeting Tour: Welcome to HYERI'S STUDIO in Jakarta", date: "2025-08-09", venue: "The Kasablanka Hall, Jakarta Selatan", type: "Fan Meeting Hallyu (Aktris/eks Girl's Day)", visitors: "", note: "Fan meeting perdana di Jakarta", category: "Fan Meeting", source: "https://theseoulstory.com/upcoming-event-2025-hyeri-fanmeeting-tour-in-jakarta-welcome-to-hyeris-studio/" },
  { id: "fm08", organizer: "WeTV", name: "WeTV Always More (Fan Meeting Zhou Yiran & Meng Ziyi)", date: "2025-11-19", venue: "Fairmont Hotel Jakarta, Jakarta Pusat", type: "Fan Meeting Asia (Aktor Tiongkok)", visitors: "", note: "Bintang tamu Meng Ziyi", category: "Fan Meeting", source: "https://todaystage.com/articles/events/wetv-always-more-2026-zhou-yiran-meng-ziyi-arrive-in-jakarta-as-wetv-prepares-to-launch-new-genres/" },

  // ── Penyisiran akhir — Konser Nasional tambahan ──
  { id: "n21", organizer: "JUNI Records", name: "Raisa - ambiVert Showcase", date: "2025-07-23", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM), Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "", note: "Showcase peluncuran album kelima", category: "Konser Musik", source: "https://jakarta.akurat.co/lifestyle/112995/raisa-ambivert-showcase-konser-dan-peluncuran-album-kelima-di-graha-bhakti-budaya-tim-pada-23-juli-2025-segini-harga-tiketnya" },
  { id: "n22", organizer: "Bengkelive / Bengkel Space SCBD", name: "MALIQ & D'Essentials Intimate Concert (Bengkel SCBD 4th Anniversary)", date: "2025-07-31", venue: "Bengkel Space, Fairgrounds SCBD, Jakarta Selatan", type: "Konser Musik Nasional (Pop/Soul)", visitors: "", note: "Intimate concert", category: "Konser Musik", source: "https://matalelaki.com/event/read/bengkel-scbd-jakarta-4th-anniversary-day-1-maliq-d-essentials" },
  { id: "n23", organizer: "Kolam Ikan Creative Communication", name: "Vina Panduwinata - The Untold Story Live in Concert", date: "2025-09-12", venue: "Balai Sarbini, Jakarta", type: "Konser Musik Nasional (Pop)", visitors: "", note: "", category: "Konser Musik", source: "https://www.metrotvnews.com/play/K5nC7By5-vina-panduwinata-hibur-penggemar-lintas-generasi-lewat-the-untold-story-live-concert" },
  { id: "n24", organizer: "", name: "Pamungkas Live at Bengkel Space", date: "2025-12-19", venue: "Bengkel Space, SCBD, Jakarta Selatan", type: "Konser Musik Nasional (Pop/Indie)", visitors: "", note: "", category: "Konser Musik", source: "https://www.shazam.com/event/becac73e-3465-408e-b4fd-335753cbfd5e" },

  // ── Penyisiran akhir — Teater / Musikal tambahan ──
  { id: "pt01", organizer: "Jakarta Art House", name: "Mamma Mia! The Musical Re-run 2025", date: "2025-05-21 s/d 2025-06-01", venue: "Graha Bhakti Budaya, Taman Ismail Marzuki (TIM), Jakarta", type: "Teater / Drama Musikal", visitors: "12.000", note: "14 pertunjukan; lisensi internasional, musik live ABBA", category: "Teater / Musikal", source: "https://biz.kompas.com/read/2025/05/05/172905328/mamma-mia-the-musical-re-run-2025-hadirkan-14-pertunjukan-36-aktor-dan-nostalgia" },
  { id: "pt02", organizer: "Dinas Kebudayaan DKI Jakarta", name: "Festival Teater Jakarta (FTJ) 2025", date: "2025-10-16", venue: "Gedung Kesenian Jakarta, Jakarta Pusat", type: "Teater / Festival", visitors: "", note: "Festival teater tahunan Dinas Kebudayaan DKI", category: "Teater / Musikal", source: "https://www.facebook.com/disbuddki/posts/805436175526578/" },
  { id: "pt03", organizer: "Svara Production", name: "SvaTheFest 2025", date: "2025-10-01 s/d 2025-10-04", venue: "Gedung Kesenian Jakarta, Jakarta Pusat", type: "Teater / Drama Musikal", visitors: "", note: "Festival teater & musikal lintas generasi", category: "Teater / Musikal", source: "https://www.liputan6.com/showbiz/read/6176476/svathefest-2025-sukses-digelar-di-jakarta-wadah-pergelaran-teater-hingga-musikal-lintas-generasi" },
  { id: "pt04", organizer: "Salihara Arts Center", name: "Jakarta Performing Arts Festival (JPAF) 2025", date: "Oktober 2025", venue: "Teater Salihara, Jakarta Selatan", type: "Seni Pertunjukan / Festival", visitors: "", note: "Festival teater, musik, tari (tanggal pasti belum dikonfirmasi)", category: "Teater / Musikal", source: "https://hijkt.com/jadwal-acara-seni-jakarta-2025-jangan-lewatkan/" },
  { id: "pt05", organizer: "ADPRO", name: "Musikal Bawang Merah Bawang Putih", date: "2025-05-10", venue: "Galeri Indonesia Kaya, Jakarta Pusat", type: "Teater / Drama Musikal", visitors: "", note: "Musikal cerita rakyat (2 pertunjukan)", category: "Teater / Musikal", source: "https://hypeabis.id/read/48545/cek-agenda-pentas-teater-musikal-menarik-sepanjang-mei-2025" },

  // ── Penyisiran akhir — Seni Tradisional tambahan ──
  { id: "tr01", organizer: "Pemprov DKI Jakarta (Dinas Kebudayaan)", name: "Jakarnaval 2025", date: "2025-06-22", venue: "Monas - Bundaran HI, Jakarta Pusat", type: "Seni Tradisional / Karnaval Budaya", visitors: "", note: "Karnaval budaya HUT ke-498 Jakarta", category: "Seni Tradisional", source: "https://www.traveloka.com/id-id/explore/destination/daftar-event-acara-ulang-tahun-jakarta-2025-gt/592326" },
  { id: "tr02", organizer: "Pemprov DKI Jakarta (Dinas Kebudayaan)", name: "Lebaran Betawi 2025", date: "2025-04-25 s/d 2025-04-26", venue: "Kawasan Monas, Jakarta Pusat", type: "Seni Tradisional (Budaya Betawi)", visitors: "", note: "Lenong, tanjidor, gambang kromong, palang pintu", category: "Seni Tradisional", source: "https://www.tempo.co/hiburan/ragam-tradisi-dan-kesenian-di-lebaran-betawi-2025-1247731" },
  { id: "tr03", organizer: "Pemkot Jakarta Timur / Dinas Kebudayaan DKI", name: "Festival Ondel-Ondel & Festival Palang Pintu 2025", date: "2025-06-28", venue: "Taman Mini Indonesia Indah (TMII), Jakarta Timur", type: "Seni Tradisional (Budaya Betawi)", visitors: "", note: "Parade ondel-ondel, aksi palang pintu", category: "Seni Tradisional", source: "https://www.tempo.co/hiburan/ragam-tradisi-dan-kesenian-di-lebaran-betawi-2025-1247731" },
  { id: "tr04", organizer: "Indonesian Contemporary Gamelan Ensemble / Salihara", name: "Jakarta Contemporary Gamelan Festival 2025", date: "2025-09-12 s/d 2025-09-13", venue: "Teater Salihara, Jakarta Selatan", type: "Seni Tradisional / Gamelan", visitors: "", note: "Edisi perdana; gamelan Jawa-Sunda-Bali & kontemporer", category: "Seni Tradisional", source: "https://tiket.salihara.org/acara/jakarta-contemporary-gamelan-festival-2025-diversity-in-gamelan" },

  // ── Penyisiran akhir — Seni Rupa tambahan ──
  { id: "sr01", organizer: "JIPFest", name: "Jakarta International Photo Festival (JIPFest) 2025 - 'Coexistence'", date: "2025-09-12 s/d 2025-09-21", venue: "Galeri Emiria Soenassa & S. Sudjojono, Taman Ismail Marzuki, Jakarta", type: "Seni Rupa / Festival Fotografi", visitors: "", note: "300+ karya; 21 fotografer terpilih", category: "Seni Rupa", source: "https://jipfest.com/2025/05/call-for-submissions-photo-exhibition-at-jipfest-2025/" },
  { id: "sr02", organizer: "Galeri Cemara / komunitas fotografi", name: "Rekam Jakarta 2025 - 'Metamorph'", date: "2025-08-22 s/d 2025-08-28", venue: "Galeri Cemara, Menteng, Jakarta Pusat", type: "Seni Rupa / Pameran Fotografi", visitors: "", note: "Edisi ke-6; 53 fotografer", category: "Seni Rupa", source: "https://megapolitan.antaranews.com/berita/426601/wamenekraf-apresiasi-pameran-fotografi-rekam-jakarta-2025-sebagai-arsip-ibukota" },
  { id: "sr03", organizer: "Nadi Gallery", name: "Ugo Untoro: 'Melukis Rintik yang Menolak Kering'", date: "2025-07-24 s/d 2025-08-24", venue: "Nadi Gallery, Jakarta Barat", type: "Seni Rupa / Pameran Tunggal", visitors: "", note: "Pameran tunggal; kurator Sudjud Dartanto", category: "Seni Rupa", source: "https://www.kompas.id/artikel/pameran-tunggal-ugo-untoro-di-galeri-nadi" },

  // ── Penyisiran akhir — Festival Film tambahan ──
  { id: "fl01", organizer: "Forum Lenteng", name: "ARKIPEL 2025 (ke-12) - 'Years of Living Dangerously'", date: "2025-08-30 s/d 2025-09-14", venue: "Forum Lenteng & TMII, Jakarta", type: "Festival Film (Dokumenter/Eksperimental)", visitors: "", note: "80 film dari 26 negara; gratis", category: "Film", source: "https://arkipel.org/" },
  { id: "fl02", organizer: "Madani International Film Festival", name: "Madani International Film Festival 2025 (ke-8) - 'Misykat'", date: "2025-10-08 s/d 2025-10-12", venue: "Taman Ismail Marzuki & bioskop di Jakarta", type: "Festival Film", visitors: "", note: "95 film dari 24 negara", category: "Film", source: "https://www.kompas.com/hype/read/2025/10/07/210312466/madani-international-film-festival-hadirkan-95-film-dari-24-negara" },
  { id: "fl03", organizer: "Jakarta World Cinema", name: "Jakarta World Cinema (JWC) 2025", date: "2025-09-27 s/d 2025-10-04", venue: "CGV Grand Indonesia, Jakarta Pusat", type: "Festival Film", visitors: "", note: "185 film dari 66 negara", category: "Film", source: "https://variety.com/2025/film/news/joachim-trier-jafar-panahi-jakarta-world-cinema-festival-1236500770/" },
];

/** Bulan Indonesia → angka (untuk pengurutan tanggal "Bulan 2025"). */
const BULAN: Record<string, number> = {
  januari: 1, februari: 2, maret: 3, april: 4, mei: 5, juni: 6,
  juli: 7, agustus: 8, september: 9, oktober: 10, november: 11, desember: 12,
};

/** Kunci urut kronologis dari string tanggal (best-effort). */
export function eventDateSort(date: string): number {
  const iso = date.match(/(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return Number(iso[1] + iso[2] + iso[3]);
  const m = date.toLowerCase().match(/([a-z]+)\s+(\d{4})/);
  if (m && BULAN[m[1]]) return Number(`${m[2]}${String(BULAN[m[1]]).padStart(2, "0")}00`);
  const y = date.match(/(\d{4})/);
  if (y) return Number(`${y[1]}0000`);
  return 99999999;
}

/** Event dengan angka pengunjung yang masih perkiraan/kapasitas (perlu verifikasi). */
export function eventNeedsVerify(e: GciEvent): boolean {
  return /perkiraan|kapasitas|target|estimasi|terjual/i.test(e.note);
}

export const GCI_EVENTS: GciEvent[] = [...SEED].sort(
  (a, b) => eventDateSort(a.date) - eventDateSort(b.date)
);

export function eventStats() {
  return {
    total: GCI_EVENTS.length,
    musik: GCI_EVENTS.filter(
      (e) => e.category === "Konser Musik" || e.category === "Festival Musik"
    ).length,
    konser: GCI_EVENTS.filter((e) => e.category === "Konser Musik").length,
    festival: GCI_EVENTS.filter((e) => e.category === "Festival Musik").length,
    budaya: GCI_EVENTS.filter(
      (e) => e.category !== "Konser Musik" && e.category !== "Festival Musik"
    ).length,
    withVisitors: GCI_EVENTS.filter((e) => e.visitors && !eventNeedsVerify(e)).length,
  };
}
