/**
 * Curated directory of Jakarta restaurants/bars serving international cuisine
 * or beverages. Ratings + review counts were extracted from public aggregator
 * pages (Wanderlog, TripAdvisor, NOW! Jakarta, What's New Indonesia, Chope).
 * Google review counts are preferred where both are reported, since they
 * carry the larger sample size. Every record carries source URLs so the
 * listing can be re-verified.
 *
 * Permanently-closed venues from the source lists have been omitted.
 */

export type Restaurant = {
  id: string;
  name: string;
  cuisine: string;
  category: "Food" | "Beverage" | "Food & Beverage";
  area: string;
  address?: string;
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  priceNote?: string;
  rating?: number;            // 0–5
  reviewCount?: number;       // total reviews
  ratingSource?: "Google" | "TripAdvisor";
  highlights: string[];
  description: string;
  sources: { label: string; url: string }[];
};

const SRC = {
  wlFineDining: { label: "Wanderlog — Fine Dining Jakarta", url: "https://wanderlog.com/list/geoCategory/1524810/best-fine-dining-restaurants-in-jakarta" },
  wlNice: { label: "Wanderlog — Nice & Fine Dining", url: "https://wanderlog.com/list/geoCategory/40087/nice-restaurants-and-fine-dining-in-jakarta" },
  wlItalian: { label: "Wanderlog — Italian Jakarta", url: "https://wanderlog.com/list/geoCategory/52581/best-italian-restaurants-in-jakarta" },
  wlFrench: { label: "Wanderlog — French Jakarta", url: "https://wanderlog.com/list/geoCategory/45441/best-french-restaurants-and-bistros-in-jakarta" },
  wlJapanese: { label: "Wanderlog — Japanese Jakarta", url: "https://wanderlog.com/list/geoCategory/54366/best-japanese-food-and-restaurants-in-jakarta" },
  wlChinese: { label: "Wanderlog — Chinese Jakarta", url: "https://wanderlog.com/list/geoCategory/22236/best-chinese-food-in-jakarta" },
  wlKorean: { label: "Wanderlog — Korean Jakarta", url: "https://wanderlog.com/list/geoCategory/1501051/best-korean-restaurants-in-jakarta" },
  wlThai: { label: "Wanderlog — Thai Jakarta", url: "https://wanderlog.com/list/geoCategory/765088/best-thai-foods-and-restaurants-in-jakarta" },
  wlVietnamese: { label: "Wanderlog — Vietnamese Jakarta", url: "https://wanderlog.com/list/geoCategory/792073/best-vietnamese-foods-and-restaurants-in-jakarta" },
  wlMexican: { label: "Wanderlog — Mexican Jakarta", url: "https://wanderlog.com/list/geoCategory/775882/best-mexican-foods-and-restaurants-in-jakarta" },
  wlIndian: { label: "Wanderlog — Indian Jakarta", url: "https://wanderlog.com/list/geoCategory/761490/best-indian-foods-and-restaurants-in-jakarta" },
  wlAmerican: { label: "Wanderlog — American Jakarta", url: "https://wanderlog.com/list/geoCategory/818/best-american-restaurants-in-jakarta" },
  wlSpanish: { label: "Wanderlog — Spanish Jakarta", url: "https://wanderlog.com/list/geoCategory/804666/best-spanish-foods-and-restaurants-in-jakarta" },
  wlMiddleEastern: { label: "Wanderlog — Middle Eastern Jakarta", url: "https://wanderlog.com/list/geoCategory/763289/best-middle-eastern-foods-and-restaurants-in-jakarta" },
  wlEuropean: { label: "Wanderlog — European Jakarta", url: "https://wanderlog.com/list/geoCategory/1522630/best-european-restaurants-in-jakarta" },
  wniFineDining: { label: "What's New Indonesia — Fine Dining", url: "https://whatsnewindonesia.com/ultimate-guide/jakarta/best-fine-dining-restaurants-jakarta" },
  wniBars: { label: "What's New Indonesia — Best Bars 2026", url: "https://whatsnewindonesia.com/ultimate-guide/jakarta/best-bars-jakarta" },
  wniSteak: { label: "What's New Indonesia — Best Steaks", url: "https://whatsnewindonesia.com/jakarta/ultimate-guide/food-and-drink/best-places-steak-jakarta" },
  wniME: { label: "What's New Indonesia — Middle Eastern", url: "https://whatsnewindonesia.com/jakarta/ultimate-guide/food-and-drink/best-middle-eastern-restaurants-jakarta" },
  wniViet: { label: "What's New Indonesia — Vietnamese", url: "https://whatsnewindonesia.com/jakarta/ultimate-guide/food-and-drink/best-vietnamese-restaurants-jakarta-where-you-can-find-pho" },
  nowBars: { label: "NOW! Jakarta — Cocktail Bars", url: "https://www.nowjakarta.co.id/the-best-cocktail-bars-in-jakarta-from-speakeasies-to-social-hotspots/" },
  chopeChinese: { label: "Chope — Chinese Guide", url: "https://www.chope.co/jakarta-restaurants/pages/chineseguide?lang=en_US" },
  chopeSenopati: { label: "Chope — Senopati Guide", url: "https://www.chope.co/jakarta-restaurants/pages/senopati-gunawarman-area-guide?lang=en_US" },
};

export const RESTAURANTS: Restaurant[] = [
  // ───────── ITALIAN ─────────
  { id: "toscana", name: "Toscana", cuisine: "Italian", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya No.120, Mampang Prapatan", priceRange: "$$$", rating: 4.5, reviewCount: 1476, ratingSource: "Google", highlights: ["22-year Kemang pioneer", "Brick-walled trattoria", "Pasta & grilled meats"], description: "Elegant Kemang trattoria, a fine-dining pioneer for over two decades. Pasta, grilled meats and seafood in a charming brick-walled room.", sources: [SRC.wlItalian] },
  { id: "mamma-rosy", name: "Mamma Rosy", cuisine: "Italian", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya No.58, Mampang Prapatan", priceRange: "$$$", rating: 4.5, reviewCount: 3749, ratingSource: "Google", highlights: ["Balinese architecture meets Italian", "Family recipes by Rosa Vignolo", "Cozy terrace & bar"], description: "Balinese-Italian fusion setting in Kemang Raya. Homemade dishes from cherished family recipes by Rosa 'Mamma' Vignolo.", sources: [SRC.wlItalian] },
  { id: "osteria-gia", name: "Osteria GIA", cuisine: "Italian", category: "Food & Beverage", area: "Plaza Indonesia, Central Jakarta", address: "Jl. M.H. Thamrin No.30, Menteng", priceRange: "$$$", rating: 4.9, reviewCount: 4877, ratingSource: "Google", highlights: ["Authentic Italian osteria", "Strong pizza & pasta", "Curated 70+ wine list"], description: "Authentic Italian osteria with a deep pizza and pasta repertoire, paired with a curated list of 70+ wines from around the world.", sources: [SRC.wlItalian, SRC.wniFineDining] },
  { id: "expatriate-italian", name: "Expatriate Italian Restaurant", cuisine: "Italian", category: "Food", area: "Kelapa Gading, North Jakarta", address: "Jl. Boulevard Raya QF 3 No.11a", priceRange: "$$$", rating: 4.5, reviewCount: 1504, ratingSource: "Google", highlights: ["North Jakarta favourite", "Traditional Italian", "Long-running locals' pick"], description: "Long-running traditional Italian destination in Kelapa Gading, a North Jakarta favourite.", sources: [SRC.wlItalian] },
  { id: "emilia-cucina", name: "Emilia Cucina Italiana", cuisine: "Italian", category: "Food", area: "Kebayoran Lama, South Jakarta", address: "Jl. Biduri Bulan Blok I No.03", priceRange: "$$$", rating: 4.8, reviewCount: 4776, ratingSource: "Google", highlights: ["Highly-rated neighbourhood Italian", "Hand-made pasta", "Hidden-gem energy"], description: "South Jakarta's hidden-gem Italian, consistently among the highest-rated cucinas in town.", sources: [SRC.wlItalian] },
  { id: "rosso", name: "Rosso", cuisine: "Italian", category: "Food & Beverage", area: "Sudirman, Central Jakarta", address: "Shangri-La Jakarta, Jl. Jenderal Sudirman No.Kav.1", priceRange: "$$$$", rating: 4.6, reviewCount: 160, ratingSource: "Google", highlights: ["Shangri-La signature", "Brick-oven pizza", "Italian hotel dining"], description: "Shangri-La Jakarta's signature Italian restaurant — brick-oven pizza, fresh pasta and a glamorous hotel-dining setting.", sources: [SRC.wlItalian] },
  { id: "caffe-milano", name: "Caffe Milano", cuisine: "Italian", category: "Food & Beverage", area: "Thamrin, Central Jakarta", address: "Grand Indonesia East Mall, Jl. M.H. Thamrin No.1", priceRange: "$$", rating: 4.7, reviewCount: 3046, ratingSource: "Google", highlights: ["Casual Italian café", "Mall flagship", "All-day menu"], description: "Casual all-day Italian café inside Grand Indonesia East Mall.", sources: [SRC.wlItalian] },
  { id: "oro-italian", name: "ORO Italian Restaurant", cuisine: "Italian", category: "Food", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya No.2h", priceRange: "$$$", rating: 4.8, reviewCount: 1467, ratingSource: "Google", highlights: ["Kemang fine Italian", "Strong dessert programme", "Premium ingredients"], description: "Polished Italian dining destination in Kemang with one of the area's strongest dessert programmes.", sources: [SRC.wlItalian] },
  { id: "casa-cuomo", name: "Casa Cuomo Ristorante & Lounge", cuisine: "Italian", category: "Food & Beverage", area: "Gunawarman, South Jakarta", address: "Jl. Gunawarman No.57, Kebayoran Baru", priceRange: "$$$", rating: 4.5, reviewCount: 806, ratingSource: "Google", highlights: ["Ristorante + lounge", "Wine programme", "Senopati-adjacent"], description: "Two-in-one Italian ristorante and cocktail lounge on Jl. Gunawarman.", sources: [SRC.wlItalian] },
  { id: "bistecca", name: "Bistecca SCBD", cuisine: "Italian Steakhouse", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "18 Parc Place SCBD Tower C, Jl. Tulodong Atas No.52-53", priceRange: "$$$$", rating: 4.6, reviewCount: 1792, ratingSource: "Google", priceNote: "Premium charcoal-grilled prime cuts", highlights: ["Bistecca Fiorentina (1kg, 45-day aged)", "Italian-American steakhouse", "Classic martini bar"], description: "Italian-American steakhouse by The Union Group with Chef Luca Pezzera. Spectacular cuts of charcoal-grilled prime meats and the signature 1kg 45-day aged Bistecca Fiorentina.", sources: [SRC.wlItalian, SRC.wniFineDining] },
  { id: "bottega", name: "Bottega Ristorante", cuisine: "Italian", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "Fairgrounds SCBD", priceRange: "$$$", rating: 4.5, reviewCount: 1502, ratingSource: "Google", highlights: ["European-style decor", "Diverse pasta menu", "Truffle Tagliolini"], description: "European-style ristorante known for mouthwatering pasta, including Crab Spaghetti, Truffle Tagliolini, and Bacon Mac & Cheese.", sources: [SRC.wlItalian] },
  { id: "alto", name: "Alto Restaurant & Bar", cuisine: "Italian", category: "Food & Beverage", area: "Gatot Subroto, South Jakarta", address: "Four Seasons Hotel Jakarta, Jl. Jend. Gatot Subroto Kav. 18", priceRange: "$$$$", highlights: ["Executive Chef Marco Violano", "Hotel fine dining", "Traditional Italian"], description: "Traditional Italian dishes by Executive Chef Marco Violano inside Four Seasons Hotel Jakarta.", sources: [SRC.wniFineDining] },
  { id: "sicile", name: "Sicile", cuisine: "Italian / Mediterranean", category: "Food & Beverage", area: "Senopati, South Jakarta", priceRange: "$$$", highlights: ["All-day mingle spot", "Italian-Mediterranean", "Steakhouse vibe"], description: "Italian-Mediterranean inspired steakhouse experience in Senopati, operating as an all-day mingle spot.", sources: [SRC.chopeSenopati] },

  // ───────── FRENCH ─────────
  { id: "amuz", name: "AMUZ Gourmet Restaurant", cuisine: "French", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "The Energy Building, SCBD, Jl. Jenderal Sudirman Kav. 52-53", priceRange: "$$$$", rating: 4.6, reviewCount: 476, ratingSource: "Google", highlights: ["Five-course set", "Fine French wines", "Contemporary French"], description: "Contemporary French fine dining with a flagship five-course set including amuse-bouche, starter, two mains and dessert.", sources: [SRC.wlFrench, SRC.wniFineDining] },
  { id: "le-quartier", name: "Le Quartier", cuisine: "French", category: "Food & Beverage", area: "Gunawarman, South Jakarta", address: "Jl. Gunawarman No.34, Kebayoran Baru", priceRange: "$$$", rating: 4.6, reviewCount: 3182, ratingSource: "Google", highlights: ["Parisian brasserie", "Wooden floors & chandelier", "Welcoming neighbourhood feel"], description: "Charming French brasserie evoking Parisian streets — classic decor, wooden floors and a welcoming dining experience.", sources: [SRC.wlFrench] },
  { id: "lyon", name: "Lyon", cuisine: "French", category: "Food & Beverage", area: "Menteng, Central Jakarta", address: "Jl. M.H. Thamrin", priceRange: "$$$$", rating: 4.4, reviewCount: 237, ratingSource: "TripAdvisor", highlights: ["Classic French dining", "Menteng landmark", "Mannerly service"], description: "Classic French dining destination on Jl. M.H. Thamrin in Menteng.", sources: [SRC.wlFrench] },
  { id: "bistro-baron", name: "Bistro Baron", cuisine: "French Bistro", category: "Food & Beverage", area: "Plaza Indonesia, Central Jakarta", address: "Plaza Indonesia, Jl. M.H. Thamrin No.28-30", priceRange: "$$$", rating: 4.4, reviewCount: 482, ratingSource: "Google", highlights: ["Casual French bistro", "Steak frites", "Wine selection"], description: "Casual French bistro at Plaza Indonesia with classic bistro fare and a focused wine selection.", sources: [SRC.wlFrench] },
  { id: "pierre", name: "PIERRE", cuisine: "French", category: "Food & Beverage", area: "Senopati, South Jakarta", address: "Jl. Senopati No.39, Kebayoran Baru", priceRange: "$$$$", rating: 4.7, reviewCount: 1196, ratingSource: "Google", highlights: ["Intimate fine dining", "Traditional French", "Senopati refuge"], description: "Tranquil refuge in Senopati offering traditional French cuisine — an intimate, elegant space removed from the city's hustle.", sources: [SRC.wlFrench] },
  { id: "vk-scbd", name: "VK SCBD (Vong Kitchen)", cuisine: "Modern French", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "Alila SCBD Hotel, Jl. Jend. Sudirman Kav 52-53", priceRange: "$$$$", rating: 4.6, reviewCount: 1808, ratingSource: "Google", highlights: ["Jean-Georges Vongerichten concept", "Modern French", "Hotel destination"], description: "Modern French restaurant inside the Alila SCBD — sister concept to the Jean-Georges Vongerichten group.", sources: [SRC.wlFrench, SRC.wniFineDining] },
  { id: "paul-classic", name: "PAUL Classic Pacific Place", cuisine: "French Bakery & Bistro", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "Pacific Place Mall, Jl. Jenderal Sudirman 52-53", priceRange: "$$", rating: 4.6, reviewCount: 4045, ratingSource: "Google", highlights: ["Heritage French bakery", "All-day bistro", "Mall flagship"], description: "Heritage French bakery and all-day bistro at Pacific Place.", sources: [SRC.wlFrench] },
  { id: "sophie-kemang", name: "Sophie Authentique (Kemang)", cuisine: "French Bistro", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya No.55, South Jakarta", priceRange: "$$$", rating: 4.3, reviewCount: 291, ratingSource: "Google", highlights: ["Authentic French bistro", "Kemang charm", "Pastries & savories"], description: "Authentic French bistro in Kemang, sibling location to the original Sophie outlet.", sources: [SRC.wlFrench] },
  { id: "orient8", name: "Orient8", cuisine: "European / French-Italian", category: "Food & Beverage", area: "Senayan, Central Jakarta", address: "Hotel Mulia Senayan, Jl. Asia Afrika", priceRange: "$$$$", rating: 4.8, reviewCount: 535, ratingSource: "Google", highlights: ["Hotel Mulia signature", "French-Italian", "Open kitchen showpiece"], description: "Hotel Mulia Senayan's flagship European restaurant — French-Italian repertoire with an open-kitchen showpiece.", sources: [SRC.wlFrench] },
  { id: "alice-by-tom-aikens", name: "Alice by Tom Aikens", cuisine: "Modern French", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "District 8 SCBD, Lot 28", priceRange: "$$$$", rating: 4.8, reviewCount: 968, ratingSource: "Google", highlights: ["Michelin chef Tom Aikens", "Modern French", "District 8 destination"], description: "Modern French restaurant from Michelin-starred chef Tom Aikens at District 8 SCBD.", sources: [SRC.wlFrench] },

  // ───────── JAPANESE / NIKKEI ─────────
  { id: "asuka", name: "Asuka Japanese Dining", cuisine: "Japanese (Omakase)", category: "Food", area: "Mega Kuningan, South Jakarta", address: "JW Marriott Jakarta lobby, Kawasan Mega Kuningan", priceRange: "$$$$", rating: 4.8, reviewCount: 266, ratingSource: "TripAdvisor", highlights: ["JW Marriott flagship", "Award-winning omakase", "Sushi & sashimi"], description: "JW Marriott's fine-dining Japanese flagship, an award-winning omakase concept built on fresh, top-grade fish.", sources: [SRC.wlJapanese] },
  { id: "sumire", name: "Sumire Restaurant", cuisine: "Japanese (Teppanyaki)", category: "Food", area: "Tanah Abang, Central Jakarta", address: "Grand Hyatt Jakarta", priceRange: "$$$$", rating: 4.4, reviewCount: 249, ratingSource: "Google", highlights: ["Teppanyaki", "Chirashi", "Grand Hyatt signature"], description: "Grand Hyatt Jakarta's signature Japanese: teppanyaki, chirashi and a full Japanese kitchen.", sources: [SRC.wlJapanese] },
  { id: "okuzono", name: "Okuzono Japanese Dining", cuisine: "Japanese (Izakaya)", category: "Food & Beverage", area: "Senopati, South Jakarta", priceRange: "$$$", rating: 4.6, reviewCount: 2923, ratingSource: "Google", highlights: ["Senopati izakaya favourite", "Sashimi-led menu", "Authentic Japanese"], description: "Authentic Senopati izakaya, repeatedly cited as one of the area's strongest Japanese addresses.", sources: [SRC.wlJapanese] },
  { id: "kahyangan", name: "Kahyangan Japanese Restaurant", cuisine: "Japanese (Shabu-shabu/Teppanyaki)", category: "Food", area: "Thamrin, Central Jakarta", address: "Wisma Nusantara, Jl. M.H. Thamrin", priceRange: "$$$$", rating: 4.6, reviewCount: 265, ratingSource: "Google", highlights: ["Shabu-shabu", "Teppanyaki", "Wagyu beef"], description: "High-rise Japanese specialising in shabu-shabu and teppanyaki, with a strong Wagyu programme.", sources: [SRC.wlJapanese] },
  { id: "oku-jakarta", name: "OKU Jakarta", cuisine: "Modern Japanese", category: "Food & Beverage", area: "Thamrin, Central Jakarta", address: "Hotel Indonesia Kempinski, M.H. Thamrin", priceRange: "$$$$", rating: 4.7, reviewCount: 686, ratingSource: "Google", highlights: ["Chef Kazumasa Yazawa", "Toyosu-sourced fish 2×/week", "Zen-inspired lounge"], description: "Premium modern Japanese in the Kempinski. Chef Kazumasa Yazawa's interpretations rely on fresh seafood imported twice weekly from Toyosu Fish Market in Tokyo.", sources: [SRC.wlJapanese, SRC.wlFineDining] },
  { id: "enmaru", name: "Enmaru Japanese Restaurant", cuisine: "Japanese (Omakase)", category: "Food", area: "Thamrin, Central Jakarta", address: "The Plaza Office Tower, 46th floor, M.H. Thamrin", priceRange: "$$$$", rating: 4.6, reviewCount: 322, ratingSource: "Google", highlights: ["46th-floor views", "Omakase", "Classic Japanese kaiseki"], description: "46th-floor Japanese kaiseki and omakase with sweeping city views from The Plaza Office Tower.", sources: [SRC.wlJapanese, SRC.wniFineDining] },
  { id: "sakana", name: "Sakana Midplaza", cuisine: "Japanese (Izakaya)", category: "Food & Beverage", area: "Tanah Abang, Central Jakarta", address: "Midplaza 1, Basement floor", priceRange: "$$$", rating: 4.5, reviewCount: 891, ratingSource: "Google", highlights: ["Basement izakaya gem", "Authentic Japanese", "Daily fresh fish"], description: "Hidden basement izakaya at Midplaza 1, known for authentic small plates and fresh fish daily.", sources: [SRC.wlJapanese] },
  { id: "keyaki", name: "Keyaki Japanese Restaurant", cuisine: "Japanese (Kyoto)", category: "Food", area: "Thamrin, Central Jakarta", address: "Pan Pacific Jakarta, 90th floor, MH Thamrin", priceRange: "$$$$", rating: 4.4, reviewCount: 81, ratingSource: "Google", highlights: ["90th-floor views", "Kyoto cuisine", "Teppanyaki & buffet"], description: "Sky-high Kyoto-style Japanese at the Pan Pacific, with teppanyaki and lunch buffet.", sources: [SRC.wlJapanese] },
  { id: "nishimura", name: "Nishimura", cuisine: "Japanese (Teppanyaki)", category: "Food", area: "Karet Tengsin, Central Jakarta", address: "Shangri-La Hotel Jakarta", priceRange: "$$$$", rating: 4.5, reviewCount: 116, ratingSource: "TripAdvisor", highlights: ["Teppanyaki theatre", "Traditional Japanese", "Shangri-La signature"], description: "Shangri-La Jakarta's traditional Japanese teppanyaki room.", sources: [SRC.wlJapanese] },
  { id: "marufuku", name: "Marufuku", cuisine: "Japanese (Ramen)", category: "Food", area: "Blok M, South Jakarta", address: "Blok M, Kebayoran Baru", priceRange: "$$", rating: 4.1, reviewCount: 875, ratingSource: "Google", highlights: ["Ramen specialist", "Sushi side menu", "Grilled & steamed dishes"], description: "Casual Blok M Japanese with a ramen focus, plus sushi and grilled/steamed sides.", sources: [SRC.wlJapanese] },
  { id: "kikugawa", name: "Kikugawa Restaurant", cuisine: "Japanese (Traditional)", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. Cikini IV, Menteng", priceRange: "$$", rating: 4.6, reviewCount: 1815, ratingSource: "Google", highlights: ["Historic Menteng spot", "Japanese comfort sets", "Long-running"], description: "Historic Menteng Japanese with the comfort-food sets that built its long-running following.", sources: [SRC.wlJapanese] },
  { id: "sushi-hiro", name: "Sushi Hiro", cuisine: "Japanese (Sushi)", category: "Food", area: "Grogol Petamburan, West Jakarta", address: "Neo Soho Mall", priceRange: "$$", rating: 4.8, reviewCount: 6849, ratingSource: "Google", highlights: ["High-volume favourite", "Fusion rolls", "Fresh seafood"], description: "High-volume sushi favourite at Neo Soho with creative fusion rolls and consistently fresh seafood.", sources: [SRC.wlJapanese] },
  { id: "henshin", name: "Henshin", cuisine: "Nikkei (Japanese-Peruvian)", category: "Food & Beverage", area: "Kuningan, South Jakarta", address: "The Westin Jakarta, Level 67-69 Gama Tower, Jl. H. R. Rasuna Said", priceRange: "$$$$", rating: 4.6, reviewCount: 2354, ratingSource: "Google", highlights: ["Indonesia's highest rooftop bar", "Japanese-Peruvian fusion", "360° skyline views"], description: "Three-floor Nikkei destination atop Gama Tower with Indonesia's highest rooftop bar and 360-degree skyline views.", sources: [SRC.wniFineDining, SRC.wlFineDining] },

  // ───────── CHINESE ─────────
  { id: "twelve-chinese", name: "Twelve Chinese Dining", cuisine: "Chinese", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. Dr. Kusuma Atmaja No.75, Menteng", priceRange: "$$$", rating: 4.6, reviewCount: 1632, ratingSource: "Google", highlights: ["Zodiac-themed concept", "Halal-certified", "Dim sum & roasted duck"], description: "Halal-certified, zodiac-themed Chinese kitchen with reimagined recipes and a Japanese-influenced twist.", sources: [SRC.wlChinese] },
  { id: "li-feng", name: "Li Feng", cuisine: "Chinese (Cantonese)", category: "Food", area: "Thamrin, Central Jakarta", address: "Mandarin Oriental Jakarta, Jl. M.H. Thamrin", priceRange: "$$$$", rating: 4.6, reviewCount: 725, ratingSource: "Google", highlights: ["Mandarin Oriental signature", "Michelin chef collab", "Crispy fish skin"], description: "Mandarin Oriental's signature Cantonese, with Michelin-starred chef collaborations and dishes like crispy fish skin and bamboo lobster.", sources: [SRC.wlChinese, SRC.chopeChinese] },
  { id: "table8", name: "Table8", cuisine: "Chinese (Cantonese/Szechuan)", category: "Food", area: "Senayan, Central Jakarta", address: "Hotel Mulia Jakarta, Jl. Asia Afrika", priceRange: "$$$", rating: 4.9, reviewCount: 2754, ratingSource: "TripAdvisor", highlights: ["All-you-can-eat dim sum", "Buffet-style fusion", "Hotel Mulia destination"], description: "Hotel Mulia's all-you-can-eat dim sum hall, with Cantonese-Szechuan fusion and hakao and shumai on rotation.", sources: [SRC.wlChinese] },
  { id: "pearl", name: "Pearl Chinese Restaurant", cuisine: "Chinese (Cantonese)", category: "Food", area: "Senayan, Central Jakarta", address: "JW Marriott Hotel, Jl. DR. Ide Anak Agung Gde Agung No.1", priceRange: "$$$$", rating: 4.6, reviewCount: 445, ratingSource: "Google", highlights: ["Modern Cantonese", "Peking duck", "Prawn mayonnaise"], description: "Modern Cantonese in a luxury hotel setting — Peking duck, prawn mayonnaise and black-pepper beef are signatures.", sources: [SRC.wlChinese] },
  { id: "taste-paradise", name: "Taste Paradise", cuisine: "Chinese (High-end)", category: "Food", area: "Thamrin, Central Jakarta", address: "Plaza Indonesia South Gate, Jl. M.H. Thamrin No.5", priceRange: "$$$$", rating: 4.6, reviewCount: 993, ratingSource: "Google", highlights: ["High-end dim sum", "Wasabi prawn mayo", "Shark fin soup"], description: "High-end Chinese inside Plaza Indonesia. Book ahead for weekends — dim sum, wasabi prawn mayonnaise and shark fin soup are the menu pillars.", sources: [SRC.wlChinese] },
  { id: "din-tai-fung", name: "Din Tai Fung", cuisine: "Chinese (Taiwanese)", category: "Food", area: "Pantai Indah Kapuk, North Jakarta", address: "Pantjoran PIK, Unit D-02", priceRange: "$$", rating: 4.9, reviewCount: 2025, ratingSource: "Google", highlights: ["Xiao long bao", "Halal chicken substitutes", "Global chain"], description: "Famed Taiwanese chain known worldwide for soup dumplings; PIK outlet offers halal chicken substitutes.", sources: [SRC.wlChinese] },
  { id: "angke", name: "Angke Restaurant — Ketapang", cuisine: "Chinese (Hakka)", category: "Food", area: "Taman Sari, West Jakarta", address: "Jl. Kyai Haji Zainul Arifin", priceRange: "$$", rating: 4.5, reviewCount: 6630, ratingSource: "Google", highlights: ["Operating since 1965", "Hakka specialist", "Multi-floor heritage venue"], description: "Hakka stalwart operating since 1965, sprawling across multiple floors and known for eel with fumak and cereal prawns.", sources: [SRC.wlChinese] },
  { id: "tien-chao", name: "Tien Chao Restaurant", cuisine: "Chinese", category: "Food", area: "Kuningan, South Jakarta", address: "Gran Melia Jakarta, Jl. H. R. Rasuna Said No.Kav X", priceRange: "$$$$", rating: 4.5, reviewCount: 77, ratingSource: "TripAdvisor", highlights: ["Chef Walden Qiang Wei", "Recently revitalised", "Peking duck & dim sum"], description: "Recently revitalised Chinese at Gran Melia, helmed by Chef Walden Qiang Wei.", sources: [SRC.wlChinese] },
  { id: "wong-fu-kie", name: "Wong Fu Kie Hakka", cuisine: "Chinese (Hakka)", category: "Food", area: "Glodok, West Jakarta", address: "Jl. Perniagaan Timur 2 No.22", priceRange: "$$", rating: 4.4, reviewCount: 1283, ratingSource: "Google", highlights: ["Family-run since 1925", "Historic Kota Tua", "Hakka noodles"], description: "Family-run Hakka specialist operating since 1925 in historic Kota Tua.", sources: [SRC.wlChinese] },
  { id: "trio", name: "Restoran Trio", cuisine: "Chinese (Cantonese)", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. RP. Soeroso No.29A, Gondangdia", priceRange: "$$", rating: 4.4, reviewCount: 1112, ratingSource: "Google", highlights: ["Established 1947", "100+ menu items", "Authentic Cantonese"], description: "Legendary Menteng Cantonese operating since 1947, with a 100+ item menu including signature lumpia udang and gohyong.", sources: [SRC.wlChinese] },
  { id: "paradise-dynasty", name: "Paradise Dynasty", cuisine: "Chinese (Northern/Southern fusion)", category: "Food", area: "Multiple branches", priceRange: "$$$", rating: 4.3, reviewCount: 667, ratingSource: "Google", highlights: ["8-flavoured xiao long bao", "Foie gras dumplings", "Northern + Southern menu"], description: "Modern take on Northern and Southern Chinese cuisine, famous for 8-flavoured xiao long bao and foie-gras-stuffed variants.", sources: [SRC.wlChinese] },
  { id: "li-lian", name: "Li Lian", cuisine: "Chinese", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "Park Hyatt Jakarta, Level 19", priceRange: "$$$$", highlights: ["Park Hyatt flagship", "Skyline views", "Refined Chinese"], description: "Park Hyatt Jakarta's first Chinese restaurant on Level 19, with refined Chinese plates and skyline views.", sources: [SRC.chopeChinese] },
  { id: "canton-108", name: "Canton 108", cuisine: "Chinese (Cantonese)", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "District 8, SCBD", priceRange: "$$$", highlights: ["Elevated Cantonese", "SCBD destination", "Authentic recipes"], description: "District 8 SCBD honouring Chinese authenticity with elevated dining.", sources: [SRC.chopeChinese] },

  // ───────── KOREAN ─────────
  { id: "bornga", name: "Bornga", cuisine: "Korean BBQ", category: "Food", area: "Senopati, South Jakarta", address: "Jl. Wolter Monginsidi No.24, Petogogan, Kebayoran Baru", priceRange: "$$$", rating: 4.7, reviewCount: 2138, ratingSource: "Google", highlights: ["Korean BBQ favourite", "Premium cuts", "Senopati flagship"], description: "One of Jakarta's most popular Korean BBQ houses, offering fresh, high-quality cuts.", sources: [SRC.wlKorean] },
  { id: "chung-gi-wa", name: "Chung Gi Wa", cuisine: "Korean", category: "Food", area: "Pulo, South Jakarta", address: "Jl. Wijaya II No.118-119, Kebayoran Baru", priceRange: "$$$", rating: 4.4, reviewCount: 1974, ratingSource: "Google", highlights: ["Long-running Korean", "Hanok-style dining", "Korean BBQ + classics"], description: "Long-running South Jakarta Korean with hanok-style dining and a full Korean menu beyond just BBQ.", sources: [SRC.wlKorean] },
  { id: "gahyo", name: "Gahyo Korean BBQ", cuisine: "Korean BBQ", category: "Food", area: "Blok M, South Jakarta", address: "Jl. Melawai Raya No.109, 3rd & 4th floor, Kebayoran Baru", priceRange: "$$$", rating: 4.5, reviewCount: 268, ratingSource: "Google", highlights: ["Operating since 2005", "Daechang specialty", "Teuk Nyang Nyeum"], description: "Korean BBQ operating since 2005 with signature Daechang (marinated large intestine) and Teuk Nyang Nyeum.", sources: [SRC.wlKorean] },
  { id: "tobak", name: "Tobak Korean Restaurant", cuisine: "Korean", category: "Food", area: "Senopati, South Jakarta", address: "Jl. Wolter Monginsidi No.30, Petogogan", priceRange: "$$$", rating: 4.5, reviewCount: 1411, ratingSource: "Google", highlights: ["Senopati Korean", "Hot stone bibimbap", "Reliable Korean staples"], description: "Senopati Korean reliable for hot stone bibimbap and standard Korean staples.", sources: [SRC.wlKorean] },
  { id: "samwon-house", name: "SamWon House", cuisine: "Korean", category: "Food", area: "Kuningan, South Jakarta", address: "Jl. Setiabudi Selatan Raya No.2", priceRange: "$$", rating: 4.1, reviewCount: 538, ratingSource: "Google", highlights: ["Casual Korean", "Strong banchan", "Lunch sets"], description: "Casual Korean canteen in Kuningan with strong banchan and lunch sets.", sources: [SRC.wlKorean] },
  { id: "legend-of-noodle", name: "Legend of Noodle", cuisine: "Korean (Noodles)", category: "Food", area: "Senopati, South Jakarta", address: "Jl. Senopati No.81, Selong, Kebayoran Baru", priceRange: "$$", rating: 4.6, reviewCount: 4305, ratingSource: "Google", highlights: ["Hand-pulled noodles", "Senopati institution", "Korean comfort food"], description: "Senopati institution famous for hand-pulled Korean noodles and comfort dishes.", sources: [SRC.wlKorean] },
  { id: "samwon-garden", name: "Samwon Garden Korean BBQ", cuisine: "Korean BBQ", category: "Food", area: "Kuningan, South Jakarta", address: "Lotte Mall Kuningan, 5th Floor, Jl. Prof. DR. Satrio No.18", priceRange: "$$$", rating: 4.5, reviewCount: 525, ratingSource: "Google", highlights: ["Mall destination", "Premium grill", "Korean side spreads"], description: "Premium grill room inside Lotte Mall Kuningan with the full Korean side spread.", sources: [SRC.wlKorean] },
  { id: "ojju", name: "Ojju", cuisine: "Korean (Cheesy)", category: "Food", area: "Casablanca, South Jakarta", address: "Jl. Raya Casablanca No.88, Unit FSU-35", priceRange: "$$", rating: 4.6, reviewCount: 4342, ratingSource: "Google", highlights: ["Korean cheese spreads", "K-pop crowd", "Strong reviews"], description: "Mall Korean famous for cheese-laden mains; a magnet for the K-pop crowd.", sources: [SRC.wlKorean] },
  { id: "cheongdam-garden", name: "Cheongdam Garden Senopati", cuisine: "Korean BBQ", category: "Food & Beverage", area: "Senopati, South Jakarta", address: "Jl. Senopati No.43C", priceRange: "$$$$", rating: 4.6, reviewCount: 2206, ratingSource: "Google", highlights: ["Premium Korean BBQ", "Senopati destination", "Wagyu options"], description: "Senopati destination for premium Korean BBQ with Wagyu and choice cuts.", sources: [SRC.wlKorean] },
  { id: "mr-park", name: "Mr. Park Korean BBQ Grill", cuisine: "Korean BBQ", category: "Food", area: "SCBD, South Jakarta", address: "SCBD Lot Jl. Tulodong Atas 2 No.8F", priceRange: "$$$", rating: 4.5, reviewCount: 1480, ratingSource: "Google", highlights: ["SCBD favourite", "Marinated cuts", "Banchan rotation"], description: "SCBD Korean BBQ favourite with marinated cuts and a deep banchan rotation.", sources: [SRC.wlKorean] },
  { id: "seo-seo-galbi", name: "Seo Seo Galbi PIK", cuisine: "Korean BBQ", category: "Food", area: "PIK, North Jakarta", address: "Ruko Crown Golf Blok A No.31, Pantai Indah Kapuk", priceRange: "$$$", rating: 4.7, reviewCount: 2165, ratingSource: "Google", highlights: ["PIK Korean BBQ", "Galbi specialist", "Highly-rated"], description: "PIK Korean BBQ specialist with a galbi-led grill menu and strong reviews.", sources: [SRC.wlKorean] },
  { id: "mapo-galmaegi", name: "Mapo Galmaegi (Magal BBQ Puri)", cuisine: "Korean BBQ", category: "Food", area: "Kembangan, West Jakarta", address: "Jl. Taman Aries No.3D", priceRange: "$$$", rating: 4.4, reviewCount: 1278, ratingSource: "Google", highlights: ["West Jakarta Korean BBQ", "Pork-belly focus", "Korean staples"], description: "West Jakarta Korean BBQ with a pork-belly focus and full Korean menu support.", sources: [SRC.wlKorean] },
  { id: "yongdaeri", name: "Yongdaeri Korean BBQ", cuisine: "Korean BBQ", category: "Food", area: "SCBD, South Jakarta", priceRange: "$$$", rating: 4.6, reviewCount: 1572, ratingSource: "Google", highlights: ["SCBD Korean BBQ", "Strong meat program", "Casual atmosphere"], description: "Casual but highly-rated Korean BBQ in the SCBD area.", sources: [SRC.wlKorean] },

  // ───────── THAI ─────────
  { id: "chandara", name: "Chandara Fine Thai Cuisine", cuisine: "Thai", category: "Food & Beverage", area: "Senayan, Central Jakarta", address: "Plaza Senayan Mall, Jl. Asia Afrika No.3", priceRange: "$$$", rating: 4.5, reviewCount: 684, ratingSource: "Google", highlights: ["Head chef 15+ years experience", "Fine dining Thai", "Multiple branches"], description: "Fine dining Thai with a head chef bringing 15+ years of expertise. Plaza Senayan and Plaza Indonesia branches present an immersive Thai ambience.", sources: [SRC.wlThai] },
  { id: "santhai", name: "Santhai", cuisine: "Thai", category: "Food", area: "Casablanca, South Jakarta", address: "Jl. Raya Casablanca No.88, Unit No.28", priceRange: "$$$", rating: 4.4, reviewCount: 1194, ratingSource: "Google", highlights: ["Wagyu beef", "Fish skin with salted egg", "Modern Thai"], description: "Modern Thai dining frequently praised for its Wagyu beef and fish skin with salted egg.", sources: [SRC.wlThai] },
  { id: "jittlada-gi", name: "Jittlada Thai Cuisine — Grand Indonesia", cuisine: "Thai", category: "Food", area: "Thamrin, Central Jakarta", address: "Grand Indonesia, Jl. M.H. Thamrin", priceRange: "$$$", rating: 4.6, reviewCount: 1069, ratingSource: "Google", highlights: ["Long-running Thai", "Curries & stir-fries", "Mall destination"], description: "Long-running Thai destination at Grand Indonesia, dependable for curries and stir-fries.", sources: [SRC.wlThai] },
  { id: "tamnak-thai", name: "Tamnak Thai Restaurant", cuisine: "Thai", category: "Food", area: "Menteng, Central Jakarta", address: "Menteng Central, Jl. HOS. Cokroaminoto No.78-80", priceRange: "$$$", rating: 4.5, reviewCount: 722, ratingSource: "Google", highlights: ["Authentic Thai", "Tom yum & green curry", "Menteng Central"], description: "Authentic Thai at Menteng Central, with tom yum, green curry and other classics covered.", sources: [SRC.wlThai] },
  { id: "jittlada-sc", name: "Jittlada Thai Cuisine — Senayan City", cuisine: "Thai", category: "Food", area: "Senayan, Central Jakarta", address: "Senayan City, Jl. Asia Afrika No.2", priceRange: "$$$", rating: 4.6, reviewCount: 851, ratingSource: "Google", highlights: ["Senayan City branch", "Thai classics", "Reliable Thai"], description: "Senayan City branch of the reliable Jittlada Thai group.", sources: [SRC.wlThai] },
  { id: "jittlada-kk", name: "Jittlada Thai Cuisine — Kota Kasablanka", cuisine: "Thai", category: "Food", area: "Casablanca, South Jakarta", address: "Kota Kasablanka, Jl. Raya Casablanca No.88", priceRange: "$$$", rating: 4.6, reviewCount: 776, ratingSource: "Google", highlights: ["Kota Kasablanka branch", "Thai classics", "Mall destination"], description: "Kota Kasablanka branch of Jittlada Thai, popular with the office lunch crowd.", sources: [SRC.wlThai] },
  { id: "so-thai", name: "So Thai by Chandara", cuisine: "Thai (Casual)", category: "Food", area: "Thamrin, Central Jakarta", address: "Plaza Indonesia, Jl. M.H. Thamrin No.30", priceRange: "$$", rating: 4.7, reviewCount: 882, ratingSource: "Google", highlights: ["Casual sister to Chandara", "Pad Thai & boat noodles", "Highly-rated"], description: "Chandara's casual sister: pad Thai, boat noodles and other accessible Thai dishes.", sources: [SRC.wlThai] },
  { id: "larb", name: "Larb Thai Cuisine", cuisine: "Thai", category: "Food", area: "PIK, North Jakarta", address: "Jl. Mandara Permai VII", priceRange: "$$", rating: 4.3, reviewCount: 751, ratingSource: "Google", highlights: ["Northern Thai larb", "Casual Thai", "PIK setting"], description: "Casual North Jakarta Thai with strong larb and a comfortable PIK setting.", sources: [SRC.wlThai] },
  { id: "greyhound-menteng", name: "Greyhound Cafe Menteng", cuisine: "Thai (Modern)", category: "Food & Beverage", area: "Menteng, Central Jakarta", address: "Jl. Sunda No.5", priceRange: "$$$", rating: 4.6, reviewCount: 838, ratingSource: "Google", highlights: ["Bangkok import", "Modern Thai cafe", "Brunch favourite"], description: "Bangkok-born café concept landed in Menteng, with a modern Thai menu and brunch standards.", sources: [SRC.wlThai] },

  // ───────── VIETNAMESE ─────────
  { id: "do-an-menteng", name: "Do An Vietnamese — Menteng Central", cuisine: "Vietnamese", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. HOS. Cokroaminoto No.78, Menteng Central", priceRange: "$$", rating: 4.7, reviewCount: 857, ratingSource: "Google", highlights: ["Vibrant Vietnamese", "Pho, spring rolls, banh mi", "Top-rated branch"], description: "Vibrant Vietnamese restaurant serving traditional dishes with abundant spices — pho, spring rolls, banh mi and salads.", sources: [SRC.wlVietnamese, SRC.wniViet] },
  { id: "yeu-saigon", name: "Yeu Saigon Cafe — Gran Rubina", cuisine: "Vietnamese", category: "Food & Beverage", area: "Kuningan, South Jakarta", address: "Generali Tower, Grand Rubina Business Park, Rasuna Epicentrum", priceRange: "$$", rating: 4.7, reviewCount: 1247, ratingSource: "Google", highlights: ["Vietnamese coffee", "Pho & banh", "Regional Vietnamese menu"], description: "Vietnamese specialties spanning regional dishes, pho, banh and a strong Vietnamese coffee programme.", sources: [SRC.wlVietnamese, SRC.wniViet] },
  { id: "saigon-delight", name: "Saigon Delight", cuisine: "Vietnamese", category: "Food", area: "Multiple branches", address: "Bellagio, Grand Indonesia, Lippo Mall Puri, Gandaria City", priceRange: "$$", rating: 4.6, reviewCount: 1888, ratingSource: "Google", highlights: ["MSG-free", "Organic garden", "Rich beef pho"], description: "Multi-branch Vietnamese serving pho with a richly developed beef broth, no MSG, and fresh ingredients from its own organic garden.", sources: [SRC.wlVietnamese, SRC.wniViet] },
  { id: "pho-street-puri", name: "Pho Street — Lippo Mall Puri", cuisine: "Vietnamese", category: "Food", area: "Puri, West Jakarta", address: "Lippo Mall Puri, 1st floor unit 10", priceRange: "$$", rating: 4.7, reviewCount: 301, ratingSource: "Google", highlights: ["Pho specialist", "Banh mi", "Mall casual"], description: "Mall casual Vietnamese with a clean pho-and-banh-mi menu at Lippo Mall Puri.", sources: [SRC.wlVietnamese] },
  { id: "monviet", name: "MonViet", cuisine: "Vietnamese", category: "Food", area: "Sudirman, Central Jakarta", address: "Setiabudi One / fX Sudirman", priceRange: "$$", rating: 4.3, reviewCount: 91, ratingSource: "Google", highlights: ["Casual Vietnamese", "Pho & banh mi", "Multiple CBD branches"], description: "Casual Vietnamese with pho, banh mi and rice plates across CBD branches.", sources: [SRC.wlVietnamese] },
  { id: "madame-mai", name: "Madame Mai", cuisine: "Vietnamese", category: "Food", area: "Pluit, North Jakarta", address: "Jl. Pluit Indah No.1 Lt.1-111E", priceRange: "$$$", rating: 4.9, reviewCount: 1353, ratingSource: "Google", highlights: ["Highly-rated", "Pluit destination", "Vietnamese fine-casual"], description: "Polished Vietnamese in Pluit, with one of the highest user ratings on this list.", sources: [SRC.wlVietnamese] },
  { id: "pho-24", name: "Pho 24", cuisine: "Vietnamese (Pho chain)", category: "Food", area: "Multiple branches", address: "Lotte Shopping Avenue, Pacific Place, Citywalk Sudirman, Grand Indonesia", priceRange: "$$", rating: 4.3, reviewCount: 510, ratingSource: "Google", highlights: ["Pho chain", "Reliable broth", "Mall-friendly"], description: "Multi-branch Vietnamese pho chain — reliable broths and a familiar menu across major Jakarta malls.", sources: [SRC.wlVietnamese] },
  { id: "madame-ching", name: "Madame Ching", cuisine: "Vietnamese", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. Surabaya No.24, Menteng", priceRange: "$$", rating: 4.4, reviewCount: 1250, ratingSource: "Google", highlights: ["Banh mi sandwiches", "Pho soups", "Menteng staple"], description: "Menteng staple combining a deli concept with Vietnamese classics — banh mi, pho and rice plates.", sources: [SRC.wlVietnamese] },
  { id: "namnam", name: "NamNam Noodle Bar", cuisine: "Vietnamese", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. M.H. Thamrin No.28-30", priceRange: "$$", rating: 4.3, reviewCount: 245, ratingSource: "Google", highlights: ["Singapore import", "Pho & rice plates", "Casual noodle bar"], description: "Singapore-origin Vietnamese noodle bar landed at Plaza Indonesia.", sources: [SRC.wlVietnamese] },
  { id: "do-an-cilandak", name: "Do An Vietnamese — Cilandak", cuisine: "Vietnamese", category: "Food", area: "Cilandak, South Jakarta", address: "Jl. Cilandak Tengah Raya No.87", priceRange: "$$", rating: 4.6, reviewCount: 307, ratingSource: "Google", highlights: ["Cilandak Do An branch", "Banh mi & pho", "South Jakarta access"], description: "South Jakarta branch of the Do An Vietnamese group.", sources: [SRC.wlVietnamese] },
  { id: "banh-banh", name: "Banh Banh", cuisine: "Vietnamese", category: "Food", area: "Kuningan, South Jakarta", address: "Jl. Prof. DR. Satrio No.18", priceRange: "$$", rating: 4.4, reviewCount: 46, ratingSource: "Google", highlights: ["Banh mi specialist", "Vietnamese coffee", "Newer concept"], description: "Newer Vietnamese concept specialising in banh mi and Vietnamese coffee.", sources: [SRC.wlVietnamese] },

  // ───────── MEXICAN / LATIN ─────────
  { id: "taco-local", name: "Taco Local", cuisine: "Mexican", category: "Food", area: "Senopati, South Jakarta", address: "Wijaya Grand Centre, Blok. Alea No.15-16, Kebayoran Baru", priceRange: "$$", rating: 4.5, reviewCount: 276, ratingSource: "Google", highlights: ["Al Pastor Taco", "Burrito Lengua", "Carnitas Quesadilla"], description: "Authentic Mexican on Wijaya — Al Pastor tacos, Burrito Lengua and Carnitas Quesadilla.", sources: [SRC.wlMexican] },
  { id: "amigos", name: "Amigos Bar & Cantina Kemang", cuisine: "Mexican / Tex-Mex", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Kemang Club Villas, Jl. Kemang Selatan I", priceRange: "$$$", rating: 4.5, reviewCount: 2457, ratingSource: "Google", priceNote: "~Rp 500,000 for two (incl. drinks)", highlights: ["Operating since 1979", "Live bands 5 nights/week", "Friday Latin Night"], description: "Long-running Jakarta institution (since 1979). Classic American and Tex-Mex menus, fresh salsa, famous margaritas, live bands and Friday Latin Night.", sources: [SRC.wlMexican] },
  { id: "taco-bell-senopati", name: "Taco Bell Senopati", cuisine: "Mexican (QSR)", category: "Food", area: "Senopati, South Jakarta", address: "Jl. Senopati No.96, Kebayoran Baru", priceRange: "$", rating: 4.4, reviewCount: 3589, ratingSource: "Google", highlights: ["Mexican fast food", "Crunchwraps & burritos", "All-day"], description: "Indonesian flagship of the global Mexican fast-food chain — crunchwraps, burritos and quesadillas.", sources: [SRC.wlMexican] },
  { id: "chileco", name: "Chileco Mexican Grill", cuisine: "Mexican", category: "Food", area: "Kuningan, South Jakarta", address: "WTC2 LG Floor, Jl. Jendral Sudirman Kav 29", priceRange: "$$", rating: 4.6, reviewCount: 112, ratingSource: "Google", highlights: ["Office-lunch Mexican", "Build-your-own bowls", "Fresh salsas"], description: "Office-tower Mexican grill — build-your-own bowls and tacos with fresh salsas.", sources: [SRC.wlMexican] },
  { id: "el-asador", name: "El Asador South American Restaurant", cuisine: "South American / Argentinian", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Kemang Point Building Ground Floor, Jl. Kemang Raya No.3", priceRange: "$$$", rating: 4.5, reviewCount: 1459, ratingSource: "Google", highlights: ["Argentinian grill", "Premium steaks", "South American wines"], description: "Argentinian grill and Latin wine list with a serious commitment to premium cuts.", sources: [SRC.wlAmerican, SRC.wlMexican] },
  { id: "bearrito", name: "Bearrito", cuisine: "Mexican", category: "Food", area: "Bintaro, South Jakarta", address: "Jl. Bintaro Tengah No.35 Blok N2, Pesanggrahan", priceRange: "$$", rating: 4.6, reviewCount: 295, ratingSource: "Google", highlights: ["Burritos & quesadillas", "Bintaro favourite", "Casual Mexican"], description: "Casual Bintaro Mexican focused on burritos, quesadillas and California-style fillings.", sources: [SRC.wlMexican] },
  { id: "carbon", name: "Carbón", cuisine: "Latin / Mexican", category: "Food & Beverage", area: "Setiabudi, South Jakarta", address: "MD Place 11th Floor, Jl. Setia Budi Selatan No.7", priceRange: "$$$$", rating: 4.8, reviewCount: 711, ratingSource: "Google", highlights: ["Open-fire Latin grill", "Strong cocktails", "Highly-rated"], description: "MD Place open-fire Latin grill with one of the highest ratings on this list.", sources: [SRC.wlMexican] },

  // ───────── INDIAN ─────────
  { id: "royal-kitchen", name: "The Royal Kitchen", cuisine: "Indian", category: "Food", area: "Kuningan, South Jakarta", address: "Bellagio Mall, Jl. Mega Kuningan Barat", priceRange: "$$$", rating: 4.4, reviewCount: 1621, ratingSource: "Google", highlights: ["Royal Indian decor", "Tandoor + curries", "Fine Indian dining"], description: "Fine Indian dining in the heart of Kuningan, with royal-themed interiors, soft lighting and a full tandoor menu.", sources: [SRC.wlIndian] },
  { id: "queens-tandoor", name: "Queen's Tandoor", cuisine: "Indian", category: "Food", area: "Thamrin, Central Jakarta", address: "Plaza Bank Index, Jl. M.H. Thamrin", priceRange: "$$$", rating: 4.3, reviewCount: 1862, ratingSource: "Google", highlights: ["Established 1986", "Tandoor specialist", "Authentic spices"], description: "Tradition-rich Indian restaurant established 1986, with authentic tandoor and traditional ambience.", sources: [SRC.wlIndian, SRC.wlEuropean] },
  { id: "ganesha-ek-sanskriti", name: "Ganesha Ek Sanskriti", cuisine: "Indian", category: "Food", area: "Sudirman, South Jakarta", address: "Gedung BRI II, Center Park, Jl. Jenderal Sudirman", priceRange: "$$$", rating: 4.4, reviewCount: 1005, ratingSource: "Google", highlights: ["North & South Indian", "Tandoor + curries", "CBD office lunches"], description: "Sudirman Indian covering both North and South Indian cooking, popular for CBD lunches.", sources: [SRC.wlIndian] },
  { id: "fez-kinara", name: "Fez-Kinara Dining & Lounge", cuisine: "Indian / Maghreb / Middle Eastern", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya 78B", priceRange: "$$$", rating: 4.4, reviewCount: 1162, ratingSource: "Google", highlights: ["Indian + Maghreb + Gulf", "Cross-regional menu", "Kemang lounge"], description: "Cross-regional menu spanning Indian, Maghreb and Gulf cuisines in a Kemang lounge setting.", sources: [SRC.wlIndian, SRC.wniME] },
  { id: "babooji", name: "Babooji", cuisine: "Indian", category: "Food", area: "Gunawarman, South Jakarta", address: "Jl. Gunawarman No.61", priceRange: "$$$", rating: 4.3, reviewCount: 579, ratingSource: "Google", highlights: ["Modern Indian", "Senopati-adjacent", "Cocktail-led drinks"], description: "Modern Indian close to Senopati with a cocktail-led drinks programme.", sources: [SRC.wlIndian] },
  { id: "udupi-shree-krishna", name: "Udupi Shree Krishna", cuisine: "Indian (South Indian Vegetarian)", category: "Food", area: "Kemayoran, Central Jakarta", address: "Tower Akasia, Taman Kemayoran", priceRange: "$$", rating: 4.7, reviewCount: 1592, ratingSource: "Google", highlights: ["South Indian veg specialist", "Dosa & idli", "Highly-rated"], description: "Highly-rated South Indian vegetarian specialist in Kemayoran — dosa, idli and full thali sets.", sources: [SRC.wlIndian] },
  { id: "udupi-delicious", name: "Udupi Delicious", cuisine: "Indian (South Indian Vegetarian)", category: "Food", area: "Kemayoran, Central Jakarta", address: "Tower Flamboyan, Jl. Benyamin Suaeb", priceRange: "$$", rating: 4.7, reviewCount: 1467, ratingSource: "Google", highlights: ["South Indian veg", "Dosa & uttapam", "Vegetarian-friendly"], description: "Sister concept to Udupi Shree Krishna with strong dosa and uttapam.", sources: [SRC.wlIndian] },
  { id: "zanas", name: "Zanas Indian Fusion Cuisine", cuisine: "Indian (Fusion)", category: "Food", area: "Kemayoran, Central Jakarta", address: "Kondominium Taman Kemayoran Tower Eboni", priceRange: "$$", rating: 4.5, reviewCount: 605, ratingSource: "Google", highlights: ["Indian fusion", "Casual setting", "Crossover dishes"], description: "Indian-fusion concept with crossover dishes in a casual Kemayoran setting.", sources: [SRC.wlIndian] },
  { id: "d-bollywood", name: "D' Bollywood", cuisine: "Indian", category: "Food & Beverage", area: "Kuningan, South Jakarta", address: "Plaza Festival, Jl. H. R. Rasuna Said No.22", priceRange: "$$$", rating: 4.3, reviewCount: 414, ratingSource: "Google", highlights: ["Bollywood-themed", "Tandoor + curries", "Live nights"], description: "Bollywood-themed Indian with live nights and a tandoor-led menu.", sources: [SRC.wlIndian] },
  { id: "lan-na-thai-hazara", name: "Lan Na Thai & Hazara", cuisine: "Indian / Thai", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "Jl. Tulodong Bawah No. D-1", priceRange: "$$$", rating: 4.4, reviewCount: 455, ratingSource: "Google", highlights: ["Indian + Thai under one roof", "Garden setting", "Sister concepts"], description: "Two sister concepts — Lan Na (Thai) and Hazara (Indian) — sharing a garden-style space in SCBD.", sources: [SRC.wlIndian] },

  // ───────── MIDDLE EASTERN / LEBANESE / TURKISH ─────────
  { id: "al-nafoura", name: "Al Nafoura Lebanese Restaurant", cuisine: "Lebanese", category: "Food & Beverage", area: "Sudirman, Central Jakarta", address: "Le Méridien Jakarta, Jl. Jenderal Sudirman Kav.18-20", priceRange: "$$$", rating: 4.4, reviewCount: 1205, ratingSource: "Google", highlights: ["Two-level Lebanese setting", "From-scratch kitchen", "Mezze & grills"], description: "Two spacious levels of Lebanese design and cuisine at Le Méridien Jakarta — every dish made from scratch.", sources: [SRC.wlMiddleEastern, SRC.wniME] },
  { id: "turkuaz", name: "Turkuaz Restaurant", cuisine: "Turkish / Ottoman", category: "Food & Beverage", area: "Gunawarman, South Jakarta", address: "Jl. Ciranjang No.40, Kebayoran Baru", priceRange: "$$$", rating: 4.4, reviewCount: 1465, ratingSource: "Google", highlights: ["Chef Sezai Zorlu (Iron Chef Indonesia)", "Authentic Ottoman cuisine", "Mediterranean ambience"], description: "Authentic Turkish and Ottoman cuisine helmed by celebrity Chef Sezai Zorlu.", sources: [SRC.wlMiddleEastern, SRC.wniME] },
  { id: "abunawas", name: "Abunawas Restaurant — Matraman", cuisine: "Middle Eastern (Arabic)", category: "Food", area: "Matraman, East Jakarta", address: "Jl. Matraman Raya No.15", priceRange: "$$", rating: 4.5, reviewCount: 3861, ratingSource: "Google", highlights: ["Long-running Arabic", "Mandi rice & grills", "Family-friendly"], description: "Long-running Arabic restaurant in Matraman, popular for mandi rice and mixed grills.", sources: [SRC.wlMiddleEastern] },
  { id: "al-jazeerah", name: "Al Jazeerah Signature Restaurant & Lounge", cuisine: "Middle Eastern", category: "Food & Beverage", area: "Menteng, Central Jakarta", address: "Jl. Johar No.8, Kebon Sirih", priceRange: "$$$", rating: 4.5, reviewCount: 7618, ratingSource: "Google", highlights: ["7,000+ reviews", "Signature lounge", "Halal kitchen"], description: "Highly-trafficked Middle Eastern destination in Menteng with a signature lounge and 7,000+ reviews.", sources: [SRC.wlMiddleEastern] },
  { id: "hadramout", name: "Hadramout Arabic Restaurant", cuisine: "Middle Eastern (Arabic)", category: "Food", area: "Menteng, Central Jakarta", address: "Jl. Tambak No.16A, Pegangsaan", priceRange: "$$", rating: 4.4, reviewCount: 3974, ratingSource: "Google", highlights: ["Yemeni-Arabic", "Mandi specialist", "Communal portions"], description: "Yemeni-style Arabic restaurant in Menteng, famous for mandi served in communal portions.", sources: [SRC.wlMiddleEastern] },
  { id: "larazeta", name: "LARAZETA Restaurant and Grill", cuisine: "Middle Eastern", category: "Food", area: "Tebet, South Jakarta", address: "Jl. Tebet Barat Dalam Raya No.17", priceRange: "$$", rating: 4.4, reviewCount: 1670, ratingSource: "Google", highlights: ["Multi-country Middle Eastern", "Yemen to Morocco", "Casual grill"], description: "Casual grill spanning Middle Eastern dishes from Yemen, Lebanon, Egypt, Syria, Morocco and Turkey.", sources: [SRC.wlMiddleEastern, SRC.wniME] },
  { id: "ajwad", name: "Ajwad Resto", cuisine: "Middle Eastern", category: "Food", area: "Kramat Jati, East Jakarta", address: "Jl. Raya Condet No.50, Batu Ampar", priceRange: "$$", rating: 4.7, reviewCount: 7903, ratingSource: "Google", highlights: ["East Jakarta favourite", "Arabic grills", "Condet destination"], description: "East Jakarta Middle Eastern with one of the higher review counts in the city — Arabic grills and mandi.", sources: [SRC.wlMiddleEastern] },
  { id: "warung-turki", name: "Warung Turki", cuisine: "Turkish", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya No.18A, Mampang Prapatan", priceRange: "$$", rating: 4.4, reviewCount: 1170, ratingSource: "Google", highlights: ["Shisha lounge", "Operating since 2015", "Chef Sezai Zorlu's casual concept"], description: "Chef Sezai Zorlu's casual Turkish spot in Kemang, operating as a shisha lounge since 2015.", sources: [SRC.wlMiddleEastern, SRC.wniME] },
  { id: "alsadda", name: "Alsadda Restaurant", cuisine: "Middle Eastern (Arabic)", category: "Food", area: "Jatinegara, East Jakarta", address: "Jl. Otto Iskandardinata No.70/30", priceRange: "$$", rating: 4.5, reviewCount: 2814, ratingSource: "Google", highlights: ["East Jakarta institution", "Mandi & kabsa", "Family-style"], description: "Long-running East Jakarta Middle Eastern, known for mandi and kabsa in family-style portions.", sources: [SRC.wlMiddleEastern] },
  { id: "al-mukalla", name: "Rumah Makan Al Mukalla", cuisine: "Middle Eastern (Yemeni-Arabic)", category: "Food", area: "Kramat Jati, East Jakarta", address: "Jl. Raya Condet No.30, Balekambang", priceRange: "$$", rating: 4.5, reviewCount: 1183, ratingSource: "Google", highlights: ["Yemeni-Arabic", "Mandi specialist", "Condet local"], description: "Condet local with strong Yemeni-Arabic mandi and grills.", sources: [SRC.wlMiddleEastern] },

  // ───────── SPANISH ─────────
  { id: "caspar", name: "Caspar Jakarta", cuisine: "Spanish", category: "Food & Beverage", area: "Bendungan Hilir, Central Jakarta", address: "Jl. Jend. Sudirman No.36, Tanah Abang", priceRange: "$$$", rating: 4.6, reviewCount: 1754, ratingSource: "Google", highlights: ["Spanish tapas", "Strong bar program", "Buzzy CBD spot"], description: "Buzzy CBD Spanish destination with a strong tapas menu and bar programme.", sources: [SRC.wlSpanish, SRC.wlEuropean] },
  { id: "txoko", name: "Txoko Jakarta", cuisine: "Spanish (Basque)", category: "Food & Beverage", area: "Senopati, South Jakarta", address: "Jl. Suryo No.6", priceRange: "$$$", rating: 4.7, reviewCount: 1390, ratingSource: "Google", highlights: ["Basque-style txoko", "Pintxos & wine", "Senopati neighborhood spot"], description: "Basque-style txoko in Senopati — pintxos, wines and a tight neighbourhood feel.", sources: [SRC.wlSpanish] },
  { id: "plan-b-spanish", name: "Plan B Spanish Resto", cuisine: "Spanish", category: "Food", area: "Kebayoran Lama, South Jakarta", address: "Jl. Tentara Pelajar Blok D No.25", priceRange: "$$", rating: 4.6, reviewCount: 0, ratingSource: "Google", highlights: ["Casual Spanish", "Paella & tapas", "Neighbourhood spot"], description: "Casual Spanish neighbourhood spot focused on paella and tapas classics.", sources: [SRC.wlSpanish] },
  { id: "basque-tapas", name: "Basque Bar de Tapas", cuisine: "Spanish (Basque)", category: "Food & Beverage", area: "Mega Kuningan, South Jakarta", address: "Noble House 8th Floor, Mega Kuningan", priceRange: "$$$", rating: 4.5, reviewCount: 2806, ratingSource: "Google", highlights: ["Basque tapas", "Strong wines", "Mega Kuningan tower"], description: "Basque tapas with a serious wine list, perched on the 8th floor of Noble House.", sources: [SRC.wlSpanish] },
  { id: "nidcielo", name: "Nidcielo", cuisine: "Spanish (Modern)", category: "Food & Beverage", area: "Gunawarman, South Jakarta", address: "Jl. Gunawarman 61, 2nd Floor", priceRange: "$$$", rating: 4.8, reviewCount: 796, ratingSource: "Google", highlights: ["Modern Spanish", "Gunawarman destination", "Highly-rated"], description: "Modern Spanish above Jl. Gunawarman 61 with a highly-rated tasting-style menu.", sources: [SRC.wlSpanish] },
  { id: "javanegra", name: "Javanegra Gourmet Atelier", cuisine: "Spanish / European", category: "Food & Beverage", area: "Kebayoran Baru, South Jakarta", address: "Jl. Kramat Pela Raya No.212", priceRange: "$$$", rating: 4.6, reviewCount: 958, ratingSource: "Google", highlights: ["Coffee + Spanish-leaning menu", "Gourmet atelier", "All-day"], description: "Gourmet atelier blending speciality coffee with a Spanish-leaning all-day menu.", sources: [SRC.wlSpanish] },
  { id: "erre-urrechu", name: "ERRE & Urrechu Jakarta", cuisine: "Spanish", category: "Food & Beverage", area: "Kuningan, South Jakarta", address: "Jl. H. R. Rasuna Said No.5, East Kuningan", priceRange: "$$$$", rating: 4.9, reviewCount: 163, ratingSource: "Google", highlights: ["Chef Iñaki Oyarbide", "Spanish fine dining", "Strong tasting menu"], description: "Spanish fine-dining concept from chef Iñaki Oyarbide's group, with a tasting-menu format.", sources: [SRC.wlSpanish] },
  { id: "sudestada", name: "Sudestada Jakarta", cuisine: "Argentinian / Latin", category: "Food & Beverage", area: "Menteng, Central Jakarta", address: "Jl. Biliton No.18", priceRange: "$$$", rating: 4.7, reviewCount: 2647, ratingSource: "Google", highlights: ["Argentine asado", "Strong wine list", "Highly-reviewed"], description: "Argentinian asado-style grill with a Latin wine list — one of Menteng's most-reviewed destinations.", sources: [SRC.wlSpanish, SRC.wlAmerican] },
  { id: "la-posta", name: "La Posta — Taste of Argentina", cuisine: "Argentinian", category: "Food & Beverage", area: "Menteng, Central Jakarta", address: "Jl. Karet Pasar Baru Timur 5 No.25", priceRange: "$$$", rating: 4.6, reviewCount: 1086, ratingSource: "Google", highlights: ["Argentinian asado", "Tucked-away setting", "Bilingual menu"], description: "Tucked-away Argentine grill — asado meats, empanadas and a small but focused Latin wine list.", sources: [SRC.wlAmerican] },

  // ───────── AMERICAN / STEAKHOUSE ─────────
  { id: "wolfgangs", name: "Wolfgang's Steakhouse Jakarta", cuisine: "American Steakhouse", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "ELYSEE SCBD Level 6 Rooftop, Lot 21 SCBD", priceRange: "$$$$", rating: 4.5, ratingSource: "Google", highlights: ["NYC heritage", "Dry-aged USDA Prime", "Rooftop bar"], description: "Famed New York City steakhouse, the only Wolfgang's location with its own rooftop bar; dry-aged USDA Prime is the headline.", sources: [SRC.wniSteak, SRC.wlFineDining] },
  { id: "ab-steak", name: "AB Steak by Akira Back", cuisine: "American Steakhouse (Korean accent)", category: "Food & Beverage", area: "Setiabudi, South Jakarta", address: "MD Place, Jl. Setiabudi Selatan No.7", priceRange: "$$$$", highlights: ["Chef Akira Back", "Korean heritage cuts", "Premium steakhouse"], description: "Chef Akira Back's steakhouse weaving Korean heritage into the classic American steakhouse playbook.", sources: [SRC.wniSteak] },
  { id: "aged-butchered", name: "Aged + Butchered", cuisine: "American / Yakiniku Fusion", category: "Food", area: "Senopati, South Jakarta", priceRange: "$$$", highlights: ["Wagyu Truffle Mushroom Burger", "Dry-aged & wet-aged meats", "American–Yakiniku fusion"], description: "Avant-garde fusion of an American steakhouse and Asian Yakiniku, celebrating dry-aged and wet-aged meats.", sources: [SRC.wniSteak] },
  { id: "justus", name: "Justus Steakhouse", cuisine: "American Steakhouse", category: "Food", area: "Multiple branches", priceRange: "$$", highlights: ["15+ premium cuts", "Two-storey semi-open air", "Norwegian Salmon Steak"], description: "Premium steaks in a two-storey semi-open-air room with 15+ cuts: US Black Angus, Aussie Lamb Chop, Norwegian Salmon Steak.", sources: [SRC.wniSteak] },
  { id: "bluegrass", name: "Bluegrass Bar & Grill", cuisine: "American", category: "Food & Beverage", area: "Kuningan, South Jakarta", address: "Bakrie Tower, Jl. H. R. Rasuna Said Lt. G", priceRange: "$$$", rating: 4.6, reviewCount: 3066, ratingSource: "Google", highlights: ["Live music nights", "American grill", "Bourbon bar"], description: "American grill and bourbon bar with live music nights in Kuningan.", sources: [SRC.wlAmerican] },
  { id: "tucanos", name: "Tucano's Brazilian BBQ", cuisine: "Brazilian Churrasco", category: "Food & Beverage", area: "Tanah Abang, Central Jakarta", address: "Pavilion Retail Arcade, Jl. K.H. Mas Mansyur No.24", priceRange: "$$$", rating: 4.6, reviewCount: 2933, ratingSource: "Google", highlights: ["All-you-can-eat churrasco", "Brazilian rodízio", "Caipirinha bar"], description: "All-you-can-eat Brazilian rodízio with skewered meats brought tableside and a caipirinha-led bar.", sources: [SRC.wlAmerican] },
  { id: "altitude-grill", name: "Altitude Grill", cuisine: "American Grill", category: "Food & Beverage", area: "Thamrin, Central Jakarta", address: "Plaza Office Tower, Jl. M.H. Thamrin No.28-30", priceRange: "$$$$", rating: 4.5, reviewCount: 482, ratingSource: "Google", highlights: ["46th-floor grill", "Steak & seafood", "Skyline views"], description: "Sky-level American grill at The Plaza Office Tower, with steak, seafood and panoramic views.", sources: [SRC.wlAmerican] },
  { id: "le-burger", name: "Le Burger", cuisine: "American (Burgers)", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "Discovery SCBD, Jl. Tulodong Atas 2 No.11", priceRange: "$$$", rating: 4.6, reviewCount: 1246, ratingSource: "Google", highlights: ["Premium burgers", "Dry-aged patties", "Cocktail bar"], description: "Premium burger destination at Discovery SCBD with dry-aged patties and a cocktail bar.", sources: [SRC.wlAmerican] },
  { id: "johnny-rockets", name: "Johnny Rockets", cuisine: "American Diner", category: "Food & Beverage", area: "Sudirman, Central Jakarta", address: "Jl. Jenderal Sudirman No.86", priceRange: "$$", rating: 4.3, reviewCount: 420, ratingSource: "Google", highlights: ["Smoke House Double Burger", "Classic shakes", "Retro diner"], description: "Classic American diner vibes — burgers, shakes and fries in a retro setting.", sources: [SRC.wlAmerican] },
  { id: "the-coach", name: "The Coach Restaurant", cuisine: "American / British", category: "Food & Beverage", area: "Thamrin, Central Jakarta", address: "Grand Indonesia West Mall, Jl. Teluk Betung No.45A", priceRange: "$$$", rating: 4.7, reviewCount: 253, ratingSource: "Google", highlights: ["Pub-style menu", "Hearty mains", "Beer + cocktails"], description: "British-American pub-style restaurant in Grand Indonesia West Mall.", sources: [SRC.wlAmerican] },

  // ───────── BRITISH / MODERN EUROPEAN ─────────
  { id: "the-crown", name: "The Crown by Kirk Westaway", cuisine: "Modern British", category: "Food & Beverage", area: "Senayan, Central Jakarta", address: "Fairmont Jakarta, 22nd floor", priceRange: "$$$$", highlights: ["Modern British", "World-class fine dining", "Panoramic views"], description: "Fairmont Jakarta's 22nd-floor fine dining, presenting modern British cuisine with city vistas.", sources: [SRC.wniFineDining] },
  { id: "queens-head", name: "Queens Head Jakarta", cuisine: "British / Asian Fusion", category: "Food & Beverage", area: "Kemang, South Jakarta", address: "Jl. Kemang Raya No.18C", priceRange: "$$$", rating: 4.5, reviewCount: 0, ratingSource: "TripAdvisor", highlights: ["Gastropub feel", "British-Asian fusion", "Kemang setting"], description: "Kemang gastropub-style spot bridging British classics with Asian flavour.", sources: [SRC.wlEuropean] },
  { id: "animale", name: "Animale Restaurant", cuisine: "Mediterranean / American", category: "Food & Beverage", area: "Kuningan, South Jakarta", address: "MD Place 11th Floor, Jl. Setia Budi Selatan No.7", priceRange: "$$$$", rating: 4.7, reviewCount: 1405, ratingSource: "Google", highlights: ["Mediterranean-American", "11th-floor views", "Cocktail-led drinks"], description: "11th-floor Mediterranean-American with cocktail-led drinks at MD Place.", sources: [SRC.wlFineDining, SRC.wlNice] },
  { id: "skye", name: "SKYE Rooftop Dining & Lounge", cuisine: "International (Hispanic / ME / Asian)", category: "Food & Beverage", area: "Thamrin, Central Jakarta", address: "BCA Tower 56th Floor, Grand Indonesia, Jl. M.H. Thamrin No.1", priceRange: "$$$$", rating: 4.6, reviewCount: 6276, ratingSource: "Google", highlights: ["56th-floor rooftop", "International tapas", "Bundaran HI views"], description: "56th-floor BCA Tower rooftop with international Hispanic/Middle Eastern/Asian tapas and panoramic Bundaran HI views.", sources: [SRC.wlNice, SRC.wlFineDining] },

  // ───────── INTERNATIONAL BEVERAGES ─────────
  { id: "pantja", name: "Pantja", cuisine: "Cocktail Bar / Modern Dining", category: "Beverage", area: "Senopati, South Jakarta", priceRange: "$$$", highlights: ["Asia's 50 Best Bars 2024", "Farm-to-table", "Open-fire cooking"], description: "Senopati cocktail crown jewel and Asia's 50 Best Bars 2024 — farm-to-table restaurant-and-bar with seasonal ingredients and open-fire cooking.", sources: [SRC.wniBars] },
  { id: "cocktail-club", name: "The Cocktail Club", cuisine: "Cocktail Bar", category: "Beverage", area: "Senopati, South Jakarta", priceRange: "$$$", highlights: ["Best Bar Indonesia 2024", "#12 Asia's 50 Best 2024", "Bartender-run"], description: "Bartender-run bar awarded Best Cocktail Menu 2024, Best Bar in Indonesia 2024, and #12 in Asia's 50 Best Bars 2024.", sources: [SRC.wniBars] },
  { id: "duck-down", name: "Duck Down Bar", cuisine: "Cocktail Bar", category: "Beverage", area: "Senopati, South Jakarta", priceRange: "$$$", highlights: ["Intimate setting", "Creative mixology", "Cosy lounge"], description: "Creative-mixology cocktail bar in Senopati known for an intimate, cosy ambience.", sources: [SRC.nowBars] },
  { id: "between-the-sips", name: "Between the Sips", cuisine: "Cocktail Bar", category: "Beverage", area: "Senopati, South Jakarta", address: "Above Kintaro Sushi, Senopati", priceRange: "$$$", highlights: ["Hidden upstairs bar", "Newer arrival", "Speakeasy"], description: "Newer Senopati cocktail bar concealed above Kintaro Sushi — a speakeasy-style hideaway.", sources: [SRC.nowBars] },
  { id: "oddbird", name: "The Oddbird Bar", cuisine: "Cocktail Bar / Latin Tapas", category: "Food & Beverage", area: "SCBD, South Jakarta", address: "25hours Hotel, SCBD", priceRange: "$$$", highlights: ["Latin-inspired tapas", "Global cocktails", "Hotel destination"], description: "Inside the 25hours Hotel — Latin-inspired tapas meet globally influenced cocktails.", sources: [SRC.wniBars] },
  { id: "truce", name: "Truce", cuisine: "Cocktail Bar (Japanese-style)", category: "Beverage", area: "SCBD, South Jakarta", priceRange: "$$$", highlights: ["Japanese slow-bar philosophy", "Restraint & precision", "SCBD hideaway"], description: "Slow bar tucked in SCBD, taking cues from Japanese philosophy — balance, restraint and quiet precision.", sources: [SRC.wniBars] },
  { id: "cork-screw", name: "Cork & Screw Country Club", cuisine: "Wine Bar / Restaurant", category: "Food & Beverage", area: "SCBD, South Jakarta", priceRange: "$$$", highlights: ["Extensive wine list", "Crafted cocktails", "International menu"], description: "Sophisticated SCBD establishment renowned for an extensive wine list and expertly crafted cocktails.", sources: [SRC.wniBars] },
  { id: "beer-garden-scbd", name: "Beer Garden SCBD", cuisine: "Craft Beer / Sports Bar", category: "Food & Beverage", area: "SCBD, South Jakarta", priceRange: "$$", highlights: ["Best Beer House award", "Sports-bar atmosphere", "International beers"], description: "Popular SCBD beer destination with branches across Jakarta; multiple Best Beer House and Best Pub/Sports Bar awards.", sources: [SRC.wniBars] },
];

export function googleMapsUrl(r: Restaurant): string {
  const q = [r.name, r.address ?? r.area, "Jakarta"]
    .filter(Boolean)
    .join(", ");
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

/**
 * Returns a Google Maps embed URL that uses Google's public text-query
 * format — no API key needed, suitable for iframe `src`. Production use
 * should swap to the keyed Maps Embed API or Mapbox/Apple MapKit.
 */
export function mapsEmbedUrl(r: Restaurant): string {
  const q = [r.name, r.address ?? r.area, "Jakarta"]
    .filter(Boolean)
    .join(", ");
  return `https://www.google.com/maps?q=${encodeURIComponent(q)}&hl=en&z=16&output=embed`;
}

export function getCuisineList(): string[] {
  return Array.from(new Set(RESTAURANTS.map((r) => r.cuisine))).sort();
}

export function getAreaList(): string[] {
  return Array.from(new Set(RESTAURANTS.map((r) => r.area))).sort();
}
