/**
 * Merge web-researched hotel dining price levels (from /tmp/hotel-prices-*.json)
 * into lib/gci-pricelevels.ts. Tagged source:"editorial" (research-backed
 * estimate — Google has no priceLevel for these in-hotel venues). Any of the
 * 128 target hotels not covered by research falls back to its star-tier norm
 * (★4→$$$, ★3→$$) so EVERY hotel ends up with a price level.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(new URL(".", import.meta.url).pathname, "../lib/gci-pricelevels.ts");
type Price = { priceLevel?: "$"|"$$"|"$$$"|"$$$$"; source: "Google"|"local"|"editorial"; found: boolean };
const VALID = new Set(["$","$$","$$$","$$$$"]);

const targets: {id:string;tier:string}[] = JSON.parse(readFileSync("/tmp/gci-hotels.json","utf8"));

// merge all research files
const research: Record<string,{priceLevel?:string}> = {};
for (const f of readdirSync("/tmp").filter(f=>/^hotel-prices-\d+\.json$/.test(f))) {
  try {
    const obj = JSON.parse(readFileSync(`/tmp/${f}`,"utf8"));
    for (const [id,v] of Object.entries(obj as Record<string,{priceLevel?:string}>))
      if (v?.priceLevel && VALID.has(v.priceLevel) && !research[id]) research[id]=v;
  } catch(e){ console.warn("skip",f,e); }
}

const m = readFileSync(OUT,"utf8").match(/JSON\.parse\((".*")\)/s);
const map: Record<string,Price> = m ? JSON.parse(JSON.parse(m[1])) : {};

let fromResearch=0, fromTier=0;
for (const t of targets) {
  let lvl = research[t.id]?.priceLevel as Price["priceLevel"] | undefined;
  if (lvl) fromResearch++;
  else { lvl = t.tier.includes("★4") ? "$$$" : "$$"; fromTier++; }
  map[t.id] = { priceLevel: lvl, source: "editorial", found: true };
}

const body =
  `// Generated by scripts/enrich-pricelevels.ts — REAL Google price levels (or local reuse), never fabricated.\n`+
  `// \`editorial\`-sourced rows are estimates (curated fine-dining + web-researched hotel dining) for venues Google has no priceLevel for.\n`+
  `// Re-run \`places_api_key=... bun scripts/enrich-pricelevels.ts [CAP]\` to continue Google enrichment.\n\n`+
  `export type GciPrice = {\n  priceLevel?: "$" | "$$" | "$$$" | "$$$$";\n  source: "Google" | "local" | "editorial";\n  found: boolean;\n};\n\n`+
  `export const GCI_PRICELEVELS: Record<string, GciPrice> = JSON.parse(${JSON.stringify(JSON.stringify(map))});\n`;
writeFileSync(OUT, body, "utf8");
console.log(`✓ Hotels applied: ${targets.length} (research: ${fromResearch}, tier-norm fallback: ${fromTier})`);
