/**
 * Editorial price levels for in-hotel fine-dining / all-day venues that Google
 * has NO priceLevel for (verified empty via both Place Details and searchText).
 * These are NOT Google data — they are editorial estimates based on the venue
 * type and the hotel's market class, and are tagged `source: "editorial"` so
 * they remain distinguishable from real Google ($) levels.
 *
 *   bun scripts/apply-editorial-pricelevels.ts   (no API key, no calls)
 */

import { writeFileSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(new URL(".", import.meta.url).pathname, "../lib/gci-pricelevels.ts");

type Price = { priceLevel?: "$" | "$$" | "$$$" | "$$$$"; source: "Google" | "local" | "editorial"; found: boolean };

// Editorial: Mercure/Aston midscale → $$; Pullman/Novotel/standalone upscale → $$$.
const EDITORIAL: Record<string, "$$" | "$$$"> = {
  "h-food-exchange-cikini": "$$$",
  "h-food-exchange-mangga2": "$$$",
  "h-botany-holidayinn-kemayoran": "$$$",
  "h-adele-ashley": "$$$",
  "h-the-square-gajahmada": "$$$",
  "h-gourmet-bar-mangga2": "$$$",
  "garden-osteria": "$$$",
  "cutt-grill": "$$$",
  "sir-loin": "$$$",
  "h-silangit-aston-kemayoran": "$$",
  "h-spice-mercure-kota": "$$",
  "h-lobby-mercure-sabang": "$$",
  "thai-street": "$$",
};

const m = readFileSync(OUT, "utf8").match(/JSON\.parse\((".*")\)/s);
const map: Record<string, Price> = m ? JSON.parse(JSON.parse(m[1])) : {};

let n = 0;
for (const [id, lvl] of Object.entries(EDITORIAL)) {
  map[id] = { priceLevel: lvl, source: "editorial", found: true };
  n++;
}

const body =
  `// Generated by scripts/enrich-pricelevels.ts — REAL Google price levels (or local reuse), never fabricated.\n` +
  `// \`editorial\`-sourced rows are estimates for in-hotel venues Google has no priceLevel for (scripts/apply-editorial-pricelevels.ts).\n` +
  `// Re-run \`places_api_key=... bun scripts/enrich-pricelevels.ts [CAP]\` to continue Google enrichment.\n\n` +
  `export type GciPrice = {\n  priceLevel?: "$" | "$$" | "$$$" | "$$$$";\n  source: "Google" | "local" | "editorial";\n  found: boolean;\n};\n\n` +
  `export const GCI_PRICELEVELS: Record<string, GciPrice> = JSON.parse(${JSON.stringify(JSON.stringify(map))});\n`;
writeFileSync(OUT, body, "utf8");
console.log(`✓ Applied ${n} editorial price levels → ${OUT}`);
