/**
 * Clear ratings that are misattached (belong to the mall/landmark/another place,
 * not the venue). Sets the venue's GCI_RATINGS entry to { found:false } so it
 * shows "belum ada rating" instead of a misleading number. Reversible via git.
 *
 *   bun scripts/clear-bad-ratings.ts        (no API calls)
 *
 * Sources: /tmp/gci-badrating.json (verified name-mismatches) minus a KEEP list
 * of confirmed same-place naming variants, plus mall-name venues whose huge
 * review counts are clearly the mall's.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { GCI_RESTAURANTS } from "../lib/gci";

const RATINGS = resolve(new URL(".", import.meta.url).pathname, "../lib/gci-ratings.ts");

// same-place naming variants — NOT misleading, keep their ratings
const KEEP_NAMES = new Set([
  "Hotel Ashley",
  "Rumah Makan Bopet Mini Bendungan Hilir",
  "Mbah Jingkrak Setiabudi",
  "Iga Bakar Tekko",
  "Warung Kemuning",
  "TAMANI PLAZA SENAYAN",
]);

const bad = JSON.parse(readFileSync("/tmp/gci-badrating.json", "utf8")) as { id: string; name: string }[];
const toClear = new Set<string>();
for (const b of bad) if (!KEEP_NAMES.has(b.name)) toClear.add(b.id);

// mall-name venues with huge review counts (the rating is the mall's)
const MALL = /\bmall\b|emporium|lotte mall|mall artha gading|pluit village|plaza senayan mall/i;
for (const r of GCI_RESTAURANTS) {
  if (r.placeId && (r.reviewCount ?? 0) >= 15000 && (r.tier === "Restoran" || r.tier === "Cafe") && MALL.test(r.name))
    toClear.add(r.id);
}

// load + rewrite gci-ratings.ts
const txt = readFileSync(RATINGS, "utf8");
const m = txt.match(/JSON\.parse\((".*")\)/s);
if (!m) { console.error("Could not parse GCI_RATINGS"); process.exit(1); }
const map = JSON.parse(JSON.parse(m[1])) as Record<string, any>;

let cleared = 0;
const nameOf = new Map(GCI_RESTAURANTS.map(r => [r.id, r.name] as const));
for (const id of toClear) {
  if (map[id]) { map[id] = { found: false }; cleared++; console.log(`· cleared ${nameOf.get(id) ?? id}`); }
}

const header =
  "// Generated by scripts/enrich-ratings.ts — REAL Google ratings, never fabricated.\n" +
  "// Re-run `GOOGLE_PLACES_API_KEY=... bun scripts/enrich-ratings.ts` to refresh/continue.\n" +
  "// Some entries cleared to { found:false } by scripts/clear-bad-ratings.ts (rating belonged to the mall/landmark, not the venue).\n\n";
const body =
  header +
  "export type GciRating = {\n  rating?: number;\n  reviewCount?: number;\n  source?: \"Google\";\n  placeId?: string;\n  found: boolean;\n};\n\n" +
  `export const GCI_RATINGS: Record<string, GciRating> = JSON.parse(${JSON.stringify(JSON.stringify(map))});\n`;
writeFileSync(RATINGS, body, "utf8");
console.log(`\n✓ Cleared ${cleared} misattached ratings → ${RATINGS}`);
