/**
 * Price-level enrichment — attaches a REAL Google price level ($–$$$$) to GCI
 * venues. Never fabricated: a venue only gets a value if Google returns one.
 *
 *   places_api_key=xxxx bun scripts/enrich-pricelevels.ts [CAP]
 *
 * Strategy (cheapest-first, capped):
 *  1. REUSE local priceRange from lib/restaurants.ts by name (free, 0 calls).
 *  2. For venues still missing AND that have a cached placeId, do a Place
 *     Details (New) lookup with field mask = `priceLevel` ONLY → Enterprise SKU.
 *     Sorted curated-first then by review count, and HARD-CAPPED (default 900)
 *     so the run stays within the 1,000/month Enterprise free tier (~$0).
 *  3. Venues with no placeId are skipped (would need pricier searchText).
 *
 * Resumable: re-reads lib/gci-pricelevels.ts and skips venues already resolved.
 * The CAP counts only NEW billable Place Details calls this run.
 */

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { GCI_RESTAURANTS } from "../lib/gci";
import { GCI_RATINGS } from "../lib/gci-ratings";
import { RESTAURANTS } from "../lib/restaurants";

const KEY =
  process.env.places_api_key ?? process.env.PLACES_API_KEY ?? process.env.GOOGLE_PLACES_API_KEY;
if (!KEY) {
  console.error("✗ Set places_api_key in .env (Places API New, billing enabled).");
  process.exit(1);
}

const CAP = Number(process.argv[2]) || 900;
const OUT = resolve(new URL(".", import.meta.url).pathname, "../lib/gci-pricelevels.ts");
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

type Price = {
  priceLevel?: "$" | "$$" | "$$$" | "$$$$";
  source: "Google" | "local";
  found: boolean;
};

const norm = (s: string) =>
  s.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9 ]+/g, " ").replace(/\s+/g, " ").trim();

const ENUM: Record<string, Price["priceLevel"]> = {
  PRICE_LEVEL_INEXPENSIVE: "$",
  PRICE_LEVEL_MODERATE: "$$",
  PRICE_LEVEL_EXPENSIVE: "$$$",
  PRICE_LEVEL_VERY_EXPENSIVE: "$$$$",
};

function loadExisting(): Record<string, Price> {
  if (!existsSync(OUT)) return {};
  try {
    const m = readFileSync(OUT, "utf8").match(/JSON\.parse\((".*")\)/s);
    if (m) return JSON.parse(JSON.parse(m[1]));
  } catch {}
  return {};
}

function save(map: Record<string, Price>) {
  const body =
    `// Generated by scripts/enrich-pricelevels.ts — REAL Google price levels (or local reuse), never fabricated.\n` +
    `// Re-run \`places_api_key=... bun scripts/enrich-pricelevels.ts [CAP]\` to continue.\n\n` +
    `export type GciPrice = {\n  priceLevel?: "$" | "$$" | "$$$" | "$$$$";\n  source: "Google" | "local";\n  found: boolean;\n};\n\n` +
    `export const GCI_PRICELEVELS: Record<string, GciPrice> = JSON.parse(${JSON.stringify(JSON.stringify(map))});\n`;
  writeFileSync(OUT, body, "utf8");
}

async function fetchPrice(placeId: string): Promise<Price["priceLevel"] | null> {
  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch(`https://places.googleapis.com/v1/places/${encodeURIComponent(placeId)}`, {
      headers: { "X-Goog-Api-Key": KEY!, "X-Goog-FieldMask": "priceLevel" },
    });
    if (res.status >= 500) { await sleep(1000 * (attempt + 1)); continue; }
    if (!res.ok) { console.warn(`  ! ${placeId}: HTTP ${res.status} ${await res.text()}`); return null; }
    const data = (await res.json()) as { priceLevel?: string };
    return data.priceLevel ? ENUM[data.priceLevel] ?? null : null;
  }
  return null;
}

async function main() {
  // 1) local reuse map (free)
  const local = new Map<string, "$" | "$$" | "$$$" | "$$$$">();
  for (const r of RESTAURANTS) if (r.priceRange) { const k = norm(r.name); if (!local.has(k)) local.set(k, r.priceRange); }
  const reuse = (name: string) => {
    const k = norm(name);
    if (local.has(k)) return local.get(k);
    for (const [kk, v] of local) if (kk.length > 5 && (kk.includes(k) || k.includes(kk))) return v;
    return undefined;
  };

  const map = loadExisting();

  // Fill any not-yet-recorded local reuses (free, no call).
  let localFilled = 0;
  for (const r of GCI_RESTAURANTS) {
    if (map[r.id]?.found) continue;
    const p = reuse(r.name);
    if (p) { map[r.id] = { priceLevel: p, source: "local", found: true }; localFilled++; }
  }

  // 2) build callable queue: not-yet-attempted (either way) + has placeId,
  //    excluding hotels (Google rarely has priceLevel for them), prioritized by
  //    popularity (more reviews → more likely Google has a priceLevel).
  const HOTEL = /hotel|hotels|resort|\binn\b|suites|residence|wyndham|mercure|aston|ibis|fave|harris|swiss-?bel|santika|amaris|ascott|conference/i;
  const queue = GCI_RESTAURANTS
    .filter((r) => map[r.id] === undefined && !HOTEL.test(r.name) && (GCI_RATINGS as Record<string, { placeId?: string }>)[r.id]?.placeId)
    .map((r) => ({ r, pid: (GCI_RATINGS as Record<string, { placeId?: string; reviewCount?: number }>)[r.id] }))
    .sort((a, b) => (b.pid?.reviewCount ?? 0) - (a.pid?.reviewCount ?? 0));

  console.log(`Local reuse filled: ${localFilled} (total local in store: ${Object.values(map).filter((v) => v.source === "local").length})`);
  console.log(`Callable (missing + placeId): ${queue.length}. Cap this run: ${CAP}.`);

  let called = 0, hit = 0;
  for (const { r, pid } of queue) {
    if (called >= CAP) break;
    called++;
    const lvl = await fetchPrice(pid!.placeId!);
    map[r.id] = lvl ? { priceLevel: lvl, source: "Google", found: true } : { source: "Google", found: false };
    if (lvl) { hit++; console.log(`✓ ${r.name} → ${lvl}`); }
    else console.log(`· ${r.name} — no priceLevel`);
    if (called % 25 === 0) save(map);
    await sleep(85); // ~12 req/s
  }
  save(map);
  console.log(`\n✓ Wrote ${OUT}\n  Place Details calls this run: ${called} · with priceLevel: ${hit} · empty: ${called - hit}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
