/**
 * Targeted price-level rescue for CURATED venues (esp. in-hotel fine dining)
 * that Place Details left blank — the cached placeId often points at the HOTEL,
 * not the restaurant. Here we run a fresh Places searchText by "name, area"
 * with a field mask that includes `priceLevel`, so we can land the restaurant's
 * own entry and read its price level. Small set → within the free tier.
 *
 *   places_api_key=xxxx bun scripts/enrich-pricelevels-search.ts
 *
 * Updates lib/gci-pricelevels.ts in place. Name-guarded + DKI-guarded so we
 * never attach a wrong venue's price level. Resumable (skips already-found).
 */

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { GCI_RESTAURANTS, gciAddress } from "../lib/gci";

const KEY =
  process.env.places_api_key ?? process.env.PLACES_API_KEY ?? process.env.GOOGLE_PLACES_API_KEY;
if (!KEY) { console.error("✗ Set places_api_key in .env"); process.exit(1); }

const OUT = resolve(new URL(".", import.meta.url).pathname, "../lib/gci-pricelevels.ts");
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const BODETABEK = /bogor|depok|tangerang|bekasi|karawang|cikarang|serpong|\bbsd\b/i;

type Price = { priceLevel?: "$" | "$$" | "$$$" | "$$$$"; source: "Google" | "local"; found: boolean };
const ENUM: Record<string, Price["priceLevel"]> = {
  PRICE_LEVEL_INEXPENSIVE: "$", PRICE_LEVEL_MODERATE: "$$", PRICE_LEVEL_EXPENSIVE: "$$$", PRICE_LEVEL_VERY_EXPENSIVE: "$$$$",
};
const norm = (s: string) => s.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9 ]+/g, " ").replace(/\s+/g, " ").trim();
const nameOk = (q: string, m: string) => { if (!m) return false; const a = norm(q), b = norm(m); return a.includes(b) || b.includes(a); };

function load(): Record<string, Price> {
  if (!existsSync(OUT)) return {};
  try { const m = readFileSync(OUT, "utf8").match(/JSON\.parse\((".*")\)/s); if (m) return JSON.parse(JSON.parse(m[1])); } catch {}
  return {};
}
function save(map: Record<string, Price>) {
  const body =
    `// Generated by scripts/enrich-pricelevels.ts — REAL Google price levels (or local reuse), never fabricated.\n` +
    `// Re-run \`places_api_key=... bun scripts/enrich-pricelevels.ts [CAP]\` to continue.\n\n` +
    `export type GciPrice = {\n  priceLevel?: "$" | "$$" | "$$$" | "$$$$";\n  source: "Google" | "local";\n  found: boolean;\n};\n\n` +
    `export const GCI_PRICELEVELS: Record<string, GciPrice> = JSON.parse(${JSON.stringify(JSON.stringify(map))});\n`;
  writeFileSync(OUT, body, "utf8");
}

async function search(name: string, area: string): Promise<{ lvl: Price["priceLevel"] | null; ok: boolean }> {
  const body = { textQuery: `${name}, ${area}`, maxResultCount: 1, languageCode: "id" };
  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch("https://places.googleapis.com/v1/places:searchText", {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-Goog-Api-Key": KEY!, "X-Goog-FieldMask": "places.displayName,places.formattedAddress,places.priceLevel" },
      body: JSON.stringify(body),
    });
    if (res.status >= 500) { await sleep(1000 * (attempt + 1)); continue; }
    if (!res.ok) { console.warn(`  ! ${name}: HTTP ${res.status} ${await res.text()}`); return { lvl: null, ok: false }; }
    const data = (await res.json()) as { places?: { displayName?: { text?: string }; formattedAddress?: string; priceLevel?: string }[] };
    const p = data.places?.[0];
    if (!p) return { lvl: null, ok: false };
    const addr = p.formattedAddress ?? "";
    if (!nameOk(name, p.displayName?.text ?? "") || BODETABEK.test(addr) || !/jakarta/i.test(addr)) {
      if (process.env.VERBOSE) console.log(`  ✗ "${name}" → "${p.displayName?.text}" / ${addr} rejected`);
      return { lvl: null, ok: false };
    }
    return { lvl: p.priceLevel ? ENUM[p.priceLevel] ?? null : null, ok: true };
  }
  return { lvl: null, ok: false };
}

async function main() {
  const map = load();
  // Curated venues that still lack a price level (blank or Google-empty).
  const targets = GCI_RESTAURANTS.filter((r) => r.source === "curated" && !map[r.id]?.priceLevel);
  console.log(`Curated venues missing price level: ${targets.length}`);

  let hit = 0, called = 0;
  for (const r of targets) {
    const area = gciAddress(r) || (r as { area?: string }).area || "Jakarta";
    const { lvl, ok } = await search(r.name, area);
    called++;
    if (lvl) { map[r.id] = { priceLevel: lvl, source: "Google", found: true }; hit++; console.log(`✓ ${r.name} → ${lvl}`); }
    else { map[r.id] = { source: "Google", found: ok ? false : (map[r.id]?.found ?? false) }; console.log(`· ${r.name} — no priceLevel${ok ? "" : " (no match)"}`); }
    if (called % 10 === 0) save(map);
    await sleep(120);
  }
  save(map);
  console.log(`\n✓ Updated ${OUT}\n  searchText calls: ${called} · new price levels: ${hit}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
